### ISSUE TITLE
PG::InsufficientPrivilege: ERROR:  permission denied to create extension "hstore"

### ISSUE THREAD

**Issue by wixyvir** [bitnami/bitnami-docker-discourse#105]
**Description**

I am using "latest" docker images, when I instantiate discourse a first time, it works fine. But if I drop the discourse container, and re-instantiate one with the same volumes (on `/bitnami`), then it won't properly start because entrypoint script is trying to migrate database again, and is trying to create PG extensions again, as a non super-user.

**Steps to reproduce the issue:**

1. docker-compose up # with bind volumes on /bitnami
2. Set up discourse, log-in, configure...
3. Drop the discourse service container
4. Re-instantiate a discourse service container # with same volumes as the one in 1.

**Describe the results you received:**

It does not start and produce the following error

```
Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing postgresql-client
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql:5432
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Migrating database...
Error executing 'postInstallation': rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InsufficientPrivilege: ERROR:  permission denied to create extension "hstore"
HINT:  Must be superuser to create this extension.
: CREATE EXTENSION IF NOT EXISTS hstore
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/rack-mini-profiler-1.0.2/lib/patches/db/pg.rb:110:in `async_exec'
[...]

Caused by:
ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied to create extension "hstore"
HINT:  Must be superuser to create this extension.
: CREATE EXTENSION IF NOT EXISTS hstore
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/rack-mini-profiler-1.0.2/lib/patches/db/pg.rb:110:in `async_exec'
[...]

Caused by:
PG::InsufficientPrivilege: ERROR:  permission denied to create extension "hstore"
HINT:  Must be superuser to create this extension.
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/rack-mini-profiler-1.0.2/lib/patches/db/pg.rb:110:in `async_exec'
[...]
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Describe the results you expected:**

Discourse should be available

**Additional information you deem important (e.g. issue happens only occasionally):**

Also is there a way to know what this is doing https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-9/Dockerfile#L5-L11 ? Where are those packages sources ?

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:40:56 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Containers: 28
 Running: 26
 Paused: 0
 Stopped: 2
Images: 31
Server Version: 18.09.0
Storage Driver: devicemapper
 Pool Name: centos_tech-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data Space Used: 24.19GB
 Data Space Total: 42.95GB
 Data Space Available: 18.76GB
 Metadata Space Used: 24.07MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.123GB
 Thin Pool Minimum Free Space: 4.295GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.149-RHEL7 (2018-07-20)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: xv2y1ldk3u1ppb19gl4cf58jp
 Is Manager: true
 ClusterID: r4c2zh4pkmmk8u5tp2pbj52gf
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.0.75
 Manager Addresses:
  10.0.0.75:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.20.4-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.776GiB
Name: srv-tool0
ID: FS73:MACJ:V3CW:72SP:PEI2:7TNZ:CIF6:XCEU:EQ26:TNGP:R6WR:BVCQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 env=tools
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: bridge-nf-call-ip6tables is disabled
```

Thank you for your help !

**Comment by tompizmor** [comment]
Hi @wixyvir,

I tried with this docker-compose file and it worked fine after running `docker-compose up`, `docker-compose down` and `docker-compose up` again.

```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse:2'
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=127.0.0.1
  sidekiq:
    image: 'bitnami/discourse:2'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=127.0.0.1
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

> Also is there a way to know what this is doing https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-9/Dockerfile#L5-L11 ? Where are those packages sources ?

You can see the source files inside the container at `/root/.nami/components`.

There are some components that are installed directly in the Dockerfile while others are unpacked in the Dockerfile and initialized in the entrypoint.sh. So basically `bitnami-pkg install` = `bitnami-pkg unpack` + `bitnami-pkg initialize`
