### ISSUE TITLE
/usr/sbin/sendmail and unable to provision at all from docker-compose.yml

### ISSUE THREAD

**Issue by MatthewCroughan** [bitnami/bitnami-docker-discourse#106]
Try as I might for the past hour, for unknown reasons I cannot get any form of success with this compose file.

Docker version 19.03.1-ce, build 74b1e89e8a

![image](https://user-images.githubusercontent.com/26458780/62815841-764dde00-bb16-11e9-918b-68506cb913a4.png)

This is upon provisioning with `docker-compose up -d` and waiting 5 minutes. 

![image](https://user-images.githubusercontent.com/26458780/62815846-8a91db00-bb16-11e9-800a-cdda3f8679ac.png)

I then get a completely blank screen upon trying to visit the site. Https shows up for a split second in my browser, then it redirects to HTTP, however I am not even attempting to access it via port 80. So it's trying to redirect like so:

http > https > http

Why is this so hard? I've tried this on multiple machines now, and I don't even have a point to debug from. 

This is the log output for the discourse container after visiting http://127.0.0.1

![image](https://user-images.githubusercontent.com/26458780/62815867-caf15900-bb16-11e9-9996-809195ee54d0.png)

I set `DISCOURSE_HOSTNAME=localhost` just to be clear.

**Comment by MatthewCroughan** [comment]
@rafariossaa I found the issue was not putting the port identifier after localhost.
`DISCOURSE_HOSTNAME=localhost:3000` for example works fine. 

This is documented in #100, however I really think it needs to be mentioned somewhere in the README.

**Comment by MatthewCroughan** [comment]
Another issue I have is that adding `DISCOURSE_SKIP_INSTALL=yes` seems not to do anything, I'm still presented with a blank forum, when what I expect to happen is to be greeted with the "Welcome to Discourse!" startup wizard, so I can import a database file. Is this not the intention?

**Comment by rafariossaa** [comment]
Hi, 
  You need to add that environment variable to the discourse container in the docker-compose, I also set the hostname to localhost:8080 and set the port to 8080.

```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse:2'
    ports:
      - '8080:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=localhost:8080
      - DISCOURSE_SKIP_INSTALL=yes
  sidekiq:
    image: 'bitnami/discourse:2'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=localhost:8080
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local

```

This will start discourse and when I browsed to http://localhost:8080 I got the "Congratulations" screen and the first step is to set the admin credentials manually.

If that didn't happen to you, maybe you didn't delete the volumes when shutting down the compose. (docker-compose down -v)

Could you check that ?
