### ISSUE TITLE
Random settings persistence

### ISSUE THREAD

**Issue by gregoryboue** [bitnami/bitnami-docker-discourse#107]
**Description**

On an openshift installation (see yaml config below) 

When i setup with the wizard and i change the language, themes and other informations.
After that, if i refresh the home page in my web browser, i sometimes had the old theme and old language, sometimes old theme and new language, sometimes new theme and new language…

It’s totally random and if i reboot pod with discourse, it’s seems to be better but if i change settings again, the problem appears again…

**Steps to reproduce the issue:**

1. Install discourse with the config.yml below
2. Go to the homepage and login with user/bitnami123
3. Setup the wizard, select a name, a theme....
4. Go to the homepage and refresh several time

**Describe the results you received:**

I sometimes had the old theme and old language, sometimes old theme and new language, sometimes new theme and new language…

**Describe the results you expected:**

To get the settings that i setup effective

**Version**

Openshift 3.11.98

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

```
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: test-postgresql
  name: test-postgresql
spec:
  replicas: 1
  selector:
    app: test-postgresql
  template:
    metadata:
      labels:
        app: test-postgresql
    spec:
      containers:
      - image: bitnami/postgresql:11-ol-7
        name: test-postgresql
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        volumeMounts:
          - mountPath: /bitnami
            name: volume-postgres
      volumes:
        - name: volume-postgres
          persistentVolumeClaim:
            claimName: postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-postgresql
  name: test-postgresql
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: test-postgresql
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: test-redis
  name: test-redis
spec:
  replicas: 1
  selector:
    app: test-redis
  template:
    metadata:
      labels:
        app: test-redis
    spec:
      containers:
      - image: docker-public-nexusm-repo-gpf.apps.eul.sncf.fr/bitnami/redis:5.0-ol-7
        name: test-redis
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes" 
        volumeMounts:
          - mountPath: /bitnami
            name: volume-redis
      volumes:
        - name: volume-redis
          persistentVolumeClaim:
            claimName: redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-redis
  name: test-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: test-redis
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: test-discourse
  name: test-discourse
spec:
  replicas: 1
  selector:
    app: test-discourse
  template:
    metadata:
      labels:
        app: test-discourse
    spec:
      containers:
      - image: bitnami/discourse:2-ol-7
        name: test-discourse
        env:
        - name: POSTGRESQL_HOST
          value: test-postgresql
        - name: POSTGRESQL_ROOT_USER
          value: postgres
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
          value: bitnami_application
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
          value: bn_discourse
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
          value: bitnami1
        - name: DISCOURSE_POSTGRESQL_NAME
          value: bitnami_application
        - name: DISCOURSE_POSTGRESQL_USERNAME
          value: bn_discourse
        - name: DISCOURSE_POSTGRESQL_PASSWORD
          value: bitnami1
        - name: DISCOURSE_HOSTNAME
          value: XXXXX
        - name: REDIS_HOST
          value: test-redis
        - name: REDIS_PORT_NUMBER
          value: "6379"
        - name: UNICORN_WORKERS
          value: '2'
        volumeMounts:
          - mountPath: /bitnami
            name: volume-discourse
      volumes:
        - name: volume-discourse
          persistentVolumeClaim:
            claimName: discourse
      serviceAccount: discourse-user
      serviceAccountName: discourse-user

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-discourse
  name: test-discourse
spec:
  ports:
  - name: 3000-https
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: test-discourse
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: test-sidekiq
  labels:
    app: test-sidekiq
spec:
  containers:
  - name: sidekiq
    image: bitnami/discourse:2-ol-7
    args:
    - nami
    - start
    - --foreground
    - discourse-sidekiq
    env:
    - name: POSTGRESQL_HOST
      value: test-postgresql
    - name: POSTGRESQL_ROOT_USER
      value: postgres
    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
      value: bitnami_application
    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
      value: bn_discourse
    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
      value: bitnami1
    - name: DISCOURSE_POSTGRESQL_NAME
      value: bitnami_application
    - name: DISCOURSE_POSTGRESQL_USERNAME
      value: bn_discourse
    - name: DISCOURSE_POSTGRESQL_PASSWORD
      value: bitnami1
    - name: DISCOURSE_HOST
      value: test-discourse
    - name: DISCOURSE_PORT
      value: "3000"
    - name: DISCOURSE_HOSTNAME
      value: XXXXX
    - name: REDIS_HOST
      value: test-redis
    - name: REDIS_PORT_NUMBER
      value: "6379"
    volumeMounts:
      - mountPath: /bitnami
        name: volume-sidekiq
  volumes:
    - name: volume-sidekiq
      persistentVolumeClaim:
        claimName: sidekiq
```
