### ISSUE TITLE
ERROR com.bitnami.discourse-sidekiq is not fully installed. You cannot execute commands

### ISSUE THREAD

**Issue by malcolmholmes** [bitnami/bitnami-docker-discourse#115]
**Description**

I have converted the `docker-compose.yml` file associated with this repo to Kubernetes. Redis, Postgres and Discourse start up fine. However, the `discourse-sidekiq` container is refusing to start, and not giving any hints as to what might be wrong.
 
**Steps to reproduce the issue:**

Start a statefulset using this YAML:

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    tanka/origin: environments.discourse.
  name: discourse-sidekiq
  namespace: discourse
spec:
  replicas: 1
  serviceName: discourse-sidekiq
  template:
    metadata:
      labels:
        name: discourse-sidekiq
    spec:
      containers:
      - command:
        - nami
        - start
        - --foreground
        - discourse-sidekiq
        env:
        - name: POSTGRESQL_HOST
          value: pgsql
        - name: POSTGRESQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: redis
        - name: DISCOURSE_POSTGRESQL_NAME
          value: bitnami_application
        - name: DISCOURSE_POSTGRESQL_USERNAME
          value: bn_discourse
        - name: DISCOURSE_POSTGRESQL_PASSWORD
          value: bitnami1
        - name: DISCOURSE_HOST
          value: discourse
        - name: DISCOURSE_PORT
          value: "3000"
        - name: DISCOURSE_HOSTNAME
          value: forum.example.com
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
          value: bitnami_application
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
          value: bn_discourse
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
          value: bitnami1
        - name: SMTP_HOST
          value: ******
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          value: **********************
        - name: SMTP_PASSWORD
          value: ***************************
        image: bitnami/discourse:2.3.5
        name: discourse-sidekiq
        volumeMounts:
        - mountPath: /bitnami
          name: discourse-sidekiq
          readOnly: false
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: discourse-sidekiq
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: storage
```
Review the logs.

**Describe the results you received:**

It returns `ERROR com.bitnami.discourse-sidekiq is not fully installed. You cannot execute commands`

and the pod goes into CrashLoopBackoff.

**Describe the results you expected:**

The pod to stay stable, and the Sidekiq to continue running.

**Version**

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.24", GitCommit:"2ce02ef1754a457ba464ab87dba9090d90cf0468", GitTreeState:"clean", BuildDate:"2019-08-12T22:05:28Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

This is running within GKE.
