### ISSUE TITLE
Support redis_skip_client_commands

### ISSUE THREAD

**Issue by cod-y** [bitnami/bitnami-docker-discourse#116]
I'd like to request support for the [DISCOURSE_REDIS_SKIP_CLIENT_COMMANDS](https://review.discourse.org/t/feature-add-setting-to-bypass-sending-redis-client-commands/966) option in Discourse. Setting this as an environment variable and setting the value to "true" should prevent any of the unnecessary `CLIENT` commands to be run in Redis. 

This is required for managed cloud services like GCP Memorystore. See [Memorystore blocked commands](https://cloud.google.com/memorystore/docs/reference/redis-configs#blocked) for more info.

Right now I have something like the following docker-compose.yml

```
version: '2'
services:
  discourse:
    image: 'bitnami/discourse:2'
    volumes:
      - 'discourse_data:/bitnami'
    environment:
      - DISCOURSE_HOSTNAME=www.example.com
      - DISCOURSE_PASSWORD=password
      - DISCOURSE_PORT_NUMBER=5000
      - POSTGRESQL_HOST=postgres-host
      - POSTGRESQL_ROOT_USER=username
      - POSTGRESQL_ROOT_PASSWORD=password
      - POSTGRESQL_NAME=discourse_db
      - DISCOURSE_POSTGRESQL_USERNAME=username
      - DISCOURSE_POSTGRESQL_PASSWORD=password
      - REDIS_HOST=redis-host
      - DISCOURSE_REDIS_SKIP_CLIENT_COMMANDS=true
volumes:
  discourse_data:
    driver: local
```

I'm getting this in the output: https://gist.github.com/cod-y/ebd299ab800715c23da05a72b3d349d5.

Support for this setting would be ideal, but I'd be fine with a simple patch of some sort to get this configuration to apply to Discourse.
