### ISSUE TITLE
How to add additional overrides to the configuration file

### ISSUE THREAD

**Issue by andresbono** [bitnami/bitnami-docker-discourse#125]
I'm just wondering how it would be possible to add additional overrides (for example for max_reqs_per_ip_per_10_seconds). I tried to mount just configuration file, but this doesn't work:

```
        volumes:
            - type: bind
              source: ./docker/discourse-config/discourse.conf
              target: /opt/bitnami/discourse/conf/discourse.conf
            - type: volume
              source: discourse_data
              target: /bitnami
```

_Originally posted by @girkantas in https://github.com/bitnami/bitnami-docker-discourse/issues/87#issuecomment-573557551_
