### ISSUE TITLE
Incomplete installation of math plugin 

### ISSUE THREAD

**Issue by akhmerov** [bitnami/bitnami-docker-discourse#130]
**Description**

After installing the official math plugin, mathjax math shows up correctly in post/topic previews, but not in the posts themselves

**Steps to reproduce the issue:**

1. Set up a docker-compose installation of discourse, with default configuration.
2. Log in into the discourse container, run the following commands:
    ```bash
    RAILS_ENV=production bundle exec rake plugin:install repo=https://github.com/discourse/discourse-math.git 
    RAILS_ENV=production bundle exec rake assets:precompile
    ```
3. enable math plugin in `/admin/plugins`
4. Prepare a post with `$x$` in the body.

**Describe the results you received:**

The math shows rendered with mathjax in the post preview, but not in the post itself.

**Additional information**

* I see no relevant errors in the javascript console.
* ~~here~~ is an example post in our installation, that demonstrates the problem.
* [here](https://meta.discourse.org/t/discourse-math-plugin/65770/162?u=anton_akhmerov) is the reply from the discourse team, suggesting that the problem is with the bitnami installation or CSP. The lack of errors in the console suggests that it is the former.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by javsalgar** [comment]
Hi,

Just a quick note to let you know that I was able to reproduce the issue. I will open a task for investigation. As this is not a critical feature, we cannot guarantee an ETA. As soon as I have updates I will update this ticket.

Thank you very  much for reporting.

**Comment by 0xyetix** [comment]
May I ask any updates from this issue? Is it resolved?

**Comment by javsalgar** [comment]
Hi,

I'm afraid it is still in our backlog. I will forward this to the team to see if we can re-prioritize this.

**Comment by 0xyetix** [comment]
Hi @javsalgar,

Can you guide me how to workaround or fix this? I'm happy to open a PR.

**Comment by javsalgar** [comment]
After executing the plugin  installation command and the rake:precompile command, does restarting the container help with the issue?

**Comment by aakhundov** [comment]
Unfortunately, restarting the container doesn't help. Would appreciate a workaround.

**Comment by javsalgar** [comment]
Are you using the same plugin? Do other plugins that you tried installing fail?

**Comment by aakhundov** [comment]
We are using the same plugin (https://github.com/discourse/discourse-math). Installing the plugin works (the plugin configuration appears in the settings). When writing a post with mathjax, math rendering works correctly in the preview. It is even displayed correctly in the post for a couple of seconds after hitting "Reply". Then, in the post, it turns back into non-rendered text ($...$) and stays so afterwards.

As for other plugins, we've installed [this](https://github.com/jonmbake/discourse-ldap-auth) LDAP auth plugin. It works as expected.

**Comment by javsalgar** [comment]
Hi,

This is strange, there is no reason for only this plugin to fail. Maybe there is another package that we may need to install or something similar. I will add this information to the task so the team can investigate.

**Comment by marcosbc** [comment]
Hi, FYI we just released a new container version, [2.7.0-debian-10-r4](https://github.com/bitnami/bitnami-docker-discourse#270-debian-10-r4). The initialization logic has received a major refactor, and its scripts are now located in the [`rootfs/` directory](https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/).

As we have made a major refactor of the installation scripts, it is possible that this issue as been solved, so if you could confirm that it would be great.

**Comment by aakhundov** [comment]
Hi @marcosbc. I can confirm that the math plugin (v0.9) works as expected now: equations are rendered correctly both in preview, and after the message is posted. Thanks a lot for the fix!

Tested with the [helm chart](https://github.com/bitnami/charts/tree/master/bitnami/discourse/) v4.0.0.

**Comment by aakhundov** [comment]
However, another problem seems to arise with the new image / helm chart (v4.0.0).

Right after installing the helm chart (before installing any plugins or changing any configuration), emojis are not rendered properly in the newly written posts. The emojis are rendered correctly in the predefined posts, like the one by `system` in the `Welcome to the Lounge` topic.

An inspection has revealed a superfluous `//127.0.0.1` prefix in the emoji URLs (e.g., `src="//127.0.0.1/images/emoji/twitter/+1.png?v=9"`). Removing the `//127.0.0.1` prefix from the `src` (i.e., making it `src="/images/emoji/twitter/+1.png?v=9"` instead) fixes the rendering issue.

Any idea on what this may be caused by? `DISCOURSE_HOST` environment variable is set correctly in the container. Applying the accepted solution from [here](https://community.bitnami.com/t/emoji-url-set-to-127-0-0-1/69879) (changing the category of the `READ ME FIRST: Admin Quick Start Guide` topic) does not help.

**Comment by marcosbc** [comment]
Hi @aakhundov, thanks for reporting this. We have been able to reproduce this issue and are working on merging a fix and launching a new release. Stay tuned to new `bitnami/discourse` chart releases.

**Comment by aakhundov** [comment]
@marcosbc, you mean the chart releases indicated [here](https://bitnami.com/stack/discourse/helm), don't you? If so, any guess on when the fixed version of the chart is going to be released? Thanks!

**Comment by marcosbc** [comment]
Due to some internal issues in our release pipeline, the release is getting delayed. We will try to have it fixed before end of week, but unfortunately I cannot guarantee that.

**Comment by KagurazakaNyaa** [comment]
I use docker-compose to deploy and use the 2.7.4 version of the image, and this bug can still be reproduced.

```yaml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - './postgresql_data:/bitnami/postgresql'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_DATABASE=bitnami_discourse

  redis:
    image: docker.io/bitnami/redis:6.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './redis_data:/bitnami/discourse'
      - '/etc/localtime:/etc/localtime:ro'

  discourse:
    image: docker.io/bitnami/discourse:2
    ports:
      - '4567:3000'
    volumes:
      - './discourse_data:/bitnami/discourse'
      - '/opt/backup/discourse:/bitnami/discourse/public/backups'
      - '/etc/localtime:/etc/localtime:ro'
    depends_on:
      - postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=[redacted]
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
      - DISCOURSE_EMAIL=[redacted]
      - DISCOURSE_SMTP_HOST=[redacted]
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=[redacted]
      - DISCOURSE_SMTP_PASSWORD=[redacted]
      - DISCOURSE_SMTP_PROTOCOL=tls

  sidekiq:
    image: docker.io/bitnami/discourse:2
    depends_on:
      - discourse
    volumes:
      - './sidekiq_data:/bitnami/discourse'
      - '/etc/localtime:/etc/localtime:ro'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=[redacted]
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - DISCOURSE_EMAIL=[redacted]
      - DISCOURSE_SMTP_HOST=[redacted]
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=[redacted]
      - DISCOURSE_SMTP_PASSWORD=[redacted]
      - DISCOURSE_SMTP_PROTOCOL=tls
```
