### ISSUE TITLE
Startup of the container fails randomly

### ISSUE THREAD

**Issue by vranki** [bitnami/bitnami-docker-discourse#131]
**Description**

I'm trying to run this container, but startup sometimes succeeds and sometimes
fails for various reasons.

**Steps to reproduce the issue:**

1. docker-compose up

**Describe the results you received:**

Sometimes:
```
discourse_1   | postgre INFO  Found PostgreSQL server listening at postgresql:5432
discourse_1   | postgre INFO  PostgreSQL server listening and working at postgresql:5432
discourse_1   | discour INFO  Preparing Discourse environment...
discourse_1   | discour INFO  Configuring the Discourse database files...
discourse_1   | Error executing 'postInstallation': Files to substitute resolved to an empty list
discourse_discourse_1 exited with code 1
sidekiq_1     | Error executing 'postInstallation': Failed to connect to discourse:3000 after 90 tries
```
This is possibly related to #90 

Sometimes with no changes to docker-dompose.yml or any other files:
```
sidekiq_1     | postgre INFO  PostgreSQL server listening and working at postgresql:5432
sidekiq_1     | discour INFO  Configuring the Discourse database files...
sidekiq_1     | discour INFO  Configuring Redis...
sidekiq_1     | discour INFO  Setting up SMTP in Sidekiq...
sidekiq_1     | discour INFO  Waiting for Discourse service to be ready...
```
Discourse never gets ready. 

**Describe the results you expected:**

Discourse would start always.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is quite tricky issue. I've managed to start this discourse before sometimes, but now after about 10 retries it always fails. Perhaps the volume data is somehow messed up. I'll destroy the volumes and try to start the container from scratch.

docker_compose.yml:
```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - tiy
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
    networks:
      - tiy
  discourse:
    image: 'bitnami/discourse:2'
    ports:
      - '3000:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=xxxxx.xxxx.fi
      - VIRTUAL_HOST=xxxx.xxxx.fi
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=xxxxx.xxxx.xx
      - LETSENCRYPT_EMAIL=xxx.xxx@iki.xx
      - SMTP_HOST=smtp.xxxx.fi
      - SMTP_PORT=25
      - SMTP_AUTH=none
      - SMTP_TLS=no
    networks:
      - tiy
  sidekiq:
    image: 'bitnami/discourse:2'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    networks:
      - tiy
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=xxxxx.xxx.xx
      - SMTP_HOST=smtp.xxxx.fi
      - SMTP_PORT=25
      - SMTP_AUTH=none
      - SMTP_TLS=no
networks:
  tiy:
    external: true
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
networks:
  tiy:
    external: true
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:58 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:32 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 5
  Paused: 0
  Stopped: 4
 Images: 28
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-6-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.854GiB
 Name: intra
 ID: GHU2:EHBR:RKPR:I2W3:ZSXN:LLHK:LBJK:FRPR:HUG5:W7UK:DK5Z:T2XX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.0, build unknown
docker-py version: 3.4.1
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

OS: Debian Buster
