### ISSUE TITLE
ERROR ELOOP: too many symbolic links encountered, lstat /opt/bitnami/discourse-sidekiq/logs/sidekiq.log

### ISSUE THREAD

**Issue by deeztek** [bitnami/bitnami-docker-discourse#134]
Discourse is resporting the following error:

> Sidekiq is not running. Many tasks, like sending emails, are executed asynchronously by sidekiq. Please ensure at least one sidekiq process is running. Learn about Sidekiq here.

Sidekiq trace if reporting the following:

```
Starting discourse-sidekiq...


nami    ERROR ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/discourse-sidekiq/logs/sidekiq.log'


nami    TRACE Error: ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/discourse-sidekiq/logs/sidekiq.log'


    at Object.fs.lstatSync (fs.js:941:11)


    at Object.lstatSync (/opt/bitnami/nami/node_modules/graceful-fs/polyfills.js:297:22)


    at exists (/opt/bitnami/nami/node_modules/nami-utils/lib/file/exists.js:17:8)


    at size (/opt/bitnami/nami/node_modules/nami-utils/lib/file/size.js:19:8)


    at FileReader.seek (/opt/bitnami/nami/node_modules/nami-utils/lib/file/FileReader.js:35:23)


    at new FileReader (/opt/bitnami/nami/node_modules/nami-utils/lib/file/FileReader.js:14:12)


    at Service._execServiceCommand (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:70:25)


    at Service._start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:348:12)


    at Service.start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:376:30)


    at Service.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
```

**Comment by javsalgar** [comment]
Hi,

Could you provide more information about the container platform you are using? I recall seeing this issue in the past.

**Comment by deeztek** [comment]
Ubuntu 18.04
Docker version 19.03.7, build 7141c199a2
docker-compose version 1.25.4, build 8d51620a

**Comment by javsalgar** [comment]
Thanks for the information. Are you using the default docker-compose or you are using a custom one. Could you delete the volumes with `docker-compose down -v` and try again?

**Comment by deeztek** [comment]
I'm using a custom one. I've brought down the stack and deleted the volumes multiple times with no success. Here's the docker-compose I'm using:

```
version: '2'

networks:
  proxy:
    external: true

services:
  discourse_postgresql:
    image: 'bitnami/postgresql:11'

    container_name: discourse_postgresql

    restart: unless-stopped

    networks:
      - proxy

    environment:
      - TZ=America/New_York
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_PASSWORD=postgessql_password

    volumes:
      - '/mnt/data/discourse/postgresql_data:/bitnami/postgresql'

  discourse_redis:
    image: 'bitnami/redis:5.0'

    container_name: discourse_redis

    restart: unless-stopped

    networks:
      - proxy

    environment:
      - TZ=America/New_York
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=redis_password

    volumes:
      - 'redis_data:/bitnami'

  discourse:

    image: 'bitnami/discourse:2'

    container_name: discourse
    #ports:
    #  - '80:3000'

    restart: unless-stopped

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.discourse.entrypoints=http"
      - "traefik.http.routers.discourse.rule=Host(`community.domain.tld`)"
      - "traefik.http.middlewares.discourse-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.discourse.middlewares=discourse-https-redirect"
      - "traefik.http.routers.discourse-secure.entrypoints=https"
      - "traefik.http.routers.discourse-secure.rule=Host(`community.domain.tld`)"
      - "traefik.http.routers.discourse-secure.tls=true"
      #- "traefik.http.routers.discourse-secure.tls.certresolver=le"
      - "traefik.http.routers.discourse-secure.service=discourse"
      - "traefik.http.services.discourse.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

    depends_on:
      - discourse_postgresql
      - discourse_redis

    volumes:
      - 'discourse_data:/bitnami'

    environment:
      - TZ=America/New_York
      - POSTGRESQL_HOST=discourse_postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_ROOT_PASSWORD=postgessql_password
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=postgresql_client_create_database_password
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=postgresql_client_create_database_password
      - DISCOURSE_HOSTNAME=community.domain.tld
      - DISCOURSE_USERNAME=discourse_username
      - DISCOURSE_PASSWORD=discourse_password
      - DISCOURSE_EMAIL=smtp_user
      - DISCOURSE_SITENAME=My Community
      - SMTP_HOST=smtp_host
      - SMTP_PORT=587
      - SMTP_USER=smtp_user
      - SMTP_PASSWORD=smtp_password
      - REDIS_HOST=discourse_redis
      - REDIS_PASSWORD=redis_password

  discourse_sidekiq:

    image: 'bitnami/discourse:2'

    container_name: discourse_sidekiq

    environment:
      - TZ=America/New_York
      - NAMI_LOG_LEVEL=trace
      - REDIS_PASSWORD=redis_password
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=postgresql_client_create_database_password
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=community.domain.tld
      - DISCOURSE_USERNAME=discourse_username
      - DISCOURSE_EMAIL=smtp_user
      - DISCOURSE_PASSWORD=discourse_password
      - SMTP_HOST=smtp_host
      - SMTP_PORT=587
      - SMTP_USER=smtp_user
      - SMTP_PASSWORD=smtp_password

    depends_on:
      - discourse

    restart: unless-stopped

    networks:
      - proxy

    volumes:
      - 'sidekiq_data:/bitnami'

    command: 'nami start --foreground discourse-sidekiq'

    environment:
      - NAMI_LOG_LEVEL=trace
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=postgresql_client_create_database_password
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=community.domain.tld

volumes:
  postgresql_data:
    driver: local
  redis_data:
      driver_opts:
        type: nfs
        o: addr=nfs_host,nolock,soft,rw
        device: :/mnt/pool1/docker/discourse/redis_data

  discourse_data:
      driver_opts:
        type: nfs
        o: addr=nfs_host,nolock,soft,rw
        device: :/mnt/pool1/docker/discourse/discourse_data

  sidekiq_data:
      driver_opts:
        type: nfs
        o: addr=nfs_host,nolock,soft,rw
        device: :/mnt/pool1/docker/discourse/sidekiq_data



```

**Comment by javsalgar** [comment]
Hi,

I see that you are using custom volumes. Could you check that the mounts you are using are actually clean and don't contain data from the previous installations?

**Comment by deeztek** [comment]
I deleted all the containers, deleted the volumes, cleaned out all the data from the volumes and re-created the containers with the same results. I did however notice the following in the postgresql logs:

```
postgresql 06:52:00.31 INFO  ==> ** Starting PostgreSQL **


2020-03-11 10:52:00.360 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432


2020-03-11 10:52:00.360 GMT [1] LOG:  listening on IPv6 address "::", port 5432


2020-03-11 10:52:00.522 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"


2020-03-11 10:52:00.541 GMT [195] LOG:  database system was shut down at 2020-03-11 10:51:59 GMT


2020-03-11 10:52:00.551 GMT [1] LOG:  database system is ready to accept connections


2020-03-11 10:52:04.301 GMT [202] LOG:  incomplete startup packet


2020-03-11 10:52:04.304 GMT [203] LOG:  incomplete startup packet


2020-03-11 10:52:04.436 GMT [205] FATAL:  password authentication failed for user "bn_discourse"


2020-03-11 10:52:04.436 GMT [205] DETAIL:  Role "bn_discourse" does not exist.


	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"


2020-03-11 10:52:11.419 GMT [213] LOG:  incomplete startup packet

```

Not sure if it's related to the issue I'm having, but discourse does seem to come up fine and I'm able to login to it.

**Comment by javsalgar** [comment]
Hi,

Another idea that comes to mind. Could you try moving the database creation environment variables from discourse to postgresql itself?

Check this information
https://github.com/bitnami/bitnami-docker-postgresql#creating-a-database-on-first-run

**Comment by deeztek** [comment]
Hi,

I followed your advice, unfortunately, I have the same issue:

```
services:
  discourse_postgresql:
    image: 'bitnami/postgresql:11'

    container_name: discourse_postgresql

    restart: unless-stopped

    networks:
      - proxy

    environment:
      - TZ=America/New_York
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_POSTGRES_PASSWORD=postgresql_postgres_password
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_PASSWORD=postgresql_password
      - POSTGRESQL_DATABASE=bitnami_application

 volumes:
      - '/mnt/data/discourse/postgresql_data:/bitnami/postgresql'

```

**Comment by javsalgar** [comment]
Hi,

Just to confirm that the issue is with the volumes, could you try using docker default regular volumes instead of host paths or volumes with other drivers? With that we would confirm that the issue is there.

**Comment by javsalgar** [comment]
ping

**Comment by deeztek** [comment]
Sorry I got busy with other stuff and I forgot to post feedback. I followed your advise and used regular volumes with local drivers and the issue remains.

**Comment by javsalgar** [comment]
Hi,

This is weird, I am unable to reproduce the issue with this docker-compose file

```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse:2'
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=www.example.com
  sidekiq:
    image: 'bitnami/discourse:2'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=www.example.com
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

It starts without issues

**Comment by deeztek** [comment]
I took another crack at it using your compose file as a template and went from there. I finally got it working with Traefik. Part of the problem I was running into was the host port 80 was interfering with Traefik which also needs to use port 80. So I ended up simply exposing container port 3000, setup a two separate networks for discourse and traefik and it worked. Here's my docker-compose.yml just in case someone finds it of use. Also another weird issue I ran into was Discourse was interfering with my Bitnami Nextcloud container and its SMB shares. I haven't looked into it too much but best I could tell was the Redis container which both Discourse and Nextcloud utilize. I ended up putting Nextcloud conainers on their own network and that seemed to solve the problem:

```
version: '2'

networks:
  proxy:
    external: true

  discourse:
    internal: true

services:
  postgresql:
    image: 'bitnami/postgresql:11'
    container_name: 'discourse_postgres'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - discourse
    restart: unless-stopped
    labels: 
    # Watchtower
      #- "com.centurylinklabs.watchtower.enable=true"
 
  redis:
    image: 'bitnami/redis:5.0'
    container_name: 'discourse_redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
    networks:
      - discourse
    restart: unless-stopped
    labels:
    # Watchtower
      #- "com.centurylinklabs.watchtower.enable=true"


  discourse:
    image: 'bitnami/discourse:latest'
    container_name: 'discourse'
    ports:
      - '3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami'
    networks:
      - proxy
      - discourse

    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
    
      # Routers
      - "traefik.http.routers.discourse.entrypoints=http"
      - "traefik.http.routers.discourse.rule=Host(`community.domain.tld`)"
      - "traefik.http.routers.discourse.middlewares=discourse-https-redirect"
    
      - "traefik.http.routers.discourse-secure.entrypoints=https"
      - "traefik.http.routers.discourse-secure.rule=Host(`community.domain.tld`)"
      - "traefik.http.routers.discourse-secure.tls=true"
      #- "traefik.http.routers.discourse-secure.tls.certresolver=le"
      - "traefik.http.routers.discourse-secure.service=discourse"
      #- "traefik.http.routers.discourse-secure.middlewares=add-discourse"
    
      # Service definition
      - "traefik.http.services.discourse.loadbalancer.server.port=3000"
    
      # Middleware definitions
      - "traefik.http.middlewares.discourse-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.add-discourse.addPrefix.prefix=/interface"
      # Watchtower
      #- "com.centurylinklabs.watchtower.enable=true"
    

    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bn_discourse_password
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bn_discourse_password
      - DISCOURSE_HOSTNAME=community.domain.tld
      - DISCOURSE_USERNAME=discourse_app_admin_username
      - DISCOURSE_PASSWORD=discourse_app_admin_password
      - DISCOURSE_EMAIL=someone@domain.tld
      - DISCOURSE_SITENAME=My Awesome Community
      - SMTP_HOST=smtp.domain.tld
      - SMTP_PORT=587
      - SMTP_USER=smtp_username
      - SMTP_PASSWORD=smtp_password
      - REDIS_HOST=discourse_redis
  sidekiq:
    image: 'bitnami/discourse:latest'
    container_name: 'discourse_sidekiq'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    networks:
      - discourse
    restart: unless-stopped
    labels:
    # Watchtower
      #- "com.centurylinklabs.watchtower.enable=true"


    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bn_discourse_password
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=community.domain.tld

volumes:
  postgresql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/discourse/postgresql_data

  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/discourse/postgresql_data

  discourse_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/discourse/discourse_data

  sidekiq_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/discourse/sidekiq_data
```
