### ISSUE TITLE
Feature Request: configure more values of discourse.conf

### ISSUE THREAD

**Issue by sbetzin** [bitnami/bitnami-docker-discourse#137]
Hi you guys, thanks for providing this easy to install image of discourse.
After some time (when facing slow page reloads in the forum) I wanted to set some discourse.conf parameters:

#load MiniProfiler in production, to be used by developers
`load_mini_profiler = true`
#comma delimited list of emails that have developer level access
`developer_emails = `

But it seems that it is not supported by the environment vars in the docker compose files. After digging into the docker container I have seen that the config resides in /opt/bitnami/discourse/conf/discourse.conf

I then tried to provide the config with using this in my docker compose file:
`/home/gg/Solawi-IT/docker/discourse/discourse-develop.conf:/opt/bitnami/discourse/conf/discourse.conf`

but unfortunatly this clears the whole conf folder and maps just this one file....

So my question is: how to set more config params?

Thank you in advance

**Comment by andresbono** [comment]
Hi @sbetzin, we are not able to reproduce the issue that you are describing. Can you give us more details about the steps that you followed to mount the configuration file? Did you start from a clean deployment?

**Comment by sbetzin** [comment]
@andresbono Hi Andres, como estas?
Thank you for the answer. Are you referring to the discourse.conf file mapping?

**Comment by andresbono** [comment]
Exactly, I'm referring to:

> but unfortunatly this clears the whole conf folder and maps just this one file....

**Comment by sbetzin** [comment]
Ok. I setup a clean test environment for this. My docker compose looks like this (without sql, redis and sidekiq):

 ```
 discourse-develop:
    image: bitnami/discourse:2
    container_name: discourse-develop
    hostname: discourse-develop
    ports:
      - "8080:3000"
    depends_on:
      - discourse-postgresql
      - discourse-redis
    volumes:
      - discourse-develop:/bitnami:z
    environment:
      - DISCOURSE_USERNAME=superuser
      - DISCOURSE_PASSWORD=****
      - DISCOURSE_EMAIL=****
      - DISCOURSE_HOSTNAME=****:8080
      - REDIS_HOST=discourse-redis-develop
      - POSTGRESQL_HOST=discourse-postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_ROOT_PASSWORD=***
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=discourse_develop
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=***
      - DISCOURSE_POSTGRESQL_NAME=discourse_develop
      - DISCOURSE_POSTGRESQL_USERNAME=discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=****
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=587
      - SMTP_USER=apikey
      - SMTP_PASSWORD=***

```
If I am using this setup everything works fine:

```
docker logs discourse-develop -f

Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing postgresql-client
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at discourse-postgresql:5432
postgre INFO  PostgreSQL server listening and working at discourse-postgresql:5432
postgre INFO  ==> Creating database discourse_develop...
postgre INFO  ==> Granting access to discourse to the database discourse_develop...
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at discourse-postgresql:5432
postgre INFO  PostgreSQL server listening and working at discourse-postgresql:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Configuring Discourse database...
discour INFO  Enabling PostgreSQL plugins for Discourse...
discour INFO  Migrating database...
discour INFO  Creating the Discourse admin user...
discour INFO  Configuring your Discourse installation...

```
and connecting to the running container gives this result:
```
docker exec -it  discourse-develop bash
root@discourse-develop:/# ls /opt/bitnami/discourse/conf
application.rb  cloud             discourse.conf           discourse_defaults.conf  initializers    multisite.yml.production-sample  projections.json  sidekiq.yml        thin.yml.sample   unicorn_upstart.conf
boot.rb         database.yml      discourse.config.sample  environment.rb           locales         nginx.global.conf                puma.rb           site_settings.yml  unicorn.conf.rb
cdn.yml.sample  deploy.rb.sample  discourse.pill.sample    environments             logrotate.conf  nginx.sample.conf                routes.rb         spring.rb          unicorn_launcher
```

then I add this line to my docker-compose.yml
`- /home/gg/Solawi-IT/docker/discourse/discourse-develop.conf:/opt/bitnami/discourse/conf/discourse.conf`

restarting with
`docker-compose -f /home/gg/Solawi-IT/docker/docker-compose.yml up -d  `
gives the result

```
docker logs discourse-develop -f

Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing postgresql-client
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at discourse-postgresql:5432
postgre INFO  PostgreSQL server listening and working at discourse-postgresql:5432
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at discourse-postgresql:5432
postgre INFO  PostgreSQL server listening and working at discourse-postgresql:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
Error executing 'postInstallation': Files to substitute resolved to an empty list

```
because the container terminates instantly after that I am trying to spin up a container with

```
docker run --rm -it --name console -v /home/gg/Solawi-IT/docker/discourse/discourse-develop.conf:/opt/bitnami/discourse/conf/discourse.conf:z --entrypoint /bin/bash bitnami/discourse:2
root@73adc4c69699:/# ls /opt/bitnami/discourse/conf
discourse.conf
```
