### ISSUE TITLE
Export User List not working

### ISSUE THREAD

**Issue by sbetzin** [bitnami/bitnami-docker-discourse#142]
I cannot export the user list in the admin section.

1. Starting the user list export seems to work fine. Shortly after pressing the export button I am getting an incoming notification that the user export is sucessful:
![image](https://user-images.githubusercontent.com/1607849/81607175-8c097000-93d4-11ea-8bfb-06a9e8eb83b6.png)

2. Getting a notification
![image](https://user-images.githubusercontent.com/1607849/81607283-b9eeb480-93d4-11ea-9511-09952a091330.png)

3. Opening message
![image](https://user-images.githubusercontent.com/1607849/81607316-c70ba380-93d4-11ea-8a6d-cb8f3e09a4de.png)

4. clicking on the link. 
![image](https://user-images.githubusercontent.com/1607849/81607376-dee32780-93d4-11ea-94f9-675066c6e762.png)

the url generated is:
http://[hostname]/uploads/short-url/77EDZbRgGeOHYGTmIpACAzoSuiN.zip

Environment: I tried this with a fresh installed test system 

the relevant part of docker-compose:

```
discourse-develop:
    image: bitnami/discourse:2
    container_name: discourse-develop
    hostname: discourse-develop
    depends_on:
      - discourse-postgresql
      - discourse-redis
    volumes:
      - discourse-develop:/bitnami:z
    environment:
      - DISCOURSE_USERNAME=superuser
      - DISCOURSE_PASSWORD=****
      - DISCOURSE_EMAIL=sebastian@betzin.com
      - DISCOURSE_HOSTNAME=****
      - DISCOURSE_SITENAME= *****
      - DISCOURSE_PORT_NUMBER=3000
      - REDIS_HOST=discourse-redis-develop
      - POSTGRESQL_HOST=discourse-postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_ROOT_PASSWORD=****
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=discourse_develop
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=****
      - DISCOURSE_POSTGRESQL_NAME=discourse_develop
      - DISCOURSE_POSTGRESQL_USERNAME=discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=****
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=587
      - SMTP_USER=apikey
      - SMTP_PASSWORD=****
```

docker version
```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

docker info

```
 Debug Mode: false

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-1036-azure
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.767GiB
 Name: gutes-gemuese
 ID: A2LW:NCZ7:5XQL:P7TL:PQOL:FE2T:66E4:CZDB:RU4Q:NAHK:E6CY:A4O3
 Docker Root Dir: /datadrive/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

I can see the export happening in the docker logs -f for the discourse container

```
Started GET "/admin/users/list/active.json?filter=&show_emails=false&page=1" for 109.193.249.239 at 2020-05-11 20:36:58 +0000
Processing by Admin::UsersController#index as JSON
  Parameters: {"filter"=>"", "show_emails"=>"false", "page"=>"1", "query"=>"active"}
Completed 200 OK in 80ms (Views: 0.2ms | ActiveRecord: 0.0ms | Allocations: 27333)
Started POST "/export_csv/export_entity.json" for 109.193.249.239 at 2020-05-11 20:36:59 +0000
Processing by ExportCsvController#export_entity as JSON
  Parameters: {"entity"=>"user_list", "args"=>{"trust_level"=>"active"}}
Completed 200 OK in 124ms (Views: 13.3ms | ActiveRecord: 0.0ms | Allocations: 13818)
Creating scope :open. Overwriting existing method Poll.open.
Started GET "/notifications?recent=true&limit=16" for 109.193.249.239 at 2020-05-11 20:37:54 +0000
Processing by NotificationsController#index as JSON
  Parameters: {"recent"=>"true", "limit"=>"16"}
Completed 200 OK in 53ms (Views: 0.2ms | ActiveRecord: 0.0ms | Allocations: 13697)
Started GET "/t/12.json?track_visit=true&forceLoad=true" for 109.193.249.239 at 2020-05-11 20:37:55 +0000
Processing by TopicsController#show as JSON
  Parameters: {"track_visit"=>"true", "forceLoad"=>"true", "id"=>"12"}
Completed 200 OK in 159ms (Views: 0.1ms | ActiveRecord: 0.0ms | Allocations: 39927)
Started GET "/uploads/short-url/aUVPeyqgk8eiOTdWU0mRhTCp7Hp.zip" for 109.193.249.239 at 2020-05-11 20:37:57 +0000
Processing by UploadsController#show_short as ZIP
  Parameters: {"base62"=>"aUVPeyqgk8eiOTdWU0mRhTCp7Hp", "extension"=>"zip"}
  Rendering text template
  Rendered text template (Duration: 0.0ms | Allocations: 1)
Sent file /opt/bitnami/discourse/public/uploads/default/original/1X/4c854630a316c74358c18631cca97e8ad713f517.zip (0.2ms)
Completed 500 Internal Server Error in 99ms (ActiveRecord: 0.0ms | Allocations: 38689)
ActionController::MissingFile (Cannot read file /opt/bitnami/discourse/public/uploads/default/original/1X/4c854630a316c74358c18631cca97e8ad713f517.zip)
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_controller/metal/data_streaming.rb:70:in `send_file'

```

I tried to look up the file in the volume but it seems that it is not there

a folder /original/ is not existing

```
ls /datadrive/docker/volumes/discourse-develop/_data/discourse/public/uploads/default/
optimized
```

I then looked into the optimized but the file is not found

```
ls /datadrive/docker/volumes/discourse-develop/_data/discourse/public/uploads/default/**optimized**/1X/
_129430568242d1b7f853bb13ebea28b3f6af4e7_2_180x180.png  _129430568242d1b7f853bb13ebea28b3f6af4e7_2_32x32.png  _129430568242d1b7f853bb13ebea28b3f6af4e7_2_512x512.png
```

**Comment by rafariossaa** [comment]
Hi,
  I am trying to reproduce the issue.
  I will share my findings soon.

**Comment by rafariossaa** [comment]
Hi,
  I was able to reproduce the issue, I am trying to find a fix or a workaround.

**Comment by rafariossaa** [comment]
Hi @sbetzin ,
  The issue seems to be that the discourse and the sidekiq container need to share the volumen.
  We are implementing a solution for this, but meanwhile could you try the following steps ?
- Create a data directory:
```
$ mkdir -p data/discourse
$ ln -s data/discourse data/discourse-sidekiq
```
- Use the following `docker-compose.yml`, as you can notice I am using the `data` directory as volume for both containers:
```
$ cat docker-compose.yml 
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse:2'
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - './data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=www.example.com
  sidekiq:
    image: 'bitnami/discourse:2'
    depends_on:
      - discourse
    volumes:
      - './data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=www.example.com
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
```

**Comment by sbetzin** [comment]
Hi @rafariossaa,

thank you for the response. If I understand you corrently: both containers create different pathes inside the volume. So sidekiq creates the file, but discourse container cannot access it....


```
discourse:
    image: bitnami/discourse:2
    container_name: discourse
    hostname: discourse
    depends_on:
      - discourse-postgresql
      - discourse-redis
    volumes:
      - discourse:/bitnami:z
...

discourse-sidekiq:
    image: bitnami/discourse:2
    container_name: discourse-sidekiq
    hostname: discourse-sidekiq
    depends_on:
      - discourse
    volumes:
      - discourse:/bitnami:z

...

volumes:
  discourse:
    external:
      name: discourse
```

=> in the volume

```
 ls
conf  data  discourse  discourse-sidekiq  redis

```

I am trying your solution with the hardlink...
