### ISSUE TITLE
Using the docker compose results in a blank page

### ISSUE THREAD

**Issue by jerrythomas** [bitnami/bitnami-docker-discourse#143]
**Description**

Using the docker compose results in a blank page on HTTP://localhost

**Steps to reproduce the issue:**

1. curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-discourse/master/docker-compose.yml > docker-compose.yml
2. docker-compose up -d
3. docker ps
```text
3b9f0d3b34cc        bitnami/discourse:2-debian-10     "/app-entrypoint.sh …"   19 minutes ago      Up 19 minutes       3000/tcp                            discourse_sidekiq_1
4adb67e238c7        bitnami/discourse:2-debian-10     "/app-entrypoint.sh …"   19 minutes ago      Up 19 minutes       0.0.0.0:80->3000/tcp                discourse_discourse_1
a6f7c91d463e        bitnami/postgresql:11-debian-10   "/opt/bitnami/script…"   19 minutes ago      Up 19 minutes       5432/tcp                            discourse_postgresql_1
cbcbdef0e04f        bitnami/redis:5.0-debian-10       "/opt/bitnami/script…"   19 minutes ago      Up 19 minutes       6379/tcp                            discourse_redis_1
```

**Describe the results you received:**
Navigate to HTTP://localhost

Result is a blank page. with a title "My site!"

**Describe the results you expected:**

Atleast a startup page that allows me to navigate through and try out some of the functionality of discourse.

**Additional information you deem important (e.g. issue happens only occasionally):**
Few lines from the bottom of 
```
docker-compose logs compose
```
```
discourse_1   | [ E 2020-05-20 04:22:06.5195 534/T16 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/bitnami/discourse: A timeout occurred while spawning an application process.
discourse_1   |   Error ID: cc4cdfaa
discourse_1   |   Error details saved to: /tmp/passenger-error-emCo8C.html
discourse_1   | 
discourse_1   | [ N 2020-05-20 04:25:35.9244 534/T4 age/Cor/CoreMain.cpp:1147 ]: Checking whether to disconnect long-running connections for process 1173, application /opt/bitnami/discourse (production)
discourse_1   | [ N 2020-05-20 04:25:37.0848 534/T4 age/Cor/CoreMain.cpp:1147 ]: Checking whether to disconnect long-running connections for process 582, application /opt/bitnami/discourse (production)
```

**Version**

- Output of `docker version`:
```text
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 Kubernetes:
  Version:          v1.16.6-beta.0
  StackAPI:         v1beta2
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 33
  Running: 23
  Paused: 0
  Stopped: 10
 Images: 131
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: COGP:7GCO:EHYO:7MSK:ANH5:FUFL:XBJC:NW3W:FEHJ:BEKG:FBWU:R6GM
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 195
  Goroutines: 172
  System Time: 2020-05-20T04:26:03.1362535Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @jerrythomas 

I couldn't reproduce the error locally (using also Docker for MAC) as you can see in the logs below. It looks like an "timeout" issue. Could you try again?

```console
discourse_1   |
discourse_1   | Welcome to the Bitnami discourse container
discourse_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
discourse_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
discourse_1   |
discourse_1   | nami    INFO  Initializing postgresql-client
discourse_1   | postgre INFO  Trying to connect to PostgreSQL server
discourse_1   | postgre INFO  Found PostgreSQL server listening at postgresql:5432
discourse_1   | postgre INFO  PostgreSQL server listening and working at postgresql:5432
discourse_1   | postgre ERROR [canConnect] Connection with 'bn_discourse' user is unsuccessful
discourse_1   | postgre INFO  ==> Creating database bitnami_application...
discourse_1   | postgre INFO  ==> Granting access to bn_discourse to the database bitnami_application...
discourse_1   | nami    INFO  postgresql-client successfully initialized
discourse_1   | nami    INFO  Initializing discourse
discourse_1   | discour INFO  Patching Discourse...
discourse_1   | postgre INFO  Trying to connect to PostgreSQL server
discourse_1   | postgre INFO  Found PostgreSQL server listening at postgresql:5432
discourse_1   | postgre INFO  PostgreSQL server listening and working at postgresql:5432
discourse_1   | discour INFO  Preparing Discourse environment...
discourse_1   | discour INFO  Configuring the Discourse database files...
discourse_1   | discour INFO  Configuring Redis...
discourse_1   | discour INFO  Setting up SMTP in Discourse...
discourse_1   | discour INFO  Configuring Discourse database...
discourse_1   | discour INFO  Enabling PostgreSQL plugins for Discourse...
discourse_1   | discour INFO  Migrating database...
discourse_1   | discour INFO  Creating the Discourse admin user...
discourse_1   | discour INFO  Configuring your Discourse installation...
discourse_1   | discour INFO
discourse_1   | discour INFO  ########################################################################
discourse_1   | discour INFO   Installation parameters for discourse:
discourse_1   | discour INFO     Username: user
discourse_1   | discour INFO     Password: **********
discourse_1   | discour INFO   (Passwords are not shown for security reasons)
discourse_1   | discour INFO  ########################################################################
discourse_1   | discour INFO
discourse_1   | nami    INFO  discourse successfully initialized
discourse_1   | Starting discourse...
discourse_1   | Migrating to DropUnusedColumns (20200120131338)
discourse_1   | Migrating to RemoveBounceScoreThresholdDeactivateSiteSetting (20200130115859)
discourse_1   | Migrating to MarkBookmarksTopicIdNotNull (20200203061927)
discourse_1   | Creating scope :open. Overwriting existing method Poll.open.
discourse_1   | Creating scope :open. Overwriting existing method Poll.open.
discourse_1   | [ N 2020-05-20 06:50:50.5448 513/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
discourse_1   | [ N 2020-05-20 06:50:50.5707 516/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
discourse_1   | [ N 2020-05-20 06:50:50.5708 516/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
discourse_1   | [ N 2020-05-20 06:50:50.5831 516/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 516
discourse_1   | [ N 2020-05-20 06:50:53.0093 516/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
discourse_1   | Creating scope :open. Overwriting existing method Poll.open.
discourse_1   | Started HEAD "/" for 127.0.0.1 at 2020-05-20 06:51:05 +0000
discourse_1   | Processing by ListController#latest as HTML
discourse_1   |   Rendering list/list.erb within layouts/application
discourse_1   |   Rendered list/list.erb within layouts/application (Duration: 63.9ms | Allocations: 22933)
discourse_1   |   Rendered layouts/_head.html.erb (Duration: 185.4ms | Allocations: 24930)
discourse_1   |   Rendered common/_discourse_stylesheet.html.erb (Duration: 274.5ms | Allocations: 17529)
discourse_1   |   Rendered application/_header.html.erb (Duration: 40.0ms | Allocations: 5396)
discourse_1   | Completed 200 OK in 1349ms (Views: 1052.7ms | ActiveRecord: 0.0ms | Allocations: 230166)
```

Please note that you need to access Discourse using the hostname you set in the environment variable `DISCOURSE_HOSTNAME`. For instance, set it to `discourse.foo.bar` and access it through http://discourse.foo.bar, you can do it by adding the line below in your `/etc/hosts`:

```
127.0.0.1 discourse.foo.bar
```

**Comment by jerrythomas** [comment]
Thank you. `DISCOURSE_HOSTNAME` was the issue. Changed it to `localhost` and it worked.

**Comment by frakman1** [comment]
I have the same problem. I had to change the port to something other than 80 (8899)
I changeds both instances of `DISCOURSE_HOSTNAME` to localhost but I still get this blank screen issue. I'm using Portainer with a Stack that uses this docker-compose.yml script:

```yaml
version: '2'
services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'docker.io/bitnami/discourse:2-debian-10'
    ports:
      - '8899:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=localhost
  sidekiq:
    image: 'docker.io/bitnami/discourse:2-debian-10'
    depends_on:
      - discourse
    volumes:
      - 'discourse_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=localhost
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
```

logs for the discourse container is:

``` 
Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
nami    INFO  Initializing postgresql-client
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql:5432
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Migrating database...
discour INFO 
discour INFO  ########################################################################
discour INFO   Installation parameters for discourse:
discour INFO     Persisted data and properties have been restored.
discour INFO     Any input specified will not take effect.
discour INFO   This installation requires no credentials.
discour INFO  ########################################################################
discour INFO 
nami    INFO  discourse successfully initialized
Starting discourse...
Creating scope :open. Overwriting existing method Poll.open.
Creating scope :open. Overwriting existing method Poll.open.
[ N 2021-01-31 10:42:29.0298 458/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-01-31 10:42:29.0538 461/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-01-31 10:42:29.0540 461/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-01-31 10:42:29.1440 461/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 461


[ N 2021-01-31 10:42:31.7453 461/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
Creating scope :open. Overwriting existing method Poll.open.
Started HEAD "/" for 127.0.0.1 at 2021-01-31 10:42:43 +0000
Processing by ListController#latest as HTML
  Rendering list/list.erb within layouts/crawler
  Rendered list/list.erb within layouts/crawler (Duration: 84.3ms | Allocations: 26641)
  Rendered layouts/_head.html.erb (Duration: 87.9ms | Allocations: 21269)
Completed 200 OK in 602ms (Views: 212.1ms | ActiveRecord: 0.0ms | Allocations: 160319)
Started GET "/" for 192.168.86.180 at 2021-01-31 10:51:33 +0000
Processing by ListController#latest as HTML
  Rendering list/list.erb within layouts/application
  Rendered list/list.erb within layouts/application (Duration: 7.8ms | Allocations: 1290)
  Rendered layouts/_head.html.erb (Duration: 1.6ms | Allocations: 266)
  Rendered common/_discourse_stylesheet.html.erb (Duration: 137.7ms | Allocations: 26942)
  Rendered application/_header.html.erb (Duration: 30.6ms | Allocations: 4277)
Completed 200 OK in 1139ms (Views: 651.9ms | ActiveRecord: 0.0ms | Allocations: 110889)
Creating scope :open. Overwriting existing method Poll.open.
[ N 2021-01-31 10:56:35.4528 461/T4 age/Cor/CoreMain.cpp:1147 ]: Checking whether to disconnect long-running connections for process 541, application /opt/bitnami/discourse (production)
```
