### ISSUE TITLE
Postgresql DB and user for discourse are not created properly

### ISSUE THREAD

**Issue by ggeo1992** [bitnami/bitnami-docker-discourse#148]
Hello,

I am having issues getting the required postgresql DB and user for the discourse app created on the postgre instane. I am trying to run discourse in a minikube cluster.
I am using minikube version 1.11.0, with driver=none on a Ubuntu 18.04.4 LTS system.
Below are my deployment.yaml files for both discourse and postgre:

Discourse:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discourse-apps-deployment
  labels:
    app: discourse-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discourse-apps
  template:
    metadata:
      labels:
        app: discourse-apps
    spec:
      containers:
      - name: discourse-apps
        image: docker.io/bitnami/discourse:2-debian-10
        ports:
        - containerPort: 3000
        env:
        - name: DISCOURSE_USERNAME
          value: "user"
        - name: DISCOURSE_PASSWORD
          value: "bitnami123"
        - name: DISCOURSE_EMAIL
          value: "user@example.com"
        - name: DISCOURSE_SITENAME
          value: "My site!"
        - name: DISCOURSE_HOSTNAME
          value: web-server
        - name: NAMI_DEBUG
          value: "3"
        - name: POSTGRESQL_ROOT_USER
          value: "postgres"
        #- name: POSTGRESQL_ROOT_PASSWORD
        #  valueFrom:
        #    secretKeyRef:
        #      name: pgsql-secret
        #      key: dbRootPassword
        - name: POSTGRESQL_HOST
          value: pgsql
        - name: POSTGRESQL_PORT_NUMBER
          value: "5432"
        - name: DISCOURSE_POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_USERNAME
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_USERNAME
        - name: DISCOURSE_POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_PASSWORD
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_PASSWORD
        - name: DISCOURSE_POSTGRESQL_NAME
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_DB_NAME
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_DB_NAME
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT_NUMBER
          value: "6379"
#        - name: REDIS_PASSWORD
#          value: "<enter-password-here>"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: STMP_PORT
          value: "587"
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: smtpPassword
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: smtpUsername
        volumeMounts:
          - name: discourse-data
            mountPath: /bitnami
      volumes:
      - name: discourse-data
        persistentVolumeClaim:
          claimName: discourse-pv-claim
```
Postgres:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pgsql-server
  template:
    metadata:
      labels:
        app: pgsql-server
    spec:
      containers:
        - name: pgsql-server
          image: docker.io/bitnami/postgresql:11-debian-10
          ports:
          - containerPort: 5432
          volumeMounts:
            - name: pgsql-storage
              mountPath: /bitnami/postgresql
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: NAMI_LOG_LEVEL
              value: "trace"
            #- name: POSTGRES_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: pgsql-secret
            #      key: dbRootPassword

      volumes:
      - name: pgsql-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
```
Logs i get in discourse are:
```
nami    INFO  Initializing postgresql-client
postgre DEBUG Waiting for service at pgsql:5432...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at pgsql:5432
postgre TRACE [canConnect] Testing connection with 'postgres' user
postgre TRACE [showDatabases] Getting databases for 'postgres' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dpostgres,-Upostgres,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n bitnami_application\n template1\n template0\n\n"
postgre TRACE [canConnect] Connection with 'postgres' user is successful
postgre INFO  PostgreSQL server listening and working at pgsql:5432
postgre TRACE [canConnect] Testing connection with 'discourseUser
' user
postgre TRACE [showDatabases] Getting databases for 'discourseUser
' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dpostgres,-UdiscourseUser
,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n bitnami_application\n template1\n template0\n\n"
postgre TRACE [canConnect] Connection with 'discourseUser
' user is successful
postgre TRACE [existsDatabase] Checking database existance for 'postgres' user
postgre TRACE [showDatabases] Getting databases for 'postgres' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dpostgres,-Upostgres,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n bitnami_application\n template1\n template0\n\n"
postgre TRACE [existsDatabase] Checking database existance for 'discourseUser
' user
postgre TRACE [showDatabases] Getting databases for 'discourseUser
' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dpostgres,-UdiscourseUser
,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n bitnami_application\n template1\n template0\n\n"
postgre DEBUG Reusing database and credentials
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
discour DEBUG Creating Discourse system user...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at pgsql:5432
postgre TRACE [canConnect] Testing connection with 'discourseUser
' user
postgre TRACE [showDatabases] Getting databases for 'discourseUser
' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dbitnami_application
,-UdiscourseUser
,-cSELECT datname FROM pg_database;
postgre ERROR [canConnect] Connection with 'discourseUser
' user is unsuccessful
postgre DEBUG Cannot connect to PostgreSQL server. Retrying in 5 seconds...
postgre TRACE [canConnect] Testing connection with 'discourseUser
' user
postgre TRACE [showDatabases] Getting databases for 'discourseUser
' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dbitnami_application
,-UdiscourseUser
,-cSELECT datname FROM pg_database;
postgre ERROR [canConnect] Connection with 'discourseUser
' user is unsuccessful
postgre DEBUG Cannot connect to PostgreSQL server. Retrying in 5 seconds...
postgre TRACE [canConnect] Testing connection with 'discourseUser
' user
postgre TRACE [showDatabases] Getting databases for 'discourseUser
' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dbitnami_application
,-UdiscourseUser
,-cSELECT datname FROM pg_database;
postgre ERROR [canConnect] Connection with 'discourseUser
' user is unsuccessful
postgre DEBUG Cannot connect to PostgreSQL server. Retrying in 5 seconds...
```
It seems that the sql client is not properly creating the discourse DB and USER. Although, if i connect to my postgre instance i can see the database being created. Also I see a login role named as the value of DISCOURSE_POSTGRESQL_USERNAME from the discourse deployment.
Any ideas what is wrong? I used the versions used in the README page.

Appreciate your help,
George

**Steps to reproduce the issue:**

1. Start up postgresql pod
2. Start up discourse pod

**Describe the results you received:**
Discourse pod will crash because it can't connect to postgresql

**Describe the results you expected:**
DIscourse pod to start an create the necessary postgresql resources.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 5
  Paused: 0
  Stopped: 2
 Images: 23
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-51-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.749GiB
 Name: ubuntu
 ID: IXBG:GNHQ:3TBM:2SM3:4N2S:OJOZ:X4GA:HNJ5:UXPE:J4QC:KAJR:CIV7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Trying to run this setup in minikube with driver=none, on ubuntu 18.04.4 as stated above.
