### ISSUE TITLE
Update from 2.4.4 to 2.5.0 does not work on existing environments

### ISSUE THREAD

**Issue by sbetzin** [bitnami/bitnami-docker-discourse#161]
**Description**

After updating my discourse docker images from 2.4.4 to 2.5.0 the forum is not working any more:
1. the header of the forum is empty
![image](https://user-images.githubusercontent.com/1607849/89889596-2e064780-dbd2-11ea-940e-8c0a24f77cef.png)
2. all existing threads are empty. 

![image](https://user-images.githubusercontent.com/1607849/89889713-6443c700-dbd2-11ea-8c5d-e6b70ae3872c.png)

**Steps to reproduce the issue:**

1. have an working 2.4.4 discourse forum running with this docker compose (ignore the ghost and caddy images)

```
version: '2'

## The 'z' option tells Docker that the volume content will be shared between containers. Docker will label the content with a shared content label. Shared volumes labels allow all containers to read/write content. The 'Z' option tells Docker to label the content with a private unshared label.

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    volumes:
      - /home/gg/Solawi-IT/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - /home/gg/Solawi-IT/docker/nginx/sites_ghost.conf:/etc/nginx/sites-enabled/sites_ghost.conf:z
      - /home/gg/Solawi-IT/docker/nginx/sites_discourse.conf:/etc/nginx/sites-enabled/sites_discourse.conf:z
      - /home/gg/Solawi-IT/docker/nginx/sites_caddy.conf:/etc/nginx/sites-enabled/sites_caddy.conf:z
      - letsencrypt:/etc/letsencrypt
      - ssl:/etc/ssl
      - logs:/var/log/nginx/custom
    ports:
      - "80:80"
      - "443:443"
    restart: always

  ghost:
    image: ghost
    container_name: ghost
    hostname: ghost
    volumes:
      #overwrite default settings
      - /home/gg/Solawi-IT/docker/ghost/config.production.json:/var/lib/ghost/config.production.json:z
      #overwrite template files
      - ghost:/var/lib/ghost/content:z
    environment:
      - NODE_ENV=production
    restart: always


  discourse-postgresql:
    image: bitnami/postgresql:11
    container_name: discourse-postgresql
    hostname: discourse-postgresql
    ports:
    - "5432:5432"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=discourse
      - POSTGRESQL_PASSWORD=**
      - POSTGRESQL_POSTGRES_PASSWORD=**
    volumes:
      - discourse:/bitnami/postgresql
    restart: always
  

  discourse-redis:
    image: bitnami/redis:5.0
    container_name: discourse-redis
    hostname: discourse-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - discourse:/bitnami
    restart: always


  # Discourse Config items
  # https://github.com/discourse/discourse/blob/master/config/discourse_defaults.conf
  discourse:
    image: bitnami/discourse:2.4.4
    container_name: discourse
    hostname: discourse
    depends_on:
      - discourse-postgresql
      - discourse-redis
    volumes:
      - discourse:/bitnami:z
      # - /home/gg/Solawi-IT/docker/discourse/discourse.conf:/opt/bitnami/discourse/mounted-conf/discourse.conf
    environment:
      - DISCOURSE_USERNAME=superuser
      - DISCOURSE_PASSWORD=**
      - DISCOURSE_EMAIL=**
      - DISCOURSE_HOSTNAME=forum.gutesgemuese.de
      - DISCOURSE_SITENAME=Gutes Gemüse Forum
      - REDIS_HOST=discourse-redis
      - POSTGRESQL_HOST=discourse-postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_ROOT_PASSWORD=**
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=**
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=**
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=587
      - SMTP_USER=apikey
      - SMTP_PASSWORD=**
      - DISCOURSE_LOAD_MINI_PROFILER=true
      - ENABLE_PERFORMANCE_HTTP_HEADERS=true
      - LOAD_MINI_PROFILER=true
      - DEVELOPER_EMAILS=**
      - DISCOURSE_DEVELOPER_EMAILS=**
    restart: always

  discourse-sidekiq:
    image: bitnami/discourse:2.4.4
    container_name: discourse-sidekiq
    hostname: discourse-sidekiq
    depends_on:
      - discourse
    volumes:
      - discourse:/bitnami:z
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - POSTGRESQL_HOST=discourse-postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - REDIS_HOST=discourse-redis
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=**
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=forum.gutesgemuese.de
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=587
      - SMTP_USER=apikey
      - SMTP_PASSWORD=**
    restart: always

  discourse-mail-receiver:
    image: discourse/mail-receiver:release
    container_name: discourse-mail-receiver
    hostname: discourse-mail-receiver
    ports:
      - "25:25"
    depends_on:
      - discourse
    environment:
      - MAIL_DOMAIN=forum.gutesgemuese.de
      - DISCOURSE_MAIL_ENDPOINT=http://discourse:3000/admin/email/handle_mail
      - DISCOURSE_API_USERNAME=system
      - DISCOURSE_API_KEY=**
      - LANG=en_US.UTF-8
    restart: always
    
  caddy:
    image: caddy
    container_name: caddy
    hostname: caddy
    volumes:
      - /home/gg/Solawi-IT/docker/caddy/index.html:/usr/share/caddy/index.html
    restart: always


volumes:
  ghost:
    external:
      name: ghost
  ssl:
    external:
      name: ssl
  letsencrypt:
    external:
      name: letsencrypt
  discourse:
    external:
      name: discourse
  logs:
    external:
      name: logs

```
2. Update the discourse image version to 2.5.0
3. stop docker compose
4. start docker compose

**Additional information you deem important (e.g. issue happens only occasionally):**

the docker logs does not show any error

```
docker logs b27e5d2200cd

Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing postgresql-client
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at discourse-postgresql:5432
postgre INFO  PostgreSQL server listening and working at discourse-postgresql:5432
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at discourse-postgresql:5432
postgre INFO  PostgreSQL server listening and working at discourse-postgresql:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Migrating database...
discour INFO
discour INFO  ########################################################################
discour INFO   Installation parameters for discourse:
discour INFO     Persisted data and properties have been restored.
discour INFO     Any input specified will not take effect.
discour INFO   This installation requires no credentials.
discour INFO  ########################################################################
discour INFO
nami    INFO  discourse successfully initialized
Starting discourse...
Creating scope :open. Overwriting existing method Poll.open.
Creating scope :open. Overwriting existing method Poll.open.
[ N 2020-08-11 10:53:47.0719 457/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2020-08-11 10:53:47.0915 460/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2020-08-11 10:53:47.0916 460/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2020-08-11 10:53:47.0989 460/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 460
[ N 2020-08-11 10:53:49.3764 460/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
Creating scope :open. Overwriting existing method Poll.open.
Started HEAD "/" for 127.0.0.1 at 2020-08-11 10:53:57 +0000
Processing by ListController#latest as HTML
Redirected to http://forum.gutesgemuese.de/login
Filter chain halted as :redirect_to_login_if_required rendered or redirected
Completed 302 Found in 208ms (ActiveRecord: 0.0ms | Allocations: 80609)
Creating scope :open. Overwriting existing method Poll.open.
Sent file /opt/bitnami/discourse/public/uploads/default/optimized/1X/88a6ab75cef278328dc56085ba920d131ad08b68_2_45x45.png (0.2ms)
Started GET "/" for 91.89.177.18 at 2020-08-11 10:54:17 +0000
Processing by ListController#latest as HTML
Creating scope :open. Overwriting existing method Poll.open.
Started GET "/t/bio-fleischlieferungen-sind-moeglich-an-alle-interessierte/389" for 51.137.33.21 at 2020-08-11 10:54:21 +0000
Processing by TopicsController#show as */*
  Parameters: {"slug"=>"bio-fleischlieferungen-sind-moeglich-an-alle-interessierte", "topic_id"=>"389"}
Redirected to https://forum.gutesgemuese.de/login
Filter chain halted as :redirect_to_login_if_required rendered or redirected
Completed 302 Found in 215ms (ActiveRecord: 0.0ms | Allocations: 81128)
  Rendering list/list.erb within layouts/application
  Rendered list/list.erb within layouts/application (Duration: 201.0ms | Allocations: 28439)
Sent file /opt/bitnami/discourse/public/uploads/default/optimized/1X/88a6ab75cef278328dc56085ba920d131ad08b68_2_45x45.png (0.2ms)
Started GET "/t/bio-fleischlieferungen-sind-moeglich-an-alle-interessierte/389" for 51.137.33.21 at 2020-08-11 10:54:22 +0000
Processing by TopicsController#show as */*
  Parameters: {"slug"=>"bio-fleischlieferungen-sind-moeglich-an-alle-interessierte", "topic_id"=>"389"}
Redirected to https://forum.gutesgemuese.de/login
Filter chain halted as :redirect_to_login_if_required rendered or redirected
Completed 302 Found in 1ms (ActiveRecord: 0.0ms | Allocations: 615)
  Rendered layouts/_head.html.erb (Duration: 56.5ms | Allocations: 12103)
  Rendered common/_google_universal_analytics.html.erb (Duration: 0.8ms | Allocations: 214)
  Rendered common/_discourse_stylesheet.html.erb (Duration: 165.4ms | Allocations: 19984)
  Rendered application/_header.html.erb (Duration: 39.1ms | Allocations: 502)
Completed 200 OK in 6679ms (Views: 1981.2ms | ActiveRecord: 0.0ms | Allocations: 568655)

```

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-1032-azure
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.818GiB
 Name: gutes-gemuese
 ID: A2LW:NCZ7:5XQL:P7TL:PQOL:FE2T:66E4:CZDB:RU4Q:NAHK:E6CY:A4O3
 Docker Root Dir: /datadrive/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```
