### ISSUE TITLE
discourse-chat-integration Job exception: uninitialized constant Jobs::NotifyChats Did you mean? Notification

### ISSUE THREAD

**Issue by qxmips** [bitnami/bitnami-docker-discourse#163]
**Description**

**Steps to reproduce the issue:**

cleate docker-compose:
```
ervices:
  postgresql:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './postgresql_data:/bitnami/postgresql'
  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './redis_data:/bitnami'
  discourse:
    image: 'docker.io/bitnami/discourse:2.5.0'
    ports:
      - 80:3000
    depends_on:
      - postgresql
      - redis
    volumes:
      - './discourse_data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=hostname
      - DISCOURSE_SKIP_INSTALL=no
      - REDIS_HOST=redis
   sidekiq:
    image: 'docker.io/bitnami/discourse:2.5.0'
    depends_on:
      - discourse
    volumes:
      - './discourse_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=hostname
      - DISCOURSE_SKIP_INSTALL=no
      - REDIS_HOST=redis
```
installed plugins including  https://github.com/discourse/discourse-chat-integration
restored from a backup. the plugin is configured to notify slack about new topics. 

**Describe the results you received:**

the plugin is configured to notify slack about new topics. 
But when a new topic is created it is not sending messages to slack.
"test" functionality of the plugin works though.  When using test button, test  messages are received 
Log has  following entry:
```
Job exception: uninitialized constant Jobs::NotifyChats Did you mean? Notification
```
**Describe the results you expected:**
slack receives messages 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
2.5.0- 2.5.1
- Output of `docker version`:

```
19.03.6-ce
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 10
 Server Version: 19.03.6-ce
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.186-146.268.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.851GiB
 Name: ip-10-1-10-112.vyos.local
 ID: P62Q:QPJH:DGAJ:6MM2:TIQQ:U4WL:L6OK:NPCB:6F77:MEEK:BAD6:EHZW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

same in AWS fargate.
