### ISSUE TITLE
[BUG] PermissionError : bootsnap doesn't have permission to write cache entries

### ISSUE THREAD

**Issue by madmath03** [bitnami/bitnami-docker-discourse#167]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

Discourse container starts properly, but when trying to access the website, I get this error message:
```
Oops
The software powering this discussion forum encountered an unexpected problem. We apologize for the inconvenience.

Detailed information about the error was logged, and an automatic notification generated. We'll take a look at it.

No further action is necessary. However, if the error condition persists, you can provide additional detail, including steps to reproduce the error, by posting a discussion topic in the site's feedback category.
```

**Steps to reproduce the issue:**

1. Start Discourse with the following docker-compose:
```yml
version: '2.4'

services:
  # Discourse services
  discourse:
    image: bitnami/discourse:2
    hostname: discourse
    domainname: ${DOMAIN}
    container_name: discourse
    #restart: always
    ports:
      - "3000:3000"
    networks:
      - discourse_external_network
      - discourse_internal_network
    depends_on:
      discourse_db:
        condition: service_healthy
      discourse_redis:
        condition: service_started
    links:
      - discourse_db
      - discourse_redis
    volumes:
      - /srv/discourse/data/:/bitnami
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # Site Config
      - DISCOURSE_SITENAME=Discourse
      - DISCOURSE_HOST=discourse.${DOMAIN}
      - DISCOURSE_HOSTNAME=discourse.${DOMAIN}
      - DISCOURSE_EXTERNAL_PORT_NUMBER=443
      - DISCOURSE_USERNAME=${DISCOURSE_ADMIN_LOGIN}
      - DISCOURSE_PASSWORD=${DISCOURSE_ADMIN_PWD}
      - DISCOURSE_EMAIL=discourse@${DOMAIN}
      # DB Config
      - POSTGRESQL_HOST=discourse_db
      - POSTGRESQL_PORT_NUMBER=5432
      - POSTGRESQL_ROOT_USER=${DISCOURSE_DB_USER}
      - POSTGRESQL_ROOT_PASSWORD=${DISCOURSE_DB_PWD}
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=${DISCOURSE_DB_USER}
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=${DISCOURSE_DB_USER}
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=${DISCOURSE_DB_PWD}
      - DISCOURSE_POSTGRESQL_NAME=${DISCOURSE_DB_USER}
      - DISCOURSE_POSTGRESQL_USERNAME=${DISCOURSE_DB_USER}
      - DISCOURSE_POSTGRESQL_PASSWORD=${DISCOURSE_DB_PWD}
      # Redis Config
      - REDIS_HOST=discourse_redis
      - REDIS_PORT_NUMBER=6379
      #- REDIS_PASSWORD=${DISCOURSE_REDIS_PWD}
      # SMTP Config
      - SMTP_AUTH=login
      - SMTP_HOST=smtp.${DOMAIN}
      - SMTP_PORT=587
      - SMTP_USER=${DISCOURSE_SMTP_USER}
      - SMTP_PASSWORD=${DISCOURSE_SMTP_PWD}
      - SMTP_TLS=yes

  discoursesidekiq:
    image: bitnami/discourse:2
    container_name: discoursesidekiq
    #restart: always
    command: 'nami start --foreground discourse-sidekiq'
    depends_on:
      - discourse
    networks:
      - discourse_external_network
      - discourse_internal_network
    volumes:
      - /srv/discourse/data/:/bitnami
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # Site Config
      - DISCOURSE_HOST=discourse
      - DISCOURSE_HOSTNAME=discourse.${DOMAIN}
      - DISCOURSE_PORT=3000
      - DISCOURSE_USERNAME=${DISCOURSE_ADMIN_LOGIN}
      - DISCOURSE_PASSWORD=${DISCOURSE_ADMIN_PWD}
      - DISCOURSE_EMAIL=discourse@${DOMAIN}
      # DB Config
      - POSTGRESQL_HOST=discourse_db
      - POSTGRESQL_PORT_NUMBER=5432
      - DISCOURSE_POSTGRESQL_NAME=${DISCOURSE_DB_USER}
      - DISCOURSE_POSTGRESQL_USERNAME=${DISCOURSE_DB_USER}
      - DISCOURSE_POSTGRESQL_PASSWORD=${DISCOURSE_DB_PWD}
      # Redis Config
      - REDIS_HOST=discourse_redis
      - REDIS_PORT_NUMBER=6379
      #- REDIS_PASSWORD=${DISCOURSE_REDIS_PWD}
      # SMTP Config
      - SMTP_AUTH=login
      - SMTP_HOST=smtp.${DOMAIN}
      - SMTP_PORT=587
      - SMTP_USER=${DISCOURSE_SMTP_USER}
      - SMTP_PASSWORD=${DISCOURSE_SMTP_PWD}
      - SMTP_TLS=yes

  discourse_db:
    image: postgres:11-alpine
    container_name: discourse_db
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DISCOURSE_DB_USER}"]
      interval: 60s
      retries: 5
      #start-period: 10s
    expose:
      - '5432'
    networks:
      - discourse_internal_network
    environment:
      - POSTGRES_USER=${DISCOURSE_DB_USER}
      - POSTGRES_PASSWORD=${DISCOURSE_DB_PWD}
    volumes:
      - /srv/discourse/db/data/:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  discourse_redis:
    image: redis:5.0-alpine
    container_name: discourse_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    expose:
      - '6379'
    networks:
      - discourse_internal_network
    environment:
      #- REDIS_PASSWORD=${DISCOURSE_REDIS_PWD}
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /srv/discourse/redis/:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  # Discourse networks
  discourse_external_network:
  discourse_internal_network:
    internal: true

```
2. Check logs to be sure install successful:
```
discourse           | 
discourse           | Welcome to the Bitnami discourse container
discourse           | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
discourse           | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
discourse           | 
discourse           | nami    INFO  Initializing postgresql-client
discourse           | postgre INFO  Trying to connect to PostgreSQL server
discourse           | postgre INFO  Found PostgreSQL server listening at discourse_db:5432
discourse           | postgre INFO  PostgreSQL server listening and working at discourse_db:5432
discourse           | nami    INFO  postgresql-client successfully initialized
discourse           | nami    INFO  Initializing discourse
discourse           | discour INFO  Patching Discourse...
discourse           | postgre INFO  Trying to connect to PostgreSQL server
discourse           | postgre INFO  Found PostgreSQL server listening at discourse_db:5432
discourse           | postgre INFO  PostgreSQL server listening and working at discourse_db:5432
discourse           | discour INFO  Preparing Discourse environment...
discourse           | discour INFO  Configuring the Discourse database files...
discourse           | discour INFO  Configuring Redis...
discourse           | discour INFO  Setting up SMTP in Discourse...
discourse           | discour INFO  Configuring Discourse database...
discourse           | discour INFO  Enabling PostgreSQL plugins for Discourse...
discourse           | discour INFO  Migrating database...
discourse           | discour INFO  Creating the Discourse admin user...
discourse           | discour INFO  Configuring your Discourse installation...
discourse           | discour INFO 
discourse           | discour INFO  ########################################################################
discourse           | discour INFO   Installation parameters for discourse:
discourse           | discour INFO     Username: root
discourse           | discour INFO     Password: **********
discourse           | discour INFO   (Passwords are not shown for security reasons)
discourse           | discour INFO  ########################################################################
discourse           | discour INFO 
discourse           | nami    INFO  discourse successfully initialized
discourse           | Starting discourse...
discourse           | Migrating to AddPublicFieldToPublishedPages (20200617144300)
discourse           | Migrating to DeleteTrackingStateForStagedUsers (20200618175923)
discourse           | Migrating to AddPartialTargetIdIndexToReviewables (20200820174703)
discourse           | Creating scope :open. Overwriting existing method Poll.open.
discourse           | Creating scope :open. Overwriting existing method Poll.open.
discourse           | [ N 2020-10-20 23:52:06.0144 511/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
discourse           | [ N 2020-10-20 23:52:06.0550 514/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
discourse           | [ N 2020-10-20 23:52:06.0552 514/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
discourse           | [ N 2020-10-20 23:52:06.0785 514/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 514
discourse           | [ N 2020-10-20 23:52:08.3884 514/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
discourse           | Creating scope :open. Overwriting existing method Poll.open.
discourse           | Started HEAD "/" for 127.0.0.1 at 2020-10-20 23:52:50 +0000
discourse           | Processing by ListController#latest as HTML
discourse           |   Rendering list/list.erb within layouts/crawler
discourse           |   Rendered list/list.erb within layouts/crawler (Duration: 375.3ms | Allocations: 25381)
discourse           |   Rendered layouts/_head.html.erb (Duration: 68.1ms | Allocations: 19027)
discourse           | Completed 200 OK in 1699ms (Views: 604.3ms | ActiveRecord: 0.0ms | Allocations: 218747)
discourse           | Creating scope :open. Overwriting existing method Poll.open.
discourse           | Creating scope :open. Overwriting existing method Poll.open.
discourse           | Creating scope :open. Overwriting existing method Poll.open.
discourse           | Started GET "/" for 2.3.75.18 at 2020-10-21 00:06:20 +0000
discourse           | Processing by ListController#latest as HTML
```
3. Install additional plugins:
```bash
docker-compose exec -T discourse sh -c "cd /opt/bitnami/discourse && RAILS_ENV=production bundle exec rake plugin:install[https://github.com/jonmbake/discourse-ldap-auth]"
# and other similar plugins
```
4. Precompile assets:
```bash
docker-compose exec -T discourse sh -c "cd /opt/bitnami/discourse && RAILS_ENV=production bundle exec rake assets:precompile"
```
5. access Discourse website at discourse.$DOMAIN

**Describe the results you received:**

The discourse container show the following error in the logs when trying to access the web page:
```
discourse           | Completed 500 Internal Server Error in 4186ms (ActiveRecord: 0.0ms | Allocations: 26527)
discourse           | Errno::EACCES (Permission denied @ rb_sysopen - tmp/cache/bootsnap-load-path-cache.493.85473.tmp)
discourse           | /opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/store.rb:83:in `binwrite'
discourse           | Started GET "/favicon.ico" for 2.3.75.18 at 2020-10-20 13:31:52 +0000
discourse           | ActionController::RoutingError (No route matches [GET] "/favicon.ico")
discourse           | /opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
discourse           | Failed to handle exception in exception app middleware : bootsnap doesn't have permission to write cache entries in 'tmp/cache/bootsnap-compile-cache' (or, less likely, doesn't have permission to read '/opt/bitnami/discourse/lib/topic_query_sql.rb')
discourse           | Started GET "/" for 2.3.75.18 at 2020-10-20 13:32:05 +0000
discourse           | Processing by ListController#latest as HTML
discourse           | Completed 500 Internal Server Error in 45ms (ActiveRecord: 0.0ms | Allocations: 586)
discourse           | Bootsnap::CompileCache::PermissionError (bootsnap doesn't have permission to write cache entries in 'tmp/cache/bootsnap-compile-cache' (or, less likely, doesn't have permission to read '/opt/bitnami/discourse/lib/flag_settings.rb'))
discourse           | /opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/compile_cache.rb:29:in `permission_error'
```

**Describe the results you expected:**

Access to Discourse.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
> docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
> docker info
Client:
 Debug Mode: false

Server:
 Containers: 15
  Running: 15
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-118-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.852GiB
 Name: mbrunot
 ID: KQTF:KOQK:EK4U:O4MT:RZAR:FUEC:NB7J:AT7K:EZIN:ZFVN:HZJ2:6DLB
 Docker Root Dir: /srv/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
> docker-compose version
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
