### ISSUE TITLE
trouble with set up

### ISSUE THREAD

**Issue by XoniBlue** [bitnami/bitnami-docker-discourse#186]
Hello friends im trying to get this all set up and working and im not sure what im doing wrong. 

to me it looks as if all is actually working so maybe im missing what to do next.  as when i load ip/port for discourse it does pull up a empty white page with the tabe header of "My Site!", 

here is the docker-compose code. 

```yml
version: "2"
services:
 postgresql:
    image: docker.io/bitnami/postgresql:11
 ##   network_mode: Xoni-Main
    container_name: dc_postgres
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=America/Phoenix
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /dockerconfigs/discourse_stack/postgresql_data:/bitnami/postgresql/data
  redis:
    image: docker.io/bitnami/redis:6.0
  ##  network_mode: Xoni-Main
    container_name: dc_redis
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=America/Phoenix
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /dockerconfigs/discourse_stack/redis_data:/bitnami
  discourse:
    image: docker.io/bitnami/discourse:2
  ##  network_mode: Xoni-Main
    container_name: Discourse
    restart: unless-stopped
    ports:
      - 3500:3000
    depends_on:
      - postgresql
      - redis
    volumes:
      - /dockerconfigs/discourse_stack/discourse_data:/bitnami
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=America/Phoenix
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse_xoni
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1_xoni
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse_xoni
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1_xoni
      - DISCOURSE_HOSTNAME=https://envision.xoni.me
  sidekiq:
    image: docker.io/bitnami/discourse:2
   ## network_mode: Xoni-Main
    container_name: dc_sidekiq
    restart: unless-stopped
    depends_on:
      - discourse
    volumes:
      - /dockerconfigs/discourse_stack/discourse_data:/bitnami
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=America/Phoenix
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse_xoni
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1_xoni
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=https://envision.xoni.me
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local`
```
again maybe im just missing something

as well all the spots that say network mode xoni are commented out, but trying to edit that for this post screws up the formatting so i left it.
