### ISSUE TITLE
All containers have started and have no errors, but I cannot access the ip:3000 

### ISSUE THREAD

**Issue by mikekay1** [bitnami/bitnami-docker-discourse#188]
Can someone please tell me what I wrong with my docker-compose? everything works fine, but when I try to access ip:3000 I get a connection refused. I dont understand and have other containers running on the server working just fine.

Please help

```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
#    container_name: prod_discourse_postgresql
    environment:
      -  POSTGRES_PASSWORD=####
      -  POSTGRES_DATABASE=discourse
#     - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/home/mikekay/docker-containers/discourse/postgresql_data:/bitnami/postgresql'

  redis:
    image: docker.io/bitnami/redis:6.0
#    container_name: prod_discourse_redis
    environment:
#      - DISABLE_COMMANDS="FLUSHDB,FLUSHALL,CONFIG"
      - REDIS_PASSWORD=###
    volumes:
      - '/home/mikekay/docker-containers/discourse/redis_data:/bitnami'
  discourse:
    image: docker.io/bitnami/discourse:2
#    container_name: prod_discourse_discourse
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - '/home/mikekay/docker-containers/discourse/discourse_data:/bitnami'
    environment:      
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_ROOT_PASSWORD=###
      - REDIS_HOST=redis
      - REDIS_PASSWORD=###
#      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=discourse
#      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=postgres
#      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=###
      - DISCOURSE_POSTGRESQL_NAME=discourse
      - DISCOURSE_POSTGRESQL_USERNAME=postgres
      - DISCOURSE_POSTGRESQL_PASSWORD=###
      - DISCOURSE_HOSTNAME=talk.###.ca
      - DISCOURSE_USERNAME=root
      - DISCOURSE_PASSWORD=###
      - DISCOURSE_EMAIL=admin@###.ca
  sidekiq:
    image: docker.io/bitnami/discourse:2
#    container_name: prod_discourse_sidekiq
    depends_on:
      - discourse
    volumes:
      - '/home/mikekay/docker-containers/discourse/sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=discourse
      - DISCOURSE_POSTGRESQL_USERNAME=postgres
      - DISCOURSE_POSTGRESQL_PASSWORD=###
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=talk.###.ca
#      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=discourse
#      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=postgres
#      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=###
      - REDIS_HOST=redis
      - REDIS_PASSWORD=###

volumes:
  postgresql_data:    
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```
