### ISSUE TITLE
external pgSQL does not work (or env vars do not)

### ISSUE THREAD

**Issue by lejeczek** [bitnami/bitnami-docker-discourse#193]
Hi. I follow docs and what I expected would be simple turns out to be either very tricky or quite broken.

I try to tell container to use already existing pgSQL database so I do use:
...
-e DISCOURSE_USERNAME=adm -e DISCOURSE_PASSWORD=privateloter -e DISCOURSE_EMAIL=me@private.lot -e DISCOURSE_SITENAME=private.lot -e DISCOURSE_HOSTNAME=private.lot -e POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=privatelot -e POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD='privateloter' -e POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=privateloter -e POSTGRESQL_HOST=10.1.1.226 -e POSTGRESQL_PORT_NUMBER=5432 -e POSTGRESQL_ROOT_PASSWORD='privateloter' -e POSTGRESQL_ROOT_USER=privateloter 
..
so I expect 'Discourse' to use **empty** pgSQL database on a remote, external server which, even though it has the needed permissions, shows in logs:
...
FATAL:  no pg_hba.conf entry for host "10.1.0.224", user "privateloter", database "privateloter", SSL off
..

First obvious question is why 'privateloter' when POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=privatelot ?
But next question is - does that Bitnami's Discourse really work with external pgSQL and if so then which env vars must be used?

many thanks, L.

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alvneiayu** [comment]
hi @lejeczek 

Let me try to reproduce your issue. I will come back with some feedback as soon as possible.

Thanks

Álvaro

**Comment by marcosbc** [comment]
Hi, I can confirm that Discourse works with external database. In fact we support that feature in charts and it is being used without problems.

>First obvious question is why 'privateloter' when POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=privatelot ?

That is probably happening because there is some PostgreSQL query to check if the connection was successful, and it is not specifying the DB name, so it tries to use the same DB as the user (and thus throwing that warning). Could you confirm that the DB gets created without problems? If not, please provide full logs.

**Comment by lejeczek** [comment]
Since Bitnami docs do not cover that bit (or I fail to find it) I use & follow this - https://meta.discourse.org/t/running-discourse-with-a-separate-postgresql-server/46375
Then, database name (& other bits) created that way I provide to Bitnami's container env vars - this should be easy to reproduce.

May I ask how exactly and what logs I should get you?
many thanks, L.

**Comment by alvneiayu** [comment]
hi @lejeczek 

I created using our containers an external Postgresql and Redis:
* Postgresql
```
docker run --name postgresql -e POSTGRESQL_PASSWORD='mypassword' -e POSTGRESQL_USERNAME=bn_discourse -e POSTGRESQL_DATABASE=bitnami_discourse -e POSTGRESQL_POSTGRES_PASSWORD='mypassword' bitnami/postgresql:latest
```
* Redis
```
docker run --name redis -e REDIS_PASSWORD='mypassword' bitnami/redis:latest
```
And I connected Discourse with them using the IPs assigned using these env vars:
```
docker run --name discourse_alv -p 8443:8443 -e DISCOURSE_USERNAME=adm -e DISCOURSE_PASSWORD=privateloter -e DISCOURSE_DATABASE_USER=bn_discourse -e DISCOURSE_DATABASE_PASSWORD=mypassword -e DISCOURSE_DATABASE_NAME=bitnami_discourse -e DISCOURSE_HOST=localhost -e POSTGRESQL_HOST=#POSTGRES-IP# -e POSTGRESQL_PORT_NUMBER=5432 -e POSTGRESQL_ROOT_PASSWORD='mypassword' -e DISCOURSE_DATABASE_PORT_NUMBER=5432 -e DISCOURSE_POSTGRESQL_PASSWORD='mypassword' -e DISCOURSE_DATABASE_HOST=#POSTGRES-IP# -e DISCOURSE_REDIS_HOST=#REDIS-IP# -e DISCOURSE_REDIS_PASSWORD='mypassword' -e DISCOURSE_REDIS_PORT_NUMBER=6379 -e POSTGRESQL_CLIENT_POSTGRES_USER=postgres -e POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse -e POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm -e DISCOURSE_PORT_NUMBER=8443 -e DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER=8443 discourse:latest
```
And Discourse is running in localhost:8443 without any problem. I hope this can help you to connect your Discourse.

Thanks

Álvaro

**Comment by lejeczek** [comment]
Hi @alvneiayu
No, not Bitnami's "external" containers. I, in my first message said "..so I expect 'Discourse' to use empty pgSQL database on a remote, external server which.."

I mustn't be the first & only "customer" who wants to hook up Bitnami's Discourse to a already up&running pgSQL (and Redis). Such a setup I suggested should be easy to reproduce - put/use pgSQL (& Redis) on the host where containers run to make it easy(no "remote" servers) but!.. (obviously) non-container but OS'es installations, most likely via/from OS default packaging system (or any other way but non-container pgSQL)

**Comment by marcosbc** [comment]
Hi @lejeczek, note that the Bitnami Discourse container image is fully compatible with non-Bitnami instances of PostgreSQL. You just need to specify the proper environment configuration.

For instance, you can check this `docker-compose.yml` example of Bitnami Discourse container using Dockerhub's official PostgreSQL image:

```yaml
version: '2'
services:
  postgresql:
    image: postgres:11
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=pgpassword
  redis:
    image: docker.io/bitnami/redis:6.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/discourse'
  discourse:
    image: docker.io/bitnami/discourse:2
    ports:
      - '80:3000'
    volumes:
      - 'discourse_data:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
    environment:
      - DISCOURSE_HOST=www.example.com
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      # DB configuration
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_PASSWORD=pgpassdiscourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      # PostgreSQL authentication for 'postgres' user
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_POSTGRES_PASSWORD=pgpassword
      # Create external DB
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USER=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=pgpassdiscourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
  sidekiq:
    image: docker.io/bitnami/discourse:2
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      - DISCOURSE_HOST=www.example.com
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      # DB configuration
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_PASSWORD=pgpassdiscourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

You would only need to adapt those changes to your own PostgreSQL instance.

To check the rest of the available configuration options for the container image, please check the [Configuration section](https://github.com/bitnami/bitnami-docker-discourse#configuration) in the README.
