### ISSUE TITLE
Getting from Development instance to Production

### ISSUE THREAD

**Issue by Tabascl** [bitnami/bitnami-docker-discourse#207]
Hello,

I'm currently running the official docker_compose, which does not have passwords set.
Now, I'd like to set them, for security reasons, without losing my existing data.
I tried just setting POSTGRESQL_PASSWORD for the postgresql service, and DISCOURSE_DATABASE_PASSWORD for the other containers and removing ALLOW_EMPTY_PASSWORDS, but this doesn't work.

At first the discourse instance complained that a POSTGRESQL_CLIENT_POSTGRES_PASSWORD (which to my surprise is not listed in the readme) was missing. I added that with the database password, which allowed the container to stay running, but it never got a connection to the database.

Is there a guide to do something like this?

**Comment by marcosbc** [comment]
Hi, unfortunately there is no guide, but it would be enough for you to do the following:

1. Backup the contents from the local database
2. Restore the backup of your database to the secured one. Make sure it enables [these extensions](https://github.com/bitnami/bitnami-docker-discourse/blob/master/docker-compose.yml#L40).
3. Point to your new database via `DISCOURSE_DATABASE_*` options. You should remove any `POSTGRESQL_CLIENT_` option since those are only used to initialize the database for the first time.

>At first the discourse instance complained that a POSTGRESQL_CLIENT_POSTGRES_PASSWORD (which to my surprise is not listed in the readme) was missing

You seem to be right. There is apparently a typo in the readme and it should be `POSTGRESQL_CLIENT_POSTGRES_PASSWORD` instead of `POSTGRESQL_CLIENT_DATABASE_POSTGRES_PASSWORD`.

**Comment by opsi-archIT-KIT** [comment]
Having a similar problem, but I never wanted to start without password. Something is wrong with my docker-compose.yml, but what?

```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_DATABASE=bitnami_discourse
    networks:
      - default
  redis:
    image: docker.io/bitnami/redis:6.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/discourse'
    networks:
      - default
  discourse:
    image: docker.io/bitnami/discourse:2
    volumes:
      - 'discourse_data:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
    environment:
      - VIRTUAL_HOST=forum.example.org
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=forum.example.org
      - LETSENCRYPT_EMAIL=webmaster@example.org
      - DISCOURSE_HOST=forum.example.org
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_PASSWORD=secret
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_POSTGRES_PASSWORD=secret
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USER=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=secret
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
    networks:
      - proxy-tier
      - default
  sidekiq:
    image: docker.io/bitnami/discourse:2
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      - DISCOURSE_HOST=forum.example.org
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_PASSWORD=secret
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
    networks:
      - default
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local

networks:
  proxy-tier:
    external: true
```

After starting this error is shown:

discourse 12:42:34.93 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 12:42:34.94 INFO  ==> Trying to connect to the database server
discourse 12:43:35.33 ERROR ==> Could not connect to the database server

Any hints what's wrong with the docker-compose.yml?
