### ISSUE TITLE
DISCOURSE_SMTP_PASSWORD: Special characters are truncated 

### ISSUE THREAD

**Issue by jensensen** [bitnami/bitnami-docker-discourse#208]
**Description**

The password that was set in docker-compose.yml is not the same as it should be in:
/opt/bitnami/discourse/config/discourse.conf

Special characters are truncated or deleted.

I've installed Discourse, but email doesn’t seem to work. 
I could fix SMTP mail by changing the account settings at the host.

**Steps to reproduce the issue:**

1. In docker-compose.yml set DISCOURSE_SMTP_PASSWORD: my-pwd#!k876+2E
2. Start all the container
3. Open shell to the bitnami_discourse container
4. Check file /opt/bitnami/discourse/config/discourse.conf
5. Look at the entry smtp_password = my-pwdk876+2E

**Describe the results you received:**

In the file 
/opt/bitnami/discourse/config/discourse.conf
the variable
smtp_password = my-pwdk876+2E

**Describe the results you expected:**

It should be the same as in docker-compose.yml 
where the variable was set
DISCOURSE_SMTP_PASSWORD: my-pwd#!k876+2E

**Additional information you deem important (e.g. issue happens only occasionally):**

This is not the original password the problem occured. But I had problems with the special character #

My setup is based on

image: docker.io/bitnami/discourse:2
and 
https://github.com/bitnami/bitnami-docker-discourse/blob/master/docker-compose.yml

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-8-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.771GiB
 Name: srv02
 ID: R6S5:HFI3:YYR2:OEGQ:TXVL:XQUZ:LUF3:IMAO:DHT4:KT54:TVFD:H5OG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.9.2
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

VPS, Debian 11

**Comment by alemorcuq** [comment]
Hi, @jensensen.

I wasn't able to reproduce your issue. This is the `docker-compose.yaml` file I used:

```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_DATABASE=bitnami_discourse
  redis:
    image: docker.io/bitnami/redis:6.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/discourse'
  discourse:
    image: docker.io/bitnami/discourse:2
    ports:
      - '80:3000'
    volumes:
      - 'discourse_data:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=www.example.com
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_SMTP_HOST=localhost
      - DISCOURSE_SMTP_PORT_NUMBER=8942
      - DISCOURSE_SMTP_USER=ale
      - DISCOURSE_SMTP_PASSWORD=my-pwd#!k876+2E
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
  sidekiq:
    image: docker.io/bitnami/discourse:2
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=www.example.com
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

And this is the resulting `discourse.conf` file:

```
root@8a5365af2b92:/# cat /opt/bitnami/discourse/config/discourse.conf
hostname = www.example.com
db_host = postgresql
db_port = 5432
db_username = bn_discourse
db_password = 
db_name = bitnami_discourse
redis_host = redis
redis_port = 6379
redis_password = 
smtp_address = localhost
smtp_port = 8942
smtp_user_name = ale
smtp_password = my-pwd#!k876+2E
smtp_enable_start_tls = false
smtp_authentication = login
yes
```

Could you share your `docker-compose.yaml` file to see if I can reproduce the issue with that one?

**Comment by jensensen** [comment]
Hi @alemorcuq
thank you for stepping in.
I've made persistent volumes and I'm using passwords on that machine in production.

This is my docker-compose.yaml file.

```
version: '2'
networks:
  default:
    external:
      name: nw-disco
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    container_name: dis_postgres
    restart: always
    volumes:
#      - 'postgresql_data:/bitnami/postgresql'
      - /opt/docker/disco/vol-postgresql:/bitnami/postgresql
      - /opt/docker/disco/vol-entry-init:/docker-entrypoint-initdb.d
      - /opt/docker/disco/vol-entry-preinit:/docker-entrypoint-preinitdb.d
    environment:
      - TZ=Europe/Berlin
#      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=PG-passWD-/#!17UbN
      - POSTGRESQL_DATABASE=bitnami_discourse
  redis:
    image: docker.io/bitnami/redis:6.0
    container_name: dis_redis
    restart: always
    environment:
      - TZ=Europe/Berlin
#      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=redisPWD987123
    volumes:
#      - 'redis_data:/bitnami/discourse'
      - /opt/docker/disco/vol-redis:/bitnami/redis
  discourse:
    image: docker.io/bitnami/discourse:2
    container_name: dis_bn_disco
    restart: always
    ports:
      - 8071:3000
#      - '80:3000'
#      - 192.168.56.100:8072:3000
    volumes:
#      - 'discourse_data:/bitnami/discourse'
      - /opt/docker/disco/vol-disco:/bitnami/discourse
      - /opt/docker/disco/conf:/opt/bitnami/discourse/mounted-conf
    depends_on:
      - postgresql
      - redis
    environment:
      - TZ=Europe/Berlin
#      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=www.example.com
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=postgres
      - DISCOURSE_DATABASE_PASSWORD=PG-passWD-/#!17UbN
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - DISCOURSE_REDIS_PASSWORD=redisPWD987123
#
      - POSTGRESQL_CLIENT_DATABASE_HOST=postgresql
      - POSTGRESQL_CLIENT_DATABASE_PORT_NUMBER=5432
      - POSTGRESQL_CLIENT_DATABASE_ROOT_USER=root
      - POSTGRESQL_CLIENT_DATABASE_ROOT_PASSWORD=root123
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=PG-passWD-/#!17UbN
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_POSTGRES_PASSWORD=PG-passWD-/#!17UbN
#
      - DISCOURSE_USERNAME=admin
      - DISCOURSE_PASSWORD=adminPWD-123
      - DISCOURSE_EMAIL=admin@example.com
#      - DISCOURSE_FIRST_NAME=firstN
#      - DISCOURSE_LAST_NAME=lastN
#      - DISCOURSE_SITE_NAME=my-site!
# mail
      - DISCOURSE_SMTP_HOST=mail.example.com
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=info@example.com
      - DISCOURSE_SMTP_PASSWORD=my-pwd#!k876+2EZ#/m)-!B6
      - DISCOURSE_SMTP_PROTOCOL=tls
#
sidekiq:
    image: docker.io/bitnami/discourse:2
    container_name: dis_sidekiq
    restart: always
    depends_on:
      - discourse
    volumes:
#      - 'sidekiq_data:/bitnami/discourse'
      - /opt/docker/disco/vol-disco:/bitnami/discourse
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      - TZ=Europe/Berlin
#
      - DISCOURSE_HOST=www.example.com
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=postgres
      - DISCOURSE_DATABASE_PASSWORD=PG-passWD-/#!17UbN
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - DISCOURSE_REDIS_PASSWORD=redisPWD987123
# mail
      - DISCOURSE_SMTP_HOST=mail.example.com
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=info@example.com
      - DISCOURSE_SMTP_PASSWORD=my-pwd#!k876+2EZ#/m)-!B6
      - DISCOURSE_SMTP_PROTOCOL=tls
#
#volumes:
#  postgresql_data:
#    driver: local
#  redis_data:
#    driver: local
#  discourse_data:
#    driver: local
#  sidekiq_data:
#    driver: local
#
# volumes needed
#/docker-entrypoint-initdb.d
#/docker-entrypoint-preinitdb.d

```
