### ISSUE TITLE
site_settings.yml incorrectly copying to discourse/config directory

### ISSUE THREAD

**Issue by christropher** [bitnami/bitnami-docker-discourse#230]
### Name and Version

docker.io/bitnami/discourse:latest

### What steps will reproduce the bug?

While running this `docker-compose.yml` file, the container will copy `site_settings.yml` into the config directory, attempt to run the migration rake task, and fail silently. I am using the default discourse `site_settings.yml` with no changes to isolate what the problem is.

```yml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_DATABASE=bitnami_discourse
  redis:
    image: docker.io/bitnami/redis:6.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis'
  discourse:
    image: docker.io/bitnami/discourse:latest
    ports:
      - '80:3000'
    volumes:
      - 'discourse_data:/bitnami/discourse'
      - ${PWD}/default_settings.yml:/opt/bitnami/discourse/mounted-conf/site_settings.yml
    depends_on:
      - postgresql
      - redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - DISCOURSE_CONF_DIR=/opt/bitnami/discourse/config
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=www.example.com
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
  sidekiq:
    image: docker.io/bitnami/discourse:latest
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=www.example.com
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

### What is the expected behavior?

These two lines will move `site_settings.yml` to the correct folder and allow the container + migrations to successfully run. 

```yml
...
volumes:
- ${PWD}/default_settings.yml:/opt/bitnami/discourse/mounted-conf/site_settings.yml

and

...
environment:
- DISCOURSE_CONF_DIR=/opt/bitnami/discourse/config
```

### What do you see instead?

Upon this step, the container exists and fails silently.

```
discourse 22:40:14.96 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.

discourse 22:40:14.97 INFO  ==> Detected mounted configuration files, copying to Discourse config directory

discourse 22:40:14.98 INFO  ==> Creating Discourse configuration file

discourse 22:40:15.04 INFO  ==> Restoring persisted Discourse installation

discourse 22:40:15.18 INFO  ==> Trying to connect to the database server

discourse 22:40:15.20 INFO  ==> Running database migrations
```

### Additional information

I've verified that I CAN copy the `site_settings.yml` into `opt/bitnami/discourse/config` if I change the name of the file, but the moment I try to replace the initial config, the container fails silently.
