### ISSUE TITLE
Cannot send email (smtp_domain stays at example.com)

### ISSUE THREAD

**Issue by flesser** [bitnami/bitnami-docker-discourse#31]
**Description**

In my `docker-compose.yml`, I have set `SMTP_HOST: smtp.MYDOMAIN.de`.
(I also changed the default Postgresql username and password)

After `docker-compose up`, Discourse runs, but cannot send any email.

`/opt/bitnami/discourse/conf/discourse.conf` inside the running container looks like this:
```yml
  db_name = discourse
  db_host = postgresql
  db_port = 5432
  db_password = PASSWORD
  db_username = discourse
  db_pool = 25
  redis_port = 6379
  redis_host = redis
  redis_password = 
  smtp_address = smtp.MYDOMAIN.de
    smtp_port = 587
    smtp_domain = example.com
    smtp_user_name = discourse@MYDOMAIN.de
    smtp_password =  PASSWORD
    smtp_enable_start_tls = true
    smtp_authentication = login
```
Two things I noticed:
* the indentation looks strange
*  `smtp_address` is set correctly to the domain I configured in docker-compose, but `smtp_domain` is still hardcoded to example.com

Is this intended? I would expect that this paramter is also configurable via the `docker-compose.yml`

**Comment by dbarranco** [comment]
Hi @flesser 

I just checked our daily tests of SMTP and they're working fine. Anyway, I added the env vars for the docker-compose to enable SMTP and this is how it looks like:

```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    volumes:
      - 'postgresql_data:/bitnami'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse:1'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=testsmtp@gmail.com
      - SMTP_PASSWORD=PASSWORD
      - SMTP_TLS=true
  sidekiq:
    image: 'bitnami/discourse:1'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

Then I launched the container and in the settings of SMTP the email is correctly configured and a test email was successfully sent. 
Could you share here your configuration? Please, hide any password or sensitive data that is present in your docker-compose file.

Kind regards.
