### ISSUE TITLE
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis'

### ISSUE THREAD

**Issue by rene-gomez** [bitnami/bitnami-docker-discourse#42]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
create docker-compose.yml
2. [Second Step]
docker-compose up
3. [and so on...]
the console Says: "Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis'"

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

- Output of `docker info`:

```
Containers: 26
 Running: 26
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 154
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 5.827GiB
Name: docker
ID: 4B6I:L3ET:6WWL:MFHG:R6Q7:O7FL:4YYV:233Y:FJQY:M3U7:UR5Y:QAZA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Dokcer-compose File

version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:9.6'
    volumes:
      - './postgresql_data:/bitnami'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - './discourse_data:/bitnami'
    environment:
      - DISCOURSE_EMAIL=email@gmail.com
      - DISCOURSE_HOSTNAME=forum.domain.com
      - DISCOURSE_SITENAME=forum.domain.com
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_DOMAIN=gmail.com
      - SMTP_USER=email@gmail.com
      - SMTP_PASSWORD=S3rv3r123
  sidekiq:
    image: 'bitnami/discourse:latest'
    depends_on:
      - discourse
    volumes:
      - './sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local

**Comment by rvalle** [comment]
same issue here, did you get it to work?

**Comment by rvalle** [comment]
In my case seems to be a permission issue when I define a volume with the local driver in another device. Maybe is un related to this image in particular, but more a docker misconfig.

**Comment by javsalgar** [comment]
This has to do with the use of non-root containers (the case of redis) and mounting local folders from your filesystem. In this link, you can see a solution (it is for MariaDB but applicable to your case): https://github.com/bitnami/bitnami-docker-mariadb/issues/136#issuecomment-354644226

**Comment by rvalle** [comment]
@javsalgar that is an interesting way of patching... will investigate further.
I have two major issues before I can use this container.

**Comment by javsalgar** [comment]
Hi, 
We are aware of the issues you mentioned in other posts. Stay tuned as we will update them ;)

**Comment by rene-gomez** [comment]
hi @javsalgar the problem persist on 2.0.3 release

how do you fix the problem, do you have an procedure?

best regards.

**Comment by beltran-rubo** [comment]
@rene-gomez could you remove the existing volumes and try again?

**Comment by rene-gomez** [comment]
Hi @beltran-rubo  this my result:

llocal@example:/var/www/site/forum$ docker system prune
WARNING! This will remove:
        - all stopped containers
        - all volumes not used by at least one container
        - all networks not used by at least one container
        - all dangling images
Are you sure you want to continue? [y/N] y
Deleted Containers:
44e6e183214b193966de7c35580a9905e3d917ac518783056dfe8ac7ad7cb651
52e899c2a516d46463bf5a66cba0ae78feeda1cfca947b47e8a9be3e0078d25b

Deleted Volumes:
forum_postgresql_data
forum_sidekiq_data
forum_discourse_data
forum_redis_data

Total reclaimed space: 85.42kB


**When i saw the logs the console say:**

postgresql_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/postgresql'

redis_1       | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis'

**Comment by rene-gomez** [comment]
llocal@example:/var/www/site/forum$ docker system prune
WARNING! This will remove:
        - all stopped containers
        - all volumes not used by at least one container
        - all networks not used by at least one container
        - all dangling images
Are you sure you want to continue? [y/N] y
Deleted Containers:
44e6e183214b193966de7c35580a9905e3d917ac518783056dfe8ac7ad7cb651
52e899c2a516d46463bf5a66cba0ae78feeda1cfca947b47e8a9be3e0078d25b

Deleted Volumes:
forum_postgresql_data
forum_sidekiq_data
forum_discourse_data
forum_redis_data

Total reclaimed space: 85.42kB


When i saw the logs the console say:


postgresql_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/postgresql'


redis_1       | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis'

**Comment by beltran-rubo** [comment]
the volume names uses the folder name by default. It seems the 1_postgresql_data or 1_redis_data where not deleted. Try to remove all your volumes with this command:

```
docker volume rm $(docker volume ls)
```

**Comment by rene-gomez** [comment]
@beltran-rubo your response is not good, because i have different containers running in the same host.

Please leave a effective and persistent fix

best regards

**Comment by beltran-rubo** [comment]
In that case, could you please list the volumes in your host and remove the specific ones for the Bitnami Discourse solution?

**Comment by rene-gomez** [comment]
Hi @beltran-rubo 

Yes, with the docker system prune you remove all volumes not used by at least one container, if remove the containers automatically the forum volumes are deleted, you see the result in my last response.

Do you say that docker system prune don't remove the volumes completely? 

Best regards

**Comment by beltran-rubo** [comment]
it is weird the name of the containers are "redis_1" but the name of the volumes are "forum_". Another way to remove the volumes is using "docker-compose down". Could you try that?

**Comment by rene-gomez** [comment]
Hi @beltran-rubo the name of the real containers is different, only mask the name with differents "names", after deleted all volumes, and run the docker-compose the problem persist.g

> Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis

**Comment by rene-gomez** [comment]
Hi @beltran-rubo the name of the real containers is different, only mask the name with differents "names", after deleted all volumes, and run the docker-compose the problem persist.g

`Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis`

please paste my conf file and try over the docker images not over their develop VM.

best regards

**Comment by rene-gomez** [comment]
This is my YML File:
```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:9.6'
    volumes:
      - './postgresql_data:/bitnami'
  redis:
    image: 'bitnami/redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse'
    labels:
      kompose.service.type: nodeport
    ports:
      - '3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - './discourse_data:/bitnami'
    environment:
      - DISCOURSE_EMAIL=email@gmail.com
      - DISCOURSE_HOSTNAME=forum.anysite.com
      - DISCOURSE_SITENAME=forum.anysite.com
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_DOMAIN=forum.anysite.com
      - SMTP_USER=email@gmail.com
      - SMTP_PASSWORD=password
  sidekiq:
    image: 'bitnami/discourse'
    depends_on:
      - discourse
    volumes:
      - './sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=email@gmail.com
      - SMTP_PASSWORD=password
      - DISCOURSE_HOSTNAME=forum.anysite.com
      - HOSTNAME=forum.anysite.com
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local

```

``
Running docker compose down for delete the containers
```
user@server:/var/www/forum.anysite.com$ docker-compose down
Stopping forum_sidekiq_1 ... done
Stopping forum_discourse_1 ... done
Removing forum_sidekiq_1 ... done
Removing forum_discourse_1 ... done
Removing forum_postgresql_1 ... done
Removing forum_redis_1 ... done
```
Destroying the volumes:

```
user@server:/var/www/forum.anysite.com$ docker system prune
WARNING! This will remove:
        - all stopped containers
        - all volumes not used by at least one container
        - all networks not used by at least one container
        - all dangling images
Are you sure you want to continue? [y/N] y
Deleted Volumes:
forum_postgresql_data
forum_sidekiq_data
forum_discourse_data
forum_redis_data

```

Startup the containers

`docker-compose up -d && docker-compose logs -f`

The latest logs:
```

postgresql_1  | postgre INFO  ==> Deploying PostgreSQL from scratch...
postgresql_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/postgresql'
forum_postgresql_1 exited with code 1
sidekiq_1     | nami    INFO  Initializing discourse-sidekiq
redis_1       | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis'
forum_redis_1 exited with code 1

```

**Comment by beltran-rubo** [comment]
Hi @rene-gomez 

It seems in your system the non-root containers are not allowed to run actions in the volumes. A possible workaround is to perform the permissions changes in a separate container. See the suggestion at https://github.com/bitnami/bitnami-docker-mariadb/issues/136#issuecomment-354644226 You can apply the same approach for the Redis & PostgreSQL volumes.

I hope it helps.

**Comment by bhardin** [comment]
@beltran-rubo I could not get the suggested approach to work in Rancher. It seems the container which should fix the permissions doesn't work. It just keeps restarting.

To fix, I changed the redis and postgresql containers to be root.

```
  redis:
    image: bitnami/redis:latest
    user: root
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
    - redis_data:/bitnami
  postgresql:
    image: bitnami/postgresql:9.6
    user: root
    volumes:
      - postgresql_data:/bitnami
```
