### ISSUE TITLE
Issues integrating with bitnami-docker-postgresql

### ISSUE THREAD

**Issue by j4p3** [bitnami/bitnami-docker-discourse#43]
**Description**

Following "How to use this image" instructions results in failed startup due to postgres users not being created.

This container expects both a postgres root user/password and a regular db user/password to be created in advance. However, the [bitnami-docker-postgresql](https://github.com/bitnami/bitnami-docker-postgresql) container can only create one of these users on startup. [Per its documentation](https://github.com/bitnami/bitnami-docker-postgresql#creating-a-database-user-on-first-run) , creating a custom user prevents the `postgres` user from being assigned a password.

I've tried using other `postgres` images that allow user creation alongside `postgres` password setup, instead of bitnami's version of postgres, but I've encountered other issues and would prefer to stay as close to your recommended configuration as possible.

**Steps to reproduce the issue:**

1. Create `docker-compose` file to match setup instructions. The file I'm using:

```
version: '3.2'
services:
  discourse:
    image: 'bitnami/discourse:latest'
    ports:
      - '80:3000'
    volumes:
      - 'discourse_data:/bitnami'
    depends_on:
      - 'postgresql'
      - 'redis'
    env_file:
      - '.env.docker'
  sidekiq:
    image: 'bitnami/discourse:latest'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    env_file:
      - '.env.docker'
  redis:
    image: 'redis:alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
    image: 'bitnami/postgresql:9.6'
    volumes:
      - 'postgresql_data:/bitnami'
    environment:
      - POSTGRESQL_DATABASE
      - POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD
volumes:
  client_assets:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

2. Set environment as necessary from the referenced `.env.docker` file by running `export $(cat .env.docker | xargs)`:
```
# bitnami-docker-postgres config
POSTGRESQL_DATABASE=discourse_my_app
POSTGRESQL_USERNAME=my_app
POSTGRESQL_PASSWORD=my_app

# bitnami-docker-discourse config
DISCOURSE_USERNAME=discourse_my_app
DISCOURSE_PASSWORD=discourse_my_app
DISCOURSE_EMAIL=my_email@email.com
DISCOURSE_SITENAME=my_app
POSTGRESQL_HOST=postgresql
POSTGRESQL_PORT_NUMBER=5432
POSTGRESQL_ROOT_USER=postgres
DISCOURSE_POSTGRESQL_USERNAME=my_app
DISCOURSE_POSTGRESQL_PASSWORD=my_app
DISCOURSE_POSTGRESQL_NAME=discourse_my_app

# bitnami-docker-discourse config for sidekiq
DISCOURSE_HOST=discourse
DISCOURSE_PORT=3000
```

3. run `docker-compose up`.

**Describe the results you received:**

Without a `postgres` password set in advance, discourse startup will fail with error

`psql: fe_sendauth: no password supplied`.

Without a custom database user+password set in advance, discourse startup will fail due to being unable to connect to posgres with error:

`psql: FATAL:  password authentication failed for user "my_app"` (or, when `DISCOURSE_POSTGRESQL_USERNAME` is unset, the error will be thrown with the default username `bn_discourse`.

**Describe the results you expected:**

I expect the `bitnami-docker-discourse`, given valid root `postgres` user credentials, to create the necessary database, database user, and permissions if they do not exist.

Without this behavior, it seems that it will be necessary to insert a manual step somewhere - using the `psql` shell to create the necessary user - or extending the `bitnami-docker-discourse` image to create the required user after settings its `postgres` user password. This is fine for development, but manual steps won't work in production.

**Version**

- Output of `docker version`:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

- Output of `docker info`:

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 32
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 3JJZ:CLED:NUWQ:F4RY:EGQJ:XLNX:DULK:AWV6:PJOY:WYHZ:R2VU:7ZSI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 42
 System Time: 2018-04-30T22:26:11.8688089Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Host machine: OSX El Capitan 10.11.6
Running via Docker for Mac application.
