### ISSUE TITLE
Mail not sending

### ISSUE THREAD

**Issue by Southclaws** [bitnami/bitnami-docker-discourse#53]
**Description**

First of all, thanks for such a useful image! The official discourse docker solution isn't the best and this one is far more idiomatic.

I'm having trouble getting mail to send, now I'm not sure if this is a problem with Discourse, this image specifically, the mail server or the configuration. I've asked in the discourse forum but since it's a "non standard" installation, they won't help so I thought I'd try my luck here!

When I hit "test email" I get a success message but no mail is ever sent, I'm using Elasticemail and the log shows no new mail.

**Steps to reproduce the issue:**

Here's my docker-compose file, `DOMAIN-NAME.com` is my project's domain, some use the `forum.` subdomain. Everything else is a variable which you can fill with the following .env:

```env
DATA_DIR=./data
DISCOURSE_PG_PASS=defaultpassword
DISCOURSE_PG_ROOT_PASS=defaultpassword
DISCOURSE_REDIS_PASS=defaultpassword
DISCOURSE_ROOT_PASS=defaultpassword
DISCOURSE_SMTP_PASS=defaultpassword
```

-

```yaml
version: "3.5"

networks:
  default:
    external:
      name: gateway
  databases:
    driver: bridge
    internal: true

services:
  postgresql:
    image: "bitnami/postgresql:latest"
    restart: on-failure
    environment:
      POSTGRESQL_PASSWORD: ${DISCOURSE_PG_ROOT_PASS}
      POSTGRESQL_DATABASE: discourse
    volumes:
      - "${DATA_DIR}/openmp/postgresql:/bitnami"
    networks:
      - databases
    labels:
      - traefik.enable=false

  redis:
    image: "bitnami/redis:latest"
    restart: on-failure
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      DISABLE_COMMANDS: "FLUSHDB,FLUSHALL,CONFIG"
      REDIS_HOST: redis # Hostname for Redis.
      REDIS_PORT_NUMBER: "6379" # Port used by Redis.
      REDIS_PASSWORD: ${DISCOURSE_REDIS_PASS} # Password for Redis.
    volumes:
      - "${DATA_DIR}/openmp/redis:/bitnami"
    networks:
      - databases
    labels:
      - traefik.enable=false

  sidekiq:
    image: "bitnami/discourse:2.0.5"
    command: "nami start --foreground discourse-sidekiq"
    restart: on-failure
    environment:
      POSTGRESQL_ROOT_USER: postgres # Root user for the Postgresql database.
      POSTGRESQL_ROOT_PASSWORD: ${DISCOURSE_PG_ROOT_PASS} # Root password for Postgresql.
      POSTGRESQL_HOST: postgresql # Hostname for Postgresql server.
      POSTGRESQL_PORT_NUMBER: "5432" # Port used by Postgresql server.
      DISCOURSE_POSTGRESQL_USERNAME: postgres # Discourse application database user. bn_discourse
      DISCOURSE_POSTGRESQL_PASSWORD: ${DISCOURSE_PG_ROOT_PASS} # Discourse application database password. bitnami1
      DISCOURSE_POSTGRESQL_NAME: discourse # Discourse application database name. bitnami_application
      DISCOURSE_HOST: discourse
      DISCOURSE_PORT: 3000
      DISCOURSE_HOSTNAME: DOMAIN.COM
      REDIS_HOST: redis # Hostname for Redis.
      REDIS_PORT_NUMBER: "6379" # Port used by Redis.
      REDIS_PASSWORD: ${DISCOURSE_REDIS_PASS} # Password for Redis.
      SMTP_HOST: smtp.elasticemail.com # Host for outgoing SMTP email.
      SMTP_PORT: "2525" # Port for outgoing SMTP email.
      SMTP_USER: ... # User of SMTP used for authentication (likely email).
      SMTP_PASSWORD: ${DISCOURSE_SMTP_PASS} # Password for SMTP.
      SMTP_TLS: "true" # Whether use TLS protocol for SMTP or not.
    volumes:
      - "${DATA_DIR}/openmp/sidekiq:/bitnami"
    networks:
      - databases
    depends_on:
      - discourse
    labels:
      - traefik.enable=false

  discourse:
    image: "bitnami/discourse:2.0.5"
    restart: on-failure
    environment:
      DISCOURSE_USERNAME: root # Discourse application username.
      DISCOURSE_PASSWORD: ${DISCOURSE_ROOT_PASS} # Discourse application password.
      DISCOURSE_EMAIL: admin@DOMAIN.COM # Discourse application email.
      DISCOURSE_SITENAME: Burger Shot # Discourse site name.
      DISCOURSE_HOSTNAME: DOMAIN.COM # Discourse hostname to create application URLs for features such as email notifications and emojis. It can be either an IP or a domain.
      POSTGRESQL_ROOT_USER: postgres # Root user for the Postgresql database.
      POSTGRESQL_ROOT_PASSWORD: ${DISCOURSE_PG_ROOT_PASS} # Root password for Postgresql.
      POSTGRESQL_HOST: postgresql # Hostname for Postgresql server.
      POSTGRESQL_PORT_NUMBER: "5432" # Port used by Postgresql server.
      DISCOURSE_POSTGRESQL_USERNAME: postgres # Discourse application database user. bn_discourse
      DISCOURSE_POSTGRESQL_PASSWORD: ${DISCOURSE_PG_ROOT_PASS} # Discourse application database password. bitnami1
      DISCOURSE_POSTGRESQL_NAME: discourse # Discourse application database name. bitnami_application
      # POSTGRESQL_CLIENT_CREATE_DATABASE_NAME: discourse # unknown...
      # POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME: discourse # unknown...
      # POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD: ${DISCOURSE_PG_PASS} # unknown...
      REDIS_HOST: redis # Hostname for Redis.
      REDIS_PORT_NUMBER: "6379" # Port used by Redis.
      REDIS_PASSWORD: ${DISCOURSE_REDIS_PASS} # Password for Redis.
      SMTP_HOST: smtp.elasticemail.com # Host for outgoing SMTP email.
      SMTP_PORT: "2525" # Port for outgoing SMTP email.
      SMTP_USER: ... # User of SMTP used for authentication (likely email).
      SMTP_PASSWORD: ${DISCOURSE_SMTP_PASS} # Password for SMTP.
      SMTP_TLS: "true" # Whether use TLS protocol for SMTP or not.
    volumes:
      - "${DATA_DIR}/openmp/discourse:/bitnami"
    networks:
      - default
      - databases
    depends_on:
      - postgresql
      - redis
    # ports:
    #   - 80:3000
    labels:
      - traefik.docker.network=gateway
      - "traefik.frontend.rule=Host:DOMAIN.COM"
      - traefik.frontend.headers.SSLRedirect=false
      - traefik.port=3000
```

**Describe the results you received:**

No error messages, just silent failure. No mail sent and no mail on the Elasticemail log.

**Describe the results you expected:**

I have another instance of discourse running (using their installation method) and it works fine in terms of mail, but this one has the exact same config and it won't work. I thought there was only one set of email config params but I'm not so sure now.

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
 Kubernetes:
  Version:          v1.10.3
  StackAPI:         v1beta2
```

- Output of `docker info`:

```
Containers: 39
 Running: 27
 Paused: 0
 Stopped: 12
Images: 83
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: SIKK:Z6SF:ZIGU:KH3Y:XYCP:43YE:7BHO:ICSQ:YSH2:VAYP:MVHR:K24M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 212
 Goroutines: 219
 System Time: 2018-09-05T08:24:35.5563425Z
 EventsListeners: 3
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```
