### ISSUE TITLE
Letter avatars and Gravatars not working

### ISSUE THREAD

**Issue by bkraul** [bitnami/bitnami-docker-discourse#57]
**Description**

Did a fresh docker-compose install of bitnami/discourse (See my docker-compose below). The only difference is that I am using alternate redis and postgres which to the best of my knowledge are operating as expected. Sidekiq reports it's working. But I am not seeing letter avatars or Gravatars show up. This is what the log is telling me:

```
Failed to process hijacked response correctly : /opt/bitnami/discourse/lib/letter_avatar.rb:85:in `generate_fullsize': convert-im6.q16: unable to read font `Helvetica' @ error/annotate.c/RenderFreetyp
----
/opt/bitnami/discourse/lib/discourse.rb:28:in `execute_command'
/opt/bitnami/discourse/lib/letter_avatar.rb:85:in `generate_fullsize'
/opt/bitnami/discourse/lib/letter_avatar.rb:46:in `block in generate'
/opt/bitnami/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:5:in `synchronize'
/opt/bitnami/discourse/lib/letter_avatar.rb:34:in `generate'
/opt/bitnami/discourse/app/controllers/user_avatars_controller.rb:51:in `block in show_proxy_letter'
/opt/bitnami/discourse/lib/hijack.rb:56:in `instance_eval'
/opt/bitnami/discourse/lib/hijack.rb:56:in `block in hijack'
/opt/bitnami/discourse/lib/scheduler/defer.rb:70:in `block in do_work'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rails_multisite-2.0.4/lib/rails_multisite/connection_management.rb:63:in `with_connection'
/opt/bitnami/discourse/lib/scheduler/defer.rb:68:in `do_work'
/opt/bitnami/discourse/lib/scheduler/defer.rb:59:in `block (2 levels) in start_thread'
```

**My docker-compose.yml**
```yaml
version: '3.2'
services:
  postgresql:
    image: postgres:alpine
    restart: always
    volumes:
      - /root/docker-persist/discourse/postgresql/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=--data-checksums --locale=en_US
    networks:
      - default
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - discourse_redis:/data
    sysctls:
      - net.core.somaxconn=511
    networks:
      - default
  discourse:
    image: bitnami/discourse:latest
    restart: always
    volumes:
      - /root/docker-persist/discourse:/bitnami
    environment:
      - VIRTUAL_HOST=discourse.belmankraul.com
      - VIRTUAL_PORT=3000
      - DISCOURSE_USERNAME=admin
      - DISCOURSE_PASSWORD=******
      - DISCOURSE_EMAIL=[my discourse email]
      - DISCOURSE_SITENAME=bkraul
      - DISCOURSE_HOSTNAME=discourse.belmankraul.com
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=******
      - DISCOURSE_POSTGRESQL_NAME=discourse
      - DISCOURSE_POSTGRESQL_USERNAME=discourse
      - DISCOURSE_POSTGRESQL_PASSWORD==******
      - SMTP_HOST=[my mail host]
      - SMTP_PORT=587
      - SMTP_USER=[my mail user]
      - SMTP_PASSWORD=******
    depends_on:
      - postgresql
      - redis
    networks:
      - reverse-proxy
      - default
  sidekiq:
    image: bitnami/discourse:latest
    restart: always
    volumes:
      - /root/docker-persist/discourse:/bitnami
    environment:
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_POSTGRESQL_NAME=discourse
      - DISCOURSE_POSTGRESQL_USERNAME=discourse
      - DISCOURSE_POSTGRESQL_PASSWORD==******
      - DISCOURSE_SITENAME=bkraul
      - DISCOURSE_HOSTNAME=discourse.belmankraul.com
      - SMTP_HOST=[my mail host]
      - SMTP_PORT=587
      - SMTP_USER=[my mail user]
      - SMTP_PASSWORD==******
    command: 'nami start --foreground discourse-sidekiq'
    depends_on:
      - discourse
    networks:
      - default
volumes:
  discourse_redis:
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
```

**Steps to reproduce the issue:**

1. Install bitnami/discourse with compose as shown
2. Log in with intial account

**Describe the results you received:**

There are no letter avatars for users, and creating a user that has an associated Gravatar account also does not show it:
![image](https://user-images.githubusercontent.com/14616851/47045967-b6903a00-d159-11e8-87e2-80c0934709e9.png)

**Describe the results you expected:**
Expected letter avatars and gravatars to work out of the box.

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 30
 Running: 30
 Paused: 0
 Stopped: 0
Images: 72
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-36-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.79GiB
Name: docker
ID: X777:P7YR:LILB:TJV4:YWAV:MBHI:MPIA:GSYV:MUJ2:5YLD:PJOU:K2MP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: bkraul
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
VMWare ESXi VM:
* 8GB RAM
* 4 VCPUs
* 60GB HD
