### ISSUE TITLE
/usr/sbin/sendmail is missing

### ISSUE THREAD

**Issue by Moskito99** [bitnami/bitnami-docker-discourse#58]
**Description**

**Steps to reproduce the issue:**

1. docker-compose up -d
2. send email for verification or wathever...

**Describe the results you received:**

Error in Logfile:
sidekiq_1      | 2018-11-06T22:02:12.593174878Z sh: 1: /usr/sbin/sendmail: not found

**Describe the results you expected:**

E-Mail send

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

- Output of `docker info`:

```
Containers: 61
 Running: 61
 Paused: 0
 Stopped: 0
Images: 369
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 984
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-134-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.55GiB
Name: zeus
ID: J7A3:RJVZ:K5G7:B7CT:WVKH:XH73:2XMH:WLDN:N5Z2:PPLD:32LI:26QT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.5.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Discourse behind nginx-proxy

My docker-compose file:
```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:9.6'
    volumes:
      - './data/postgresql:/bitnami'
    networks:
      default: 

  nginx-proxy:
    image: nginx:1.11.13
    environment:
      - VIRTUAL_HOST=www.########.de
      - LETSENCRYPT_HOST=www.########.de
      - LETSENCRYPT_EMAIL=#####@#####
    volumes:
      - /home/marcus/docker/etc_certs/:/etc/letsencrypt/certs/:ro
      - ./data/nginx/conf.d/:/etc/nginx/conf.d/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      default: 

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './data/redis:/bitnami'
    networks:
      default: 

  discourse:
    image: 'bitnami/discourse:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '3080:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - './data/discourse:/bitnami'
    networks:
      default: 
    environment:
      - DISCOURSE_USERNAME=admin
      - DISCOURSE_PASSWORD=########
      - DISCOURSE_HOSTNAME=www.#######.de
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=##########
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=###########
      - SMTP_HOST=mail.######.de
      - SMTP_PORT=587
      - SMTP_USER=forum@#####.de
      - SMTP_PASSWORD=######

  sidekiq:
    image: 'bitnami/discourse:latest'
    depends_on:
      - discourse
    volumes:
      - './data/sidekiq:/bitnami'
    networks:
      default:
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=########
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000

networks:
   default:

```

**Comment by javsalgar** [comment]
Hi,

I confirm that it is missing, but I did not get that error in sidekiq logs:

```
Sent mail to jsalmeron@bitnami.com (2931.3ms)
Sent mail to jsalmeron@bitnami.com (2749.6ms)
```

Did you change any configuration to use sendmail?

**Comment by Moskito99** [comment]
Hi @javsalgar , i didn't change anything in the container. I use the docker-composer file above and thought that it should work out of the box.

**Comment by Moskito99** [comment]
So, I deleted all containers and start from scratch.
Now I see the email config under configuration!
How can i change this settings, because there is still domain with example.com?

I think discourse package is far far away from usable. :-(

**Comment by javsalgar** [comment]
Could you confirm that the SMTP settings are in `/opt/bitnami/discourse/conf/discourse.conf`?

**Comment by Moskito99** [comment]
So, Istartet from scratch, once again...

My other issues are gone so far, but email sending is still not possible.

Here is my docker-composer.yml file:

```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:9.6'
    volumes:
      - './data/postgresql:/bitnami'
    networks:
      default: 

  nginx-proxy:
    image: nginx:1.11.13
    environment:
      - VIRTUAL_HOST=www.#####.de
      - LETSENCRYPT_HOST=www.#####.de
      - LETSENCRYPT_EMAIL=m####@####de
    volumes:
      - /home/marcus/docker/etc_certs/:/etc/letsencrypt/certs/:ro
      - ./data/nginx/conf.d/:/etc/nginx/conf.d/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      default: 

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './data/redis:/bitnami'
    networks:
      default: 

  discourse:
    image: 'bitnami/discourse:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '3080:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - './data/discourse:/bitnami'
    networks:
      default: 
    environment:
      - DISCOURSE_USERNAME=admin
      - DISCOURSE_PASSWORD=#######
      - DISCOURSE_HOSTNAME=www.######.de
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - SMTP_HOST=mail.#####.de
      - SMTP_PORT=465
      - SMTP_USER=forum@#####.de
      - SMTP_PASSWORD=######
      - SMTP_TLS=false
  sidekiq:
    image: 'bitnami/discourse:latest'
    depends_on:
      - discourse
    volumes:
      - './data/sidekiq:/bitnami'
    networks:
      default:
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=www.#####.de
      - SMTP_HOST=mail.####.de
      - SMTP_PORT=465
      - SMTP_USER=forum@#####.de
      - SMTP_PASSWORD=#####
      - SMTP_TLS=false

networks:
   default:

```

And now, the fun fact!
The discourse.conf file:

```
  db_name = bitnami_application
  db_host = postgresql
  db_port = 5432
  db_password = bitnami1
  db_username = bn_discourse
  db_pool = 25
  
  hostname = www.######.de
  redis_port = 6379
  redis_host = redis
  redis_password = 
  smtp_address = mail.####.de
    smtp_port = 465
    smtp_domain = example.com
    smtp_user_name = forum@######.de
    smtp_password =  ######
    smtp_enable_start_tls = true
    smtp_authentication = login
```

And NO the example.com Domain is not my Domain! ;-)
**smtp_domain** is not set, is there a hidden parameter somewhere?
**smtp_enable_start_tls** is also not set with the right parameter.
**smtp_authentication** is also missing as parameter for the docker-composer file

I think the smtp_domain is the same issue describped in the issue #56 

I tried different config in the discourse.conf but I can't get it to work.
I use my own Mailserver and normaly I connect via Port 465, login plain and ssl/tls
All clients, KMAIL/OUTLOOK/Andoid K9 Mail and so on have now problems with that...

Here are the maillog from mailserver..
```
Nov 12 22:57:09 mail postfix/smtpd[8119]: connect from v###################.megasrv.de[188.68.##.##]
Nov 12 22:58:09 mail postfix/smtpd[8119]: SSL_accept error from v###################.megasrv.de[188.68.##.##]: lost connection
Nov 12 22:58:09 mail postfix/smtpd[8119]: lost connection after CONNECT from v###################.megasrv.de[188.68.##.##]
Nov 12 22:58:09 mail postfix/smtpd[8119]: disconnect from v###################.megasrv.de[188.68.##.##]
```

What modul or script do you use for SMTP, or is it a discourse implementation?
