### ISSUE TITLE
Images are not shown after fresh install and setup

### ISSUE THREAD

**Issue by Moskito99** [bitnami/bitnami-docker-discourse#60]
**Description**

The images and emojis are not shown, because the links are still locatet at the www.example.com domain.

**Steps to reproduce the issue:**

1. docker-compose up -d
2. open discourse

**Describe the results you received:**

Error 404 on all images and emojis.

**Describe the results you expected:**

Images and emojis should show.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 61
 Running: 61
 Paused: 0
 Stopped: 0
Images: 266
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 893
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-134-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.55GiB
Name: zeus
ID: J7A3:RJVZ:K5G7:B7CT:WVKH:XH73:2XMH:WLDN:N5Z2:PPLD:32LI:26QT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.5.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:9.6'
    volumes:
      - './data/postgresql:/bitnami'
    networks:
      default: 

  nginx-proxy:
    image: nginx:1.11.13
    environment:
      - VIRTUAL_HOST=www.########.de
      - LETSENCRYPT_HOST=www.########.de
      - LETSENCRYPT_EMAIL=#####@#####
    volumes:
      - /home/marcus/docker/etc_certs/:/etc/letsencrypt/certs/:ro
      - ./data/nginx/conf.d/:/etc/nginx/conf.d/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      default: 

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './data/redis:/bitnami'
    networks:
      default: 

  discourse:
    image: 'bitnami/discourse:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '3080:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - './data/discourse:/bitnami'
    networks:
      default: 
    environment:
      - DISCOURSE_USERNAME=admin
      - DISCOURSE_PASSWORD=########
      - DISCOURSE_HOSTNAME=www.#######.de
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=##########
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=###########
      - SMTP_HOST=mail.######.de
      - SMTP_PORT=587
      - SMTP_USER=forum@#####.de
      - SMTP_PASSWORD=######

  sidekiq:
    image: 'bitnami/discourse:latest'
    depends_on:
      - discourse
    volumes:
      - './data/sidekiq:/bitnami'
    networks:
      default:
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=########
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000

networks:
   default:
```
