### ISSUE TITLE
Can not change the site name

### ISSUE THREAD

**Issue by mebibou** [bitnami/bitnami-docker-discourse#63]
**Description**

I'm trying to change the site name but it keeps saying **My Site !**

**Steps to reproduce the issue:**

My `docker-compose.yml`:
```yaml
version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:9.6'
    volumes:
      - 'postgresql_data:/bitnami'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '3003:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami'
    env_file:
      - ./.discourse-env
  sidekiq:
    image: 'bitnami/discourse:latest'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    env_file:
      - ./.discourse-env

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

My `.discourse-env` file:
```
DISCOURSE_HOSTNAME=localhost
DISCOURSE_SITENAME=My Awesome Website
DISCOURSE_USERNAME=user
DISCOURSE_PASSWORD=pwd
DISCOURSE_EMAIL=email
SMTP_HOST=...
SMTP_PORT=587
SMTP_USER=...
SMTP_PASSWORD=...
SMTP_TLS=true
DISCOURSE_HOST=discourse
DISCOURSE_PORT=3000
POSTGRESQL_HOST=postgresql
POSTGRESQL_ROOT_USER=postgres
POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
DISCOURSE_POSTGRESQL_NAME=bitnami_application
DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
```

**Describe the results you received:**

After doing `docker-compose up`, and going on http://localhost:3003/, still says "My Site!"

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Containers: 59
 Running: 3
 Paused: 0
 Stopped: 56
Images: 381
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: YBUW:KNQY:BJUR:QCWB:DRFB:EF77:FXAA:54PJ:F2T5:MGCF:HOHH:WLNQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 55
 Goroutines: 90
 System Time: 2018-11-30T12:04:51.2479978Z
 EventsListeners: 3
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```
