### ISSUE TITLE
Mails not sending after upgrade

### ISSUE THREAD

**Issue by mebibou** [bitnami/bitnami-docker-discourse#64]
**Description**

Just upgraded to the latest version, emails were being sent before but now when sending an email I have an error `There was a problem sending the test email. Please double-check your mail settings, verify that your host is not blocking mail connections, and try again.`

**Steps to reproduce the issue:**

1. Go to /admin/email
2. Enter email address and hit "Send Test Email"
3. Popup appears and show error "There was a problem sending the test email. Please double-check your mail settings, verify that your host is not blocking mail connections, and try again."

**Additional information you deem important (e.g. issue happens only occasionally):**

I tailed the logs to see what happens:
```bash
tail -f /opt/bitnami/discourse/log/production.log
```
And here is what was displayed when sending test email:
```
Processing by Admin::EmailController#test as */*
  Parameters: {"email_address"=>"email@test.com"}
Sent mail to email@test.com (1354.7ms)
Completed 422 Unprocessable Entity in 1397ms (Views: 0.4ms | ActiveRecord: 1.1ms)
```

My `docker-compose.yml`:
```yaml
version: '2'

services:
  postgresql:
    image: bitnami/postgresql:9.6
    restart: unless-stopped
    volumes:
      - postgresql_data:/bitnami
  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami
  discourse:
    image: bitnami/discourse:latest
    restart: unless-stopped
    labels:
      kompose.service.type: nodeport
    ports:
      - '3003:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - discourse_data:/bitnami
    env_file:
      - ./.discourse-env
  sidekiq:
    image: bitnami/discourse:latest
    restart: unless-stopped
    depends_on:
      - discourse
    volumes:
      - sidekiq_data:/bitnami
    command: 'nami start --foreground discourse-sidekiq'
    env_file:
      - ./.discourse-env

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 24
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-134-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.795GiB
Name: clearroad
ID: PDX5:BRCL:TSIW:7HLB:JJND:7SDV:KIQK:4FEO:CRY7:2T5H:N67R:WN5L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```
