### ISSUE TITLE
Log verbosity

### ISSUE THREAD

**Issue by heilerich** [bitnami/bitnami-docker-discourse#66]
Is there any way to increase the log verbosity of the setup process?
The initial start of my discourse container just freezes forever at the step shown in the log below, but it's very hard to track down the issue with the limited amount of information in this output.

```Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing postgresql-client
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
discour INFO  Configuring Discourse database...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql:5432
discour INFO  Enabling PostgreSQL plugins for Discourse...
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the application token...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Migrating database...
discour INFO  Creating the Discourse admin user...
```

**Comment by tompizmor** [comment]
Hello @heilerich,

You can add the environment variable `NAMI_LOG_LEVEL=trace8`.
Also, if you share your docker-compose file we can take a look at it and try to reproduce the issue.

**Comment by heilerich** [comment]
Thanks @tompizmor!
I did some more digging and I'm still stuck at the creating the admin user step. I noticed that ther is an error in the postgresql log relating to a users database. That might be just it, but I don't know discourse well enough to understand what's going on. Any help would be greatly appreciated.

```
2019-01-10 20:28:34.493 UTC [64] ERROR:  relation "users" does not exist at character 566
2019-01-10 20:28:34.493 UTC [64] STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
	                     c.collname, col_description(a.attrelid, a.attnum) AS comment
	                FROM pg_attribute a
	                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	                LEFT JOIN pg_type t ON a.atttypid = t.oid
	                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
	               WHERE a.attrelid = '"users"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum
```

**Comment by tompizmor** [comment]
@heilerich Can you share your docker-compose file? I would like to try to reproduce the issue on my side.

**Comment by heilerich** [comment]
Here it is
```
discourse:
    image: 'bitnami/discourse:latest'
    container_name: discourse
    expose:
      - 3000
    volumes:
      - '/data/discourse_data:/bitnami'
    links:
      - discourse-postgres:postgresql
      - redis
    environment:
        ## Set for nginx-proxy
        VIRTUAL_HOST: forums.example.com
        LETSENCRYPT_HOST: forums.example.com
        LETSENCRYPT_EMAIL: admin@example.com

        DISCOURSE_USERNAME: board-admin
        DISCOURSE_PASSWORD: ***
        DISCOURSE_EMAIL: admin@example.com
        DISCOURSE_SITENAME: Just some board
        DISCOURSE_HOSTNAME: forums.example.com

        SMTP_HOST: mail.example.com
        SMTP_PORT: 465
        SMTP_USER: mail-admin
        SMTP_PASSWORD: ***

        DISCOURSE_POSTGRESQL_PASSWORD: ***
        DISCOURSE_POSTGRESQL_USERNAME: postgres
        DISCOURSE_POSTGRESQL_NAME: postgres
        POSTGRESQL_ROOT_PASSWORD: ***

        NAMI_LOG_LEVEL: trace8

sidekiq:
    image: 'bitnami/discourse:latest'
    container_name: sidekiq
    links:
      - discourse
      - discourse-postgres:postgresql
    volumes:
      - '/data/sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
        SMTP_HOST: mail.example.com
        SMTP_PORT: 465
        SMTP_USER: mail-admin
        SMTP_PASSWORD: ***
```
