### ISSUE TITLE
Instructions in the readme don't work.

### ISSUE THREAD

**Issue by MicahZoltu** [bitnami/bitnami-docker-discourse#70]
Using the docker-compose file in the readme doesn't work.  The discord service fails to connect to postgres with:
```
postgre ERROR [canConnect] Connection with 'bn_discourse' user is unsuccessful
```

#43 mentions (though the Readme doesn't) that I need to set the following environment variables on the container:
```
POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=discourse_my_app
POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=my_app
POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=my_app
```
yet none of those environment variables are mentioned in the readme's list of available environment variables, suggesting that issue is out of date.

Ideally, the docker-compose file in the readme should "just work" or at least include instructions on what things are critical to set/change in order for it to work.  At the moment, the readme doesn't appear to even include the necessary information to get things started, none the less in a form that is obvious to the newbie.

**Comment by marcosbc** [comment]
Hi @MicahZoltu,

We're able to use the docker-compose.yml file just fine.

Note that the `docker-compose.yml` file in the root path of the repository is outdated, instead you should be using inside [2/debian-9](https://github.com/bitnami/bitnami-docker-discourse/tree/master/2/debian-9) or [2/ol-7](https://github.com/bitnami/bitnami-docker-discourse/tree/master/2/ol-7). We will look into removing these.

In any case both of them work for us. Could it be possible you have a built Docker image with the same tag/version than the ones used by the docker-compose.yml file?

**Comment by MicahZoltu** [comment]
Ah, I was using the docker-compose file in the root of this repository, not the ones buried 3 levels deep.  I recommend either updating the root `docker-compose.yml` file to be functional out-of-the-box, or deleting it.

Alternatively, update the readme to not reference the `docker-compose.yml` in the root and instead have it reference one of the nested ones.

**Comment by marcosbc** [comment]
Hi, actually the docker-compose.yml in the root directory works for us. In any case I've created an internal task for updating (or removing) the `docker-compose.yml` file in the root directory.

**Comment by marcosbc** [comment]
Nevermind, it seems it was fixed today in https://github.com/bitnami/bitnami-docker-discourse/commit/0944149968af606d40c6384bef57d4e8cfb46071. Closing this issue as it has been resolved.

**Comment by ggeo1992** [comment]
Hello,

I am having issues getting the required postgresql DB and user for the discourse app created on the postgre instane. I am trying to run discourse in a minikube cluster.
I am using minikube version 1.11.0, with driver=none on a Ubuntu 18.04.4 LTS system.
Below are my deployment.yaml files for both discourse and postgres:
1. Discourse:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discourse-apps-deployment
  labels:
    app: discourse-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discourse-apps
  template:
    metadata:
      labels:
        app: discourse-apps
    spec:
      containers:
      - name: discourse-apps
        image: docker.io/bitnami/discourse:2-debian-10
        ports:
        - containerPort: 3000
        env:
        - name: DISCOURSE_USERNAME
          value: "user"
        - name: DISCOURSE_PASSWORD
          value: "bitnami123"
        - name: DISCOURSE_EMAIL
          value: "user@example.com"
        - name: DISCOURSE_SITENAME
          value: "My site!"
        - name: DISCOURSE_HOSTNAME
          value: web-server
        - name: NAMI_DEBUG
          value: "3"
        - name: POSTGRESQL_ROOT_USER
          value: "postgres"
        #- name: POSTGRESQL_ROOT_PASSWORD
        #  valueFrom:
        #    secretKeyRef:
        #      name: pgsql-secret
        #      key: dbRootPassword
        - name: POSTGRESQL_HOST
          value: pgsql
        - name: POSTGRESQL_PORT_NUMBER
          value: "5432"
        - name: DISCOURSE_POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_USERNAME
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_USERNAME
        - name: DISCOURSE_POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_PASSWORD
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_PASSWORD
        - name: DISCOURSE_POSTGRESQL_NAME
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_DB_NAME
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DISCOURSE_POSTGRESQL_DB_NAME
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT_NUMBER
          value: "6379"
#        - name: REDIS_PASSWORD
#          value: "<enter-password-here>"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: STMP_PORT
          value: "587"
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: smtpPassword
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: smtpUsername
        volumeMounts:
          - name: discourse-data
            mountPath: /bitnami
      volumes:
      - name: discourse-data
        persistentVolumeClaim:
          claimName: discourse-pv-claim
```
Postgres:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pgsql-server
  template:
    metadata:
      labels:
        app: pgsql-server
    spec:
      containers:
        - name: pgsql-server
          image: docker.io/bitnami/postgresql:11-debian-10
          ports:
          - containerPort: 5432
          volumeMounts:
            - name: pgsql-storage
              mountPath: /bitnami/postgresql
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: NAMI_LOG_LEVEL
              value: "trace"
            #- name: POSTGRES_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: pgsql-secret
            #      key: dbRootPassword

      volumes:
      - name: pgsql-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
```

Logs i get in discourse are:
```
nami    INFO  Initializing postgresql-client
postgre DEBUG Waiting for service at pgsql:5432...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at pgsql:5432
postgre TRACE [canConnect] Testing connection with 'postgres' user
postgre TRACE [showDatabases] Getting databases for 'postgres' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dpostgres,-Upostgres,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n bitnami_application\n template1\n template0\n\n"
postgre TRACE [canConnect] Connection with 'postgres' user is successful
postgre INFO  PostgreSQL server listening and working at pgsql:5432
postgre TRACE [canConnect] Testing connection with 'discourseUser
' user
postgre TRACE [showDatabases] Getting databases for 'discourseUser
' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dpostgres,-UdiscourseUser
,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n bitnami_application\n template1\n template0\n\n"
postgre TRACE [canConnect] Connection with 'discourseUser
' user is successful
postgre TRACE [existsDatabase] Checking database existance for 'postgres' user
postgre TRACE [showDatabases] Getting databases for 'postgres' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dpostgres,-Upostgres,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n bitnami_application\n template1\n template0\n\n"
postgre TRACE [existsDatabase] Checking database existance for 'discourseUser
' user
postgre TRACE [showDatabases] Getting databases for 'discourseUser
' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dpostgres,-UdiscourseUser
,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n bitnami_application\n template1\n template0\n\n"
postgre DEBUG Reusing database and credentials
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
discour DEBUG Creating Discourse system user...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at pgsql:5432
postgre TRACE [canConnect] Testing connection with 'discourseUser
' user
postgre TRACE [showDatabases] Getting databases for 'discourseUser
' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dbitnami_application
,-UdiscourseUser
,-cSELECT datname FROM pg_database;
postgre ERROR [canConnect] Connection with 'discourseUser
' user is unsuccessful
postgre DEBUG Cannot connect to PostgreSQL server. Retrying in 5 seconds...
postgre TRACE [canConnect] Testing connection with 'discourseUser
' user
postgre TRACE [showDatabases] Getting databases for 'discourseUser
' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dbitnami_application
,-UdiscourseUser
,-cSELECT datname FROM pg_database;
postgre ERROR [canConnect] Connection with 'discourseUser
' user is unsuccessful
postgre DEBUG Cannot connect to PostgreSQL server. Retrying in 5 seconds...
postgre TRACE [canConnect] Testing connection with 'discourseUser
' user
postgre TRACE [showDatabases] Getting databases for 'discourseUser
' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpgsql,-dbitnami_application
,-UdiscourseUser
,-cSELECT datname FROM pg_database;
postgre ERROR [canConnect] Connection with 'discourseUser
' user is unsuccessful
postgre DEBUG Cannot connect to PostgreSQL server. Retrying in 5 seconds...
```

It seems that the sql client is not properly creating the discourse DB and USER. Although, if i connect to my postgre instance i can see the database being created. Also I see a login role named as the value of DISCOURSE_POSTGRESQL_USERNAME from the discourse deployment.
Any ideas what is wrong? I used the versions used in the README page.

Appreciate your help,
George
