### ISSUE TITLE
Port is incorrectly included in hostname in some links.

### ISSUE THREAD

**Issue by MicahZoltu** [bitnami/bitnami-docker-discourse#73]
**Description**
Some links, such as to the font awesome SVG and user avatars are getting the public port included in the URL, thus causing the URL to become invalid.

**Steps to reproduce the issue:**

1. Create a docker compose file from the README template.
2. Set necessary environment variables.
3. Navigate to your hostname.

**Describe the results you received:**
Notice in the network tab of your browser a 404 when trying to load
```
https://my.host/svg-sprite/my.host:443/svg-c56d032cd8fc8d716dbffc98b898457ec945837d.js
```
Note the extra `:443` in the middle of that path of that URL.  Without the `:443` the URL correctly resolves.

**Describe the results you expected:**

The URLs for links to assets to be valid.

**Additional information you deem important (e.g. issue happens only occasionally):**

I think the port is set to whatever I have `DISCOURSE_EXTERNAL_PORT_NUMBER` environment variable set to.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker Swarm (though I don't think this matters)

**Comment by marcosbc** [comment]
You are right about this. We have seen this issue recently when updating to the latest release of the Bitnami Discourse container, 2.2.1. It only affects port 443 though, port 80 should work.

We're working on having it released, if everything goes fine it should be out in a couple of hours.

**Comment by marcosbc** [comment]
Hi @MicahZoltu, Discourse was released with the change. Could you try and confirm it works properly now?

**Comment by MicahZoltu** [comment]
Feel free to ping me again when it is ready and I can give it a try.  I'm eager to get my Discourse server up, but this is a blocker at the moment.

**Comment by marcosbc** [comment]
Hi @MicahZoltu, the issue should have been fixed for good now. Please confirm it also works on your side after updating the image.

Thanks!

**Comment by MicahZoltu** [comment]
This appears to have resolved the issue for me.  Thanks!

**Comment by marcosbc** [comment]
Awesome, thanks for letting us know!

**Comment by yod527** [comment]
Hello! I've met exactly the same issue running discourse on some other port rather then 80 and 443. If you need to run on port, say 8822 you'll get this issue again. Running bitnami image with hash 18aa20abab97. Maybe someone has any suggestions?

**Comment by marcosbc** [comment]
Hi @yod527, it works fine for us with version `2.2.4-debian-9-r7` of the container, which uses the hash `18aa20abab97`.

Note that our docker-compose contains the following:

```
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=443
      - DISCOURSE_HOSTNAME=www.example.com
``` 

Then, in `discourse.conf` we see the following:

```
hostname = www.example.com
```

Indicating it is well configured.

**Comment by opensorceror** [comment]
@marcosbc I can confirm that I have the same issue as @yod527 , both in version `latest` and in version  `2.2.4-debian-9-r7`. The issue is caused by the `DISCOURSE_EXTERNAL_PORT_NUMBER ` variable as @MicahZoltu said, especially when using a port number other than 80 and 443, like @yod527 said. 

Here is my docker-compose:
```yaml
discourse:
    image: 'bitnami/discourse:2.2.4-debian-9-r7'
    volumes:
      - '/data/discourse/discourse-data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=localhost
      - DISCOURSE_EXTERNAL_PORT_NUMBER=25000
    depends_on:
      - postgresql
      - redis
```

The error message I see in my browser is:
```
 HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://localhost:25000/svg-sprite/localhost:25000/svg-c56d032cd8fc8d716dbffc98b898457ec945837d.js
```
The `/svg-sprite/localhost:25000/...` portion of the URI should actually be `/svg-sprite/localhost/...`. 

This prevents certain icons from loading, including the menu and search icons on the top right:

![image](https://user-images.githubusercontent.com/10184251/56429497-14304b00-6291-11e9-93c8-7100235fb438.png)

Everything works fine if I don't specify `DISCOURSE_EXTERNAL_PORT_NUMBER`, but in this case the application needs to be accessed on port 80. I'd like to use a different port instead.
