### ISSUE TITLE
How to serve discourse in a subfolder?

### ISSUE THREAD

**Issue by hebertdougl** [bitnami/bitnami-docker-discourse#76]
**Description**

I would like to know if it is possible to serve Discourse from a subfolder in my domain, like a http://example.com/forum.

According to the official forum (https://meta.discourse.org/t/subfolder-support-with-docker/30507) it is possible by adding the environment variable DISCOURSE_RELATIVE_URL_ROOT and with some nginx proxy changes.

Is this feature currently supported inside bitnami image?

**Image version**
```
bitnami/discourse:2.1.8
```

**Comment by javsalgar** [comment]
Hi,

I am afraid that this is not something that we currently support. Maybe using a container as a proxy may work, but I am not sure if the URLs generated by the application will work as they should (especially in Discourse javascripts). We will evaluate this feature in future releases, but as it is not a critical feature, we cannot guarantee an ETA, at least in the short or mid term.

**Comment by opensorceror** [comment]
It would be nice to have this functionality.

**Comment by javsalgar** [comment]
Thanks for the feedback @opensorceror. Did you try with a proxy?

**Comment by beltran-rubo** [comment]
Hi @opensorceror @hebertdougl, Discourse team strongly recommends not to use that configuration, see https://meta.discourse.org/t/subfolder-support-with-docker/30507  

I would recommend to use a subdomain for the forum instead of a sub-URI

**Comment by carrodher** [comment]
We're closing this issue because there are no plans to work on it if it is not the recommended configuration

**Comment by wesselvdv** [comment]
Could you guys atleast pipe through the ENV relative root to the discourse config?

**Comment by javsalgar** [comment]
Hi,

Do you mean allowing this variable? `DISCOURSE_RELATIVE_URL_ROOT`. Note that this is for the official Discourse container, we do not have support for that variable.

**Comment by wesselvdv** [comment]
Yep, that’s the one. It would require chaning your bitnami.json and helpers to pass it through. If you have it open source somewhere I can add it myself

**Comment by javsalgar** [comment]
Hi,

I am afraid the source of our nami modules (those based on node.js) is not currently available. We plan to migrate all of our assets to  bash so the code will be available in the repositories themselves. In the meantime what you can do is check the `/root/.nami/components/` folder inside the container. Feel free to share the changes here and we will apply them.

**Comment by nickcaballero** [comment]
Finally got this working. Couple of things that need to done.

Create a custom configuration file to provide the URL root:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: discourse-conf
data:
  discourse.conf: |-
    relative_url_root = /discourse
```

Mount the config using `values.yaml`, nami will copy and append to that file.

```yaml
discourse:
  extraVolumeMounts:
    - name: config
      mountPath: /opt/bitnami/discourse/mounted-conf

extraVolumes:
  - name: config
    configMap:
      name: discourse-conf
```

Disable ingress and provide one that correctly maps assets:

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: discourse-main
spec:
  rules:
    - host: myhost
      http:
        paths:
          - path: /discourse(/|$)(?!(assets|images))
            pathType: ImplementationSpecific
            backend:
              service:
                name: discourse
                port:
                  name: http

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: discourse-rewrite
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: myhost
      http:
        paths:
          - path: /discourse(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: discourse
                port:
                  name: http
```

The readiness/liveness probes also need to be updated since the root path has changed. I just disabled them in `values.yaml` but the chart allows for custom probes as well:

```yaml
discourse:
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the information! I think it will be helpful for other community users. About the liveness and readiness probes, you could use the `customLivenessProbe` and `customReadinessProbe` to provide one that suits the new root path. Also, the `extraDeploy` value would be helpful for deploying the new ingress rule.

**Comment by opensorceror** [comment]
Thank you @nickcaballero for sharing this, this is great! Going to test this out today.

**Comment by opensorceror** [comment]
@nickcaballero Unfortunately, I'm on Kubernetes 1.15.x, and the Ingress in that version doesn't support a negative lookahead. Any ideas on how I can still get the `discourse-main` ingress to work?

**Comment by javsalgar** [comment]
Does it fail because of verification errors? Maybe you can upgrade the ingress controller version and that should be enough.

**Comment by nickcaballero** [comment]
@opensorceror, I suppose you can add explicit rules for those paths? The base nginx file (https://github.com/discourse/discourse/blob/master/config/nginx.sample.conf) specifies this as the pattern - my ingress definition is not as complete:

`location ~* (fonts|assets|plugins|uploads)/.*\.(eot|ttf|woff|woff2|ico|otf)$`

So you could rewrite that pattern and leave the other paths alone. Ideally the explicit pattern rule will take precedence and apply the rewrite - docs mention something about the order in which the ingress is created https://kubernetes.github.io/ingress-nginx/how-it-works/#building-the-nginx-model.

**Comment by opensorceror** [comment]
Thanks @nickcaballero for the great reference, it finally works for me. 

I replicated almost all of your config, except disabling the existing ingress. Here is what my final ingress definition looks like:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: discourse-rewrite
  annotations:
    # cannot use rewrite because it adds trailing slash, 
    # see: https://github.com/kubernetes/ingress-nginx/issues/646#issuecomment-297081714
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /discourse(/|$)(fonts|assets|plugins|uploads|images|javascripts)/(.*)\.(eot|ttf|woff|woff2|ico|otf|js|png|svg|gif)$ /$2/$3.$4 permanent;
spec:
  rules:
    - host: myhost
      http:
        paths:
          - path: /discourse(/|$)(fonts|assets|plugins|uploads|images|javascripts)/(.*)\.(eot|ttf|woff|woff2|ico|otf|js|png|svg|gif)$
            backend:
              serviceName: discourse
              servicePort: http

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: discourse
spec:
  rules:
    - host: myhost
      http:
        paths:
          - path: /
            backend:
              serviceName: discourse
              servicePort: http
```

So effectively, the static assets are served at /, while Discourse is served at `/discourse`.

**Comment by opensorceror** [comment]
Discovered one minor issue with my working subfolder setup: Avatars are broken. This is due to a missing symlink that the [official subfolder guide](https://meta.discourse.org/t/subfolder-support-with-docker/30507) recommends.

To fix this, I added the following. This assumes that your subfolder is `/discourse`:

```yaml
discourse:
  command: ["/bin/bash", "-c"]

  ## Custom args for the custom command:
  # Create symlink to subfolder to fix avatars.
  # See Discourse's recommended subfolder config: https://meta.discourse.org/t/subfolder-support-with-docker/30507
  # Without this symlink, avatars are broken.
  # See: https://meta.discourse.org/t/uploaded-avatars-and-gravatar-not-working-with-subfolder-installation/38114
  args:
    - cd /opt/bitnami/discourse && mkdir -p public/discourse &&
      cd public/discourse && ln -s ../uploads && ln -s ../backups &&
      /app-entrypoint.sh nami start --foreground discourse
```
