### ISSUE TITLE
ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/discourse/conf/database.yml'

### ISSUE THREAD

**Issue by mebibou** [bitnami/bitnami-docker-discourse#80]
**Description**

Error when starting the containers using `docker-compose up`:
```
discourse     | nami    INFO  Initializing discourse
discourse     | discour INFO  Patching Discourse...
discourse     | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/discourse/conf/database.yml'
discourse     | nami    INFO  Initializing discourse
discourse     | discour INFO  Patching Discourse...
discourse     | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/discourse/conf/database.yml'
discourse exited with code 1
```

**Steps to reproduce the issue:**

My `docker-compose.yml`:
```
version: '2.2'

services:
  postgresql:
    image: bitnami/postgresql:9.6
    restart: unless-stopped
    container_name: discourse_postgresql
    volumes:
      - postgresql_data:/bitnami

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    container_name: discourse_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis:/opt/cr
      - redis_data:/bitnami

  discourse:
    image: bitnami/discourse:latest
    restart: unless-stopped
    container_name: discourse
    labels:
      kompose.service.type: nodeport
    ports:
      - '3003:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - discourse_data:/bitnami
    env_file:
      - ./.discourse-env
    healthcheck:
      test: "curl -f http://localhost:3000 || false"

  sidekiq:
    image: bitnami/discourse:latest
    restart: unless-stopped
    container_name: discourse_sidekiq
    depends_on:
      - discourse
    volumes:
      - sidekiq_data:/bitnami
    command: 'nami start --foreground discourse-sidekiq'
    env_file:
      - ./.discourse-env

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

**Describe the results you received:**

After restarting my containers (docker-compose down then up), suddenly the discourse container will not start.

**Describe the results you expected:**

It should start again no problem

**Additional information you deem important (e.g. issue happens only occasionally):**

Everytime I restart the containers I cross my fingers because this image seems very unstable and I had to reset everything multiple times, but this time I have too much data I can't just start from scratch. I would be nice if we could stop/start the containers without having so many errors

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 10
 Running: 8
 Paused: 0
 Stopped: 2
Images: 30
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-141-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.795GiB
Name: clearroad
ID: PDX5:BRCL:TSIW:7HLB:JJND:7SDV:KIQK:4FEO:CRY7:2T5H:N67R:WN5L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Linux VM on Azure

**Comment by andresbono** [comment]
Hi @mebibou, thanks for sharing the detailed information.

Could you tell us which specific version of the container are you using? You can run:

```
docker run --rm bitnami/discourse:latest sh -c 'echo $BITNAMI_IMAGE_VERSION'
```

You mention that you stopped and started the containers. Did you update the image in between?

With that information, we will try to reproduce the issue.

**Comment by mebibou** [comment]
The version is `2.1.3-debian-9-r18`

No I did not update the image in between, just did a `docker-compose down`, I added some unrelated containers and then `docker-compose up` to bring it up again, now error

**Comment by andresbono** [comment]
Hi @mebibou, we have done several tests but we can't reproduce your issue. Can you add the following environment variable to your docker-compose so the logs throw more information?

```diff
  discourse:
    image: bitnami/discourse:latest
    restart: unless-stopped
    container_name: discourse
    labels:
      kompose.service.type: nodeport
    ports:
      - '3003:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - discourse_data:/bitnami
+   environment:
+     - NAMI_LOG_LEVEL=trace
    env_file:
      - ./.discourse-env
    healthcheck:
      test: "curl -f http://localhost:3000 || false"
```

Please share the logs with us.

**Comment by mebibou** [comment]
Well that is just great, I `docker-compose down`, added the trace level, `docker-compose up` and now it works... I'll close this now and re-open if it happens again, I'll leave the trace on just in case

**Comment by Southclaws** [comment]
I'm running into this with the latest image as of today, `NAMI_LOG_LEVEL` doesn't seem to do anything. Any updates?

**Comment by andresbono** [comment]
Hi @Southclaws, can you give us more information? Can you share your docker-compose so we can try to reproduce the issue? Please, if passwords or other personal information are specified, change it to dummy values.

**Comment by Southclaws** [comment]
I can't remember unfortunately, I eventually got it working, I think I just deleted everything and started again.

I did have to modify the docker-compose a little to get it running though, here's what I have so far for a fully operational site just in case anyone arrives here via search:

```yaml
version: "3.5"
networks:
    default:
        external:
            name: gateway
    databases:
        driver: bridge
        internal: true

services:
    postgresql:
        image: "bitnami/postgresql:10"
        restart: on-failure
        environment:
            - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRESQL_DATABASE=company
        volumes:
            - "${DATA_DIR}/company/postgresql:/bitnami/postgresql"
        networks:
            - databases

    redis:
        image: "bitnami/redis:5.0"
        restart: on-failure
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        volumes:
            - "${DATA_DIR}/company/redis:/bitnami/redis/data"
        networks:
            - databases

    discourse:
        image: "bitnami/discourse:2"
        # restart: on-failure
        environment:
            - POSTGRESQL_HOST=postgresql
            - POSTGRESQL_ROOT_USER=postgres
            - POSTGRESQL_ROOT_PASSWORD=${POSTGRES_PASSWORD}
            - REDIS_HOST=redis
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - DISCOURSE_POSTGRESQL_NAME=company
            - DISCOURSE_POSTGRESQL_USERNAME=postgres
            - DISCOURSE_POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
            - DISCOURSE_HOSTNAME=www.company.com
            - DISCOURSE_USERNAME=company
            - DISCOURSE_EMAIL=hello@company.com
            - DISCOURSE_PASSWORD=${ADMIN_PASSWORD}
            - SMTP_HOST=smtp.mailserver.net
            - SMTP_PORT=587
            - SMTP_USER=apikey
            - SMTP_PASSWORD=${SMTP_PASSWORD}
        depends_on:
            - postgresql
            - redis
        volumes:
            - "${DATA_DIR}/company/discourse:/bitnami"
        networks:
            - default
            - databases
        labels:
            - traefik.enable=true
            - traefik.docker.network=gateway
            - traefik.frontend.rule=Host:www.company.com,company.com
            - traefik.frontend.headers.SSLRedirect=false
            - traefik.frontend.headers.SSLHost=www.company.com
            - traefik.frontend.redirect.regex=^https?://[a-z0-9.]+/(.*)
            - traefik.frontend.redirect.replacement=https://www.company.com/$${1}
            - traefik.port=3000

    sidekiq:
        image: "bitnami/discourse:2"
        # restart: on-failure
        command: "nami start --foreground discourse-sidekiq"
        environment:
            - NAMI_LOG_LEVEL=trace
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - DISCOURSE_POSTGRESQL_NAME=company
            - DISCOURSE_POSTGRESQL_USERNAME=postgres
            - DISCOURSE_POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
            - DISCOURSE_HOST=discourse
            - DISCOURSE_PORT=3000
            - DISCOURSE_HOSTNAME=www.company.com
            - DISCOURSE_USERNAME=company
            - DISCOURSE_EMAIL=hello@company.com
            - DISCOURSE_PASSWORD=${ADMIN_PASSWORD}
            - SMTP_HOST=smtp.mailserver.net
            - SMTP_PORT=587
            - SMTP_USER=apikey
            - SMTP_PASSWORD=${SMTP_PASSWORD}
        depends_on:
            - discourse
        volumes:
            - "${DATA_DIR}/company/sidekiq:/bitnami"
        networks:
            - databases
```
