### ISSUE TITLE
Users have to reactivate after a restart if the discourse container doesn't have a persistent volume

### ISSUE THREAD

**Issue by adarnimrod** [bitnami/bitnami-docker-discourse#82]
We run our Discourse setup on ECS with the database running on RDS which is the only persistence in the setup. After a restart all users have to reactivate their account which happens every time we deploy a new version or configuration. You can reproduce this issue locally with this the following `docker-compose.yml`:

```yaml
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:10'
    volumes:
      - 'postgresql_data:/bitnami'
  redis:
    image: 'bitnami/redis:4.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse:2'
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=localhost
  sidekiq:
    image: 'bitnami/discourse:2'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=localhost
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  sidekiq_data:
    driver: local
```
Which is the same `docker-compose.yml` from https://github.com/bitnami/bitnami-docker-discourse#run-the-application-using-docker-compose except that the volume for the discourse container is removed. Then follow these steps to reproduce
1. Start the containers (`docker-compose up`) and wait for discourse to start.
1. Install a mail server (for example `apt-get update && apt-get install -y postfix && chmod 777 /var/spool/postfix/* && /etc/init.d/postfix restart`).
1. Register a new account.
1. Activate the account from the email you received. Try to login with the 
1. Stop and start a new container (`docker-compose down && docker-compose up`) and wait for discourse to start.
1. Try to login.

Expected result: You can login without issue.
Received results: You have to reactivate your account.

**Version**

***On ECS***
- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Jan 28 21:03:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Mon Jan 28 21:05:04 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.101-91.76.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.796GiB
Name: ip-10-16-49-30.us-west-2.compute.internal
ID: 4SPL:NB2B:WGFM:FLHO:Y5H4:YDXI:WTZC:C6WM:5MRX:27MA:5RT3:GNKG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
AMI version: amazon/amzn2-ami-ecs-hvm-2.0.20190301-x86_64-ebs (ami-0302f3ec240b9d23c)

***Locally***
- Output of `docker version`:

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.5
 Git commit:        4c52b90
 Built:             Mon, 11 Mar 2019 00:06:03 +0000
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.5
  Git commit:       4c52b90
  Built:            Mon Mar 11 00:06:03 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 15
 Running: 4
 Paused: 0
 Stopped: 11
Images: 105
Server Version: 18.09.1
Storage Driver: btrfs
 Build Version: Btrfs v4.20.1 
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.0-4-amd64
Operating System: Debian GNU/Linux buster/sid
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.42GiB
Name: Yoga-C930
ID: QCJZ:CNES:7FJT:KHWQ:TYTN:7HTX:XBI3:ZBJP:K3GP:EF7T:XNUE:I3YX
Docker Root Dir: /home/nimrod/.subvolumes/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.0, build 0aa5906
docker-py version: 3.7.2
CPython version: 3.7.3rc1
OpenSSL version: OpenSSL 1.1.1b  26 Feb 2019
```
