### ISSUE TITLE
Example v3 docker-compose configuration for use with docker stack deploy command?

### ISSUE THREAD

**Issue by jackfirth** [bitnami/bitnami-docker-discourse#84]
I'm attempting to use these images with Docker Swarm and Kubernetes, using the `docker stack deploy` command and a `docker-compose.yml` file with `version: "3.7"`. But the example `docker-compose.yml` given in the README is based on `version: "2"`, which doesn't support stack deployment at all. I've tried to figure out a correct config but haven't had much success.

# Steps to reproduce the issue

1. Run `docker swarm init` to set up a local Docker Swarm cluster with only one manager node.
2. Use this `docker-compose.yml` file:

```
version: "3.7"

x-parameters:
  - &public_host "foo.local"
  - &db_init_postgres_database "bitnami_application"
  - &db_init_postgres_username "bn_discourse"
  - &db_init_postgres_password "bitnami1"
  - &web_app_postgres_database "bitnami_application"
  - &web_app_postgres_username "bn_discourse"
  - &web_app_postgres_password "bitnami1"

services:
  # Public services (ports are published on host)
  discourse:
    image: 'bitnami/discourse:2'
    ports:
      - '80:80'
    volumes:
      - 'discourse_data:/bitnami'
    deploy:
      replicas: 1
    environment:
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_ROOT_USER: postgres
      POSTGRESQL_CLIENT_CREATE_DATABASE_NAME: *db_init_postgres_database
      POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME: *db_init_postgres_username
      POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD: *db_init_postgres_password
      DISCOURSE_POSTGRESQL_NAME: *web_app_postgres_database
      DISCOURSE_POSTGRESQL_USERNAME: *web_app_postgres_username
      DISCOURSE_POSTGRESQL_PASSWORD: *web_app_postgres_password
      DISCOURSE_HOSTNAME: *public_host
  # Private services (no ports published on host)
  sidekiq:
    image: 'bitnami/discourse:2'
    volumes:
      - 'sidekiq_data:/bitnami'
    deploy:
      replicas: 1
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      DISCOURSE_POSTGRESQL_NAME: *web_app_postgres_database
      DISCOURSE_POSTGRESQL_USERNAME: *web_app_postgres_username
      DISCOURSE_POSTGRESQL_PASSWORD: *web_app_postgres_password
      DISCOURSE_HOST: discourse
      DISCOURSE_PORT: 80
      DISCOURSE_HOSTNAME: *public_host
  postgresql:
    image: 'bitnami/postgresql:10'
    volumes:
      - 'postgresql_data:/bitnami'
    deploy:
      replicas: 1
  redis:
    image: 'bitnami/redis:4.0'
    volumes:
      - 'redis_data:/bitnami'
    deploy:
      replicas: 1
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

3. Add this line to your `/etc/hosts` file:

```
127.0.0.1       foo.local
```

4. Run `docker stack deploy --compose-file docker-compose.yml basic-bitnami`
5. Wait several minutes, to be sure that the database has been initialized and everything is ready for web requests.
6. Visit `foo.local` in your browser.

# Describe the results you received

The browser tells me there was a problem loading the page:

![Screen Shot 2019-04-30 at 7 30 37 PM](https://user-images.githubusercontent.com/8175575/57003859-84d34380-6b7e-11e9-9a85-a125fcaecc38.png)

Additionally, checking the service logs with `docker service logs basic-bitnami_discourse` shows no new log messages for received HTTP requests.

# Describe the results you expected

I expected to be able to load discourse in my browser.

# Additional information you deem important 

When running with `docker-compose` instead of `docker swarm deploy`, everything works as I expect it to. It's only in swarm mode that things go south. I've only tested this on my local machine, I don't know if the problem persists on a real production swarm cluster.

I'd really like to see the `docker-compose.yml` files given as examples in the README updated to version 3+, with explicit instructions for how to run Discourse with `docker stack deploy`.

# Version

- Output of `docker version`: 

```
Client: Docker Engine - Community
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:32:50 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:40:58 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Containers: 182
 Running: 4
 Paused: 0
 Stopped: 178
Images: 723
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: pwa7lzvpcifuzn9kd493ranyh
 Is Manager: true
 ClusterID: oy7c0lyk9z3edluipsojiab32
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker Desktop
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: docker-desktop
ID: FMCV:JXVT:PCLB:GWC6:JR44:B2ZO:UY2F:7MD4:U6SA:CQQB:THAP:WK7R
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 74
 Goroutines: 245
 System Time: 2019-05-01T02:37:55.7380151Z
 EventsListeners: 6
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.0-rc1, build 0f3d4dda
docker-py version: 3.7.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

I'm using Docker for Mac on macOS Mojave.
