### ISSUE TITLE
"Could not connect: Connection refused"

### ISSUE THREAD

**Issue by philiprhoades** [bitnami/bitnami-docker-discourse#88]
**Discourse not responding**

**Steps to reproduce the issue:**

1. Install Docker Discourse from the supplied docker-compose file.
2. Browse to localhost

I can see the three containers running:

```
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                  NAMES
9876fe10b70a        bitnami/discourse:2   "/app-entrypoint.s..."   19 minutes ago      Up 11 minutes       3000/tcp               discourse_sidekiq_1
858afd9fa9a1        bitnami/discourse:2   "/app-entrypoint.s..."   19 minutes ago      Up About a minute   0.0.0.0:80->3000/tcp   discourse_discourse_1
8132ab109603        bitnami/redis:4.0     "/entrypoint.sh /r..."   19 minutes ago      Up 11 minutes       6379/tcp               discourse_redis_1
```
but cannot connect to port 80:

"Could not connect: Connection refused"

**Describe the results you expected:**

To see a Discourse welcome page.

**Comment by tompizmor** [comment]
@philiprhoades Thanks for reporting the issue. We will take a look and come back to you once we have more information.

**Comment by carrodher** [comment]
Hi,
In the above output, I can see 3 containers (discourse, sidekiq and redis) but there should be 4 (the previous ones plus postgresql).
We recently implemented some [changes](https://github.com/bitnami/bitnami-docker-postgresql#9612-r70-9612-ol-7-r72-1070-r69-1070-ol-7-r71-1120-r69-and-1120-ol-7-r71) in the postgresql image, as we are using [rolling tags](https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/), the _docker-compose.yml_ is pulling the latest postgresql version with some changes. Now, you need to use a password or set the `ALLOW_EMPTY_PASSWORD=yes` env. variable in the postgresql container section:
```yaml
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami'
...
```
We are preparing a new release with some changes in the _docker-compose.yml_ in order to add this variable by default along with other changes like update the postgresql and redis version.

In the same way, in the discourse container section, you need to modify the `DISCOURSE_HOSTNAME` env. var by setting a correct value (`localhost` in your case):
```yaml
  discourse:
    image: 'bitnami/discourse:2'
    ...
    environment:
      ...
      - DISCOURSE_HOSTNAME=localhost
```
