### ISSUE TITLE
Error executing 'postInstallation': Files to substitute resolved to an empty list

### ISSUE THREAD

**Issue by yod527** [bitnami/bitnami-docker-discourse#90]
**Description**
Getting **Error executing 'postInstallation': Files to substitute resolved to an empty list** on main discourse container. [2.2.5] container tag.

**Steps to reproduce the issue:**

1. docker-compose up - OK
2. docker-compose down - OK
3. docker-compose up - ERROR

**Describe the results you received:**

Getting described earlier error. 

**Describe the results you expected:**

Container starts without an issue

**Additional information you deem important (e.g. issue happens only occasionally):**

I have exposed `/bitnami` directory to filesystem, not to docker volume as by default.

**Version** 2.2.5, redis:5.0.0-debian-9-r12, postgres:11

- Output of `docker version`:

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 31
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-9-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.845GiB
Name: debian
ID: ZFQV:FZW7:MJHL:N5RO:RCJT:SG6L:ORFA:F4VH:FY7X:5HFU:EPLV:GLMX
Docker Root Dir: /mnt/hupp-sata/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Debian 9, running in VMware on MacOS

How can I debug this issue and understand, why I'm getting this error?

**Comment by marcosbc** [comment]
Hi @yod527, unfortunately we cannot reproduce this issue. We're using this docker-compose file with the container `bitnami/discourse:2` (image id `b8ebfc8689fd`):

```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse:2'
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - './ds_data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=www.example.com
  sidekiq:
    image: 'bitnami/discourse:2'
    depends_on:
      - discourse
    volumes:
      - './sq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=www.example.com
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

Does it work for you with that docker-compose?

Note that in order to debug this, you could add more logging:

```
@@ -20,6 +20,7 @@
     volumes:
       - 'discourse_data:/bitnami'
     environment:
+      - NAMI_LOG_LEVEL=trace8
       - POSTGRESQL_HOST=postgresql
       - POSTGRESQL_ROOT_USER=postgres
       - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
```

**Comment by yod527** [comment]
@marcosbc Hello and thank you for your response! I'm running a bit different configuration, e.g. all the container data exposed to filesytem, not to the docker volumes. I've set, trace8 in loglevel and getting next output:
```
nami    TRACE Error: Error executing 'postInstallation': Files to substitute resolved to an empty list
    at Object.substitute (/opt/bitnami/nami/node_modules/nami-utils/lib/file/substitute.js:182:11)
    at Object.wrappedFn (/opt/bitnami/nami/node_modules/nami-utils/lib/function-wrapping.js:191:17)
    at Object.$app.helpers.configureDatabase (/root/.nami/components/com.bitnami.discourse/helpers.js:38:9)
    at Service.$app.postInstallation (/root/.nami/components/com.bitnami.discourse/main.js:37:16)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
Error executing 'postInstallation': Files to substitute resolved to an empty list
```
Doesn't actually helps me to debug the issue... Like why do we need this postInstallation script, and what it's doing? Just trying to understand nature of the issue. Thank you!

**Comment by marcosbc** [comment]
Hi @yod527, the container entrypoint is trying to replace the following file:

    /opt/bitnami/discourse/conf/database.yml

Could you modify the "command" property in your docker-compose to `tail -f /dev/null`, start the container and execute the following command in it?

    /app-entrypoint.sh nami start --foreground discourse

The entrypoint should fail, but you should still be in the container. Once that happens, please run the following commands:

    ls -la /opt/bitnami/discourse
    ls -la /opt/bitnami/discourse/conf
    ls -la /opt/bitnami/discourse/conf/discourse.yml
    cat /opt/bitnami/discourse/conf/discourse.yml # don't show us the contents, just make sure it makes sense

Could it be possible you are mounting the "discourse.yml" configuration file?

**Comment by yod527** [comment]
Hi @marcosbc !
I'm exposing only `/bitnami` directory not the `/opt/bitnami` one. 
So, my volumes section looks like:

```
    volumes:
      - "/mnt/hupp-sata/discourse/data:/bitnami:rw"
```
That what i'm getting, trying to execute commands provided by you:

```bash
root@e6b01d83c36b:/# ls -la /opt/bitnami/discourse/conf/discourse.yml
ls: cannot access '/opt/bitnami/discourse/conf/discourse.yml': Too many levels of symbolic links
```
same with a `cat` command actually
All previous commands executed OK, and returned correct file/directories list.
Thanks.

**Comment by marcosbc** [comment]
Hi @yod527, your issue is really strange, but we're still not able to reproduce it.

Could you prepare a list of steps that can be followed to reproduce this issue on our side with a clean Bitnami Discourse `2.2.6-debian-9-r7` image? The more details the better.

Also, could you confirm that you are **not** mounting any configuration files? E.g. the docker-compose.yml file is same/similar to the one below:

```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'bitnami/discourse:2'
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=www.example.com
  sidekiq:
    image: 'bitnami/discourse:2'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=www.example.com
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

**Comment by yod527** [comment]
@marcosbc 2.2.6-debian-9-r7 image doesn't help. I've sent you my compose file in a pm. Thanks

**Comment by yod527** [comment]
Hello! @marcosbc is there anything else I can provide, or do to get a workaround with this? Thank you!

**Comment by marcosbc** [comment]
Hi @yod527, we were able to reproduce this issue with your container. It seems that this is happening because of this:

```
  discourse:
    (...)
    restart: always
```

This was masking the actual error, which is:

```
discourse-discourse-cmp | discour INFO  Migrating database...
discourse-discourse-cmp | Error executing 'postInstallation': rake aborted!
discourse-discourse-cmp | StandardError: An error has occurred, this and all later migrations canceled:
discourse-discourse-cmp |
discourse-discourse-cmp | PG::InsufficientPrivilege: ERROR:  permission denied to create extension "hstore"
discourse-discourse-cmp | HINT:  Must be superuser to create this extension.
discourse-discourse-cmp | : CREATE EXTENSION IF NOT EXISTS hstore
```

After some investigation, it seems like persistence is not working properly when mounting the folders manually. We're investigating it, but we would like to have it fixed early this week if possible.

In the meantime, if you prefer to workaround it for now, using Docker volumes is working properly. We'll update with any progress.

**Comment by marcosbc** [comment]
Hi @yod527, we've find a fix for your issue. However, we're still checking how we can fix this in the code as it doesn't seem to be a trivial fix.

In your `docker-compose.yml` file, change this line:

```
    volumes:
      - "/mnt/cmp-sata/discourse/postgresql:/bitnami:rw"
```

By this:

```
    volumes:
      - "/mnt/cmp-sata/discourse/postgresql:/bitnami/postgresql:rw"
```

We will continue investigating why this specific change is needed, but for now you should be able to get your Discourse installation working properly.

**Comment by yod527** [comment]
@marcosbc that actually helped me, thank you so much!

**Comment by marcosbc** [comment]
We have decided to standarize in using the VOLUME directive, and mounting `/bitnami/component` (instead of `/bitnami`) in all of our containers.
Unfortunately it has some implications as there are breaking changes, so it is something that will take us some time.

In any case, since you were able to resolve your issue, we'll proceed to close this issue. Thanks for reporting it!

**Comment by polarathene** [comment]
@marcosbc I have just run into this and appear to be doing the same as @yod527 by using local filesystem mounts instead of docker volumes.

**`docker-compose up` output**:

```
Starting discourse_redis_1 ... 
Starting discourse_postgresql_1 ... 
Starting discourse_redis_1
Starting discourse_postgresql_1 ... done
Starting discourse_discourse_1 ... 
Starting discourse_discourse_1 ... done
Starting discourse_sidekiq_1 ... 
Starting discourse_sidekiq_1 ... done
Attaching to discourse_redis_1, discourse_postgresql_1, discourse_discourse_1, discourse_sidekiq_1
redis_1       |  07:54:37.15 
redis_1       |  07:54:37.15 Welcome to the Bitnami redis container
redis_1       |  07:54:37.15 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis_1       |  07:54:37.16 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis_1       |  07:54:37.16 Send us your feedback at containers@bitnami.com
redis_1       |  07:54:37.16 
redis_1       |  07:54:37.16 INFO  ==> ** Starting Redis setup **
redis_1       |  07:54:37.17 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis_1       |  07:54:37.18 INFO  ==> Initializing Redis...
redis_1       | 
redis_1       |  07:54:37.19 INFO  ==> ** Redis setup finished! **
redis_1       |  07:54:37.20 INFO  ==> ** Starting Redis **
redis_1       | 1:C 26 Nov 2019 07:54:37.210 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1       | 1:C 26 Nov 2019 07:54:37.210 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1       | 1:C 26 Nov 2019 07:54:37.210 # Configuration loaded
redis_1       |                 _._                                                  
redis_1       |            _.-``__ ''-._                                             
redis_1       |       _.-``    `.  `_.  ''-._           Redis 5.0.7 (00000000/0) 64 bit
redis_1       |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1       |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1       |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1       |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1       |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1       |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1       |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis_1       |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1       |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1       |  |    `-._`-._        _.-'_.-'    |                                  
redis_1       |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1       |       `-._    `-.__.-'    _.-'                                       
redis_1       |           `-._        _.-'                                           
redis_1       |               `-.__.-'                                               
redis_1       | 
redis_1       | 1:M 26 Nov 2019 07:54:37.211 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1       | 1:M 26 Nov 2019 07:54:37.211 # Server initialized
redis_1       | 1:M 26 Nov 2019 07:54:37.211 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1       | 1:M 26 Nov 2019 07:54:37.211 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1       | 1:M 26 Nov 2019 07:54:37.255 * DB loaded from append only file: 0.044 seconds
redis_1       | 1:M 26 Nov 2019 07:54:37.255 * Ready to accept connections
postgresql_1  | postgresql 07:54:37.30 
postgresql_1  | postgresql 07:54:37.31 Welcome to the Bitnami postgresql container
postgresql_1  | postgresql 07:54:37.31 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql_1  | postgresql 07:54:37.32 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql_1  | postgresql 07:54:37.32 Send us your feedback at containers@bitnami.com
postgresql_1  | postgresql 07:54:37.32 
postgresql_1  | postgresql 07:54:37.34 INFO  ==> ** Starting PostgreSQL setup **
postgresql_1  | postgresql 07:54:37.42 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql_1  | postgresql 07:54:37.42 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
postgresql_1  | postgresql 07:54:37.42 INFO  ==> Loading custom pre-init scripts...
postgresql_1  | postgresql 07:54:37.43 INFO  ==> Initializing PostgreSQL database...
postgresql_1  | postgresql 07:54:37.47 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql_1  | postgresql 07:54:37.50 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql_1  | postgresql 07:54:37.50 INFO  ==> Generating local authentication configuration
postgresql_1  | postgresql 07:54:37.52 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql_1  | postgresql 07:54:37.52 INFO  ==> Configuring replication parameters
postgresql_1  | postgresql 07:54:37.55 INFO  ==> Configuring fsync
postgresql_1  | postgresql 07:54:37.56 INFO  ==> Loading custom scripts...
postgresql_1  | postgresql 07:54:37.57 INFO  ==> Enabling remote connections
postgresql_1  | postgresql 07:54:37.59 INFO  ==> Stopping PostgreSQL...
postgresql_1  | 
postgresql_1  | postgresql 07:54:37.59 INFO  ==> ** PostgreSQL setup finished! **
postgresql_1  | postgresql 07:54:37.66 INFO  ==> ** Starting PostgreSQL **
postgresql_1  | 2019-11-26 07:54:37.697 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql_1  | 2019-11-26 07:54:37.697 GMT [1] LOG:  listening on IPv6 address "::", port 5432
postgresql_1  | 2019-11-26 07:54:37.698 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
postgresql_1  | 2019-11-26 07:54:37.707 GMT [1] LOG:  could not open usermap file "/bitnami/postgresql/data/pg_ident.conf": No such file or directory
postgresql_1  | 2019-11-26 07:54:37.711 GMT [160] LOG:  database system was shut down at 2019-11-26 07:47:06 GMT
postgresql_1  | 2019-11-26 07:54:37.716 GMT [1] LOG:  database system is ready to accept connections
discourse_1   | 
discourse_1   | Welcome to the Bitnami discourse container
discourse_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
discourse_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
discourse_1   | 
sidekiq_1     | 
sidekiq_1     | Welcome to the Bitnami discourse container
sidekiq_1     | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
sidekiq_1     | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
sidekiq_1     | 
sidekiq_1     | nami    INFO  Initializing discourse-sidekiq
sidekiq_1     | discour INFO  No Discourse installation was found. The installation wasn't fully performed
sidekiq_1     | discour INFO  Waiting for Discourse service to be ready...
discourse_1   | nami    INFO  Initializing discourse
discourse_1   | discour INFO  Patching Discourse...
discourse_1   | postgre INFO  Trying to connect to PostgreSQL server
postgresql_1  | 2019-11-26 07:54:45.671 GMT [167] LOG:  incomplete startup packet
discourse_1   | postgre INFO  Found PostgreSQL server listening at postgresql:5432
discourse_1   | postgre INFO  PostgreSQL server listening and working at postgresql:5432
discourse_1   | discour INFO  Preparing Discourse environment...
discourse_1   | discour INFO  Configuring the Discourse database files...
discourse_1   | Error executing 'postInstallation': Files to substitute resolved to an empty list
discourse_discourse_1 exited with code 1
```

After exiting with `ctrl+c`, a little bit of output from sidekiq appeared:

```
sidekiq_1     | Error executing 'postInstallation': Failed to connect to discourse:3000 after 90 tries
discourse_sidekiq_1 exited with code 1
```

**docker-compose.yml**:

```
version: '2'
services:
  postgresql:
    image: bitnami/postgresql:11
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/postgresql:/bitnami/postgresql
  redis:
    image: bitnami/redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/bitnami
  discourse:
    image: bitnami/discourse:2
    labels:
      - "traefik.http.routers.discourse_router.rule=Host(`discourse.mydomain.com`)"
      - "traefik.http.routers.discourse_router.entryPoints=secure"
      - "traefik.http.routers.discourse_router.tls=true"
      - "traefik.http.services.discourse_service.loadbalancer.server.port=3000"
    # Traefik reverse proxy configured above to map port 443 to 3000
    # Internal network for containers should still be able to access via port 3000, otherwise port 443 at the domain
    #ports:
      #- '80:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./data/discourse:/bitnami
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOSTNAME=discourse.mydomain.com
  sidekiq:
    image: bitnami/discourse:2
    depends_on:
      - discourse
    volumes:
      - ./data/sidekiq:/bitnami
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=discourse.mydomain.com
```

**EDIT:** Seems the services/containers were being named `discourse_discourse1`, discourse_postgresql1`, etc with my directory for the docker-compose.yml being `discourse`. Adding a container name field to each one avoided that so that the containers would have names matching `discourse` and `postgresql`. as per the host environment variables.

After that, ran into the following:

```
discourse     | postgre ERROR [canConnect] Connection with 'bn_discourse' user is unsuccessful
```

Still an issue reaching the database? Added a network to the compose file for them to share and that seems to have resolved it. My VPS idles at 200MB RAM, <300MB with the reverse proxy service in a separate compose file running. During install memory reached 1.4GB, then settled down to 1.25GB with output not idling at:

```
sidekiq       | discour INFO  Waiting for Discourse service to be ready...
discourse     | discour INFO  Creating the Discourse admin user...
discourse     | discour INFO  Configuring your Discourse installation...
```

Accessed the service in the browser and it was ready to use, so memory at idle with no user activity is 1GB roughly?

Figured I'd share this in case anyone else came across the same errors.

**Comment by andresbono** [comment]
Hi @polarathene, thanks for sharing this information and the steps to troubleshoot your issue.

**Comment by saqibarfeen** [comment]
Similar problem I got: Error executing 'postInstallation': Files to substitute resolved to an empty list
Mine problem was that when I add restart: always to discourse container, it kept restarting with the above error.
I tried the solution posted by @polarathene here. It worked for me.
I also had names like discourse_discourse_1  , so just added a key e.g container_name: 'discourse' to each service definition in yml. and it worked.
Thanks!

**Comment by javsalgar** [comment]
Hi,

Just to confirm, are you using host path volumes or you are using docker volumes?

**Comment by KlugmannM** [comment]
hmm have the same problem, with the following error message after starting bitnami:discourse
```
discourse     | postgre INFO  Trying to connect to PostgreSQL server
postgresql_1  | 2020-12-09 18:11:09.836 GMT [89] LOG:  incomplete startup packet
discourse     | postgre INFO  Found PostgreSQL server listening at postgresql:5432
discourse     | postgre INFO  PostgreSQL server listening and working at postgresql:5432
discourse     | discour INFO  Preparing Discourse environment...
discourse     | discour INFO  Configuring the Discourse database files...
discourse     | Error executing 'postInstallation': Files to substitute resolved to an empty list
discourse exited with code 1
redis_1       | 1:M 09 Dec 2020 18:15:57.069 * 10 changes in 300 seconds. Saving...
redis_1       | 1:M 09 Dec 2020 18:15:57.070 * Background saving started by pid 50
```
Current docker-compose file
```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:11-debian-10'
    user: "1001"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/opt/containers/discourse/postgresql_data:/bitnami/postgresql'
    networks:
      - default
      
  redis:
    image: 'bitnami/redis:6.0-debian-10'
    user: root
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/opt/containers/discourse/redis_data:/bitnami'
    networks:
      - default
      
  discourse:
    image: 'bitnami/discourse:2-debian-10'
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.discourse.entrypoints=http"
       - "traefik.http.routers.discourse.rule=Host(`####`)"
       - "traefik.http.middlewares.discourse-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.discourse.middlewares=discourse-https-redirect"
       - "traefik.http.routers.discourse-secure.entrypoints=https"
       - "traefik.http.routers.discourse-secure.rule=Host(`####`)"
       - "traefik.http.routers.discourse-secure.tls=true"
       - "traefik.http.routers.discourse-secure.tls.certresolver=http"
       - "traefik.http.routers.discourse-secure.service=discourse"
       - "traefik.http.services.discourse.loadbalancer.server.port=3000"
       - "traefik.docker.network=proxy"
    networks:
      - proxy
      - default
    depends_on:
      - postgresql
      - redis
    volumes:
      - '/opt/containers/discourse/discourse_data:/bitnami'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1#test
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1#test
      - DISCOURSE_HOSTNAME=####
      - DISCOURSE_USERNAME=####
      - DISCOURSE_PASSWORD=test**test##
      - DISCOURSE_EMAIL=####
      
  sidekiq:
    image: 'bitnami/discourse:2-debian-10'
    depends_on:
      - discourse
    volumes:
      - '/opt/containers/discourse/sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1#test
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=####
    networks:
      - default

networks:
  proxy:
    external: true
```

Could you perhaps post your docker-compose files, what is meant by @saqibarfeen  _so just added a key e.g container_name: 'discourse' to each service definition in yml. and it worked_

Thanks for you efforts.

**Comment by marcosbc** [comment]
Hi @KlugmannM, unfortunately I could not reproduce your issue even using your exact same docker-compose (except for some minor modifications to the network and host/user/pass:

```diff
@@ -52,10 +52,10 @@
       - DISCOURSE_POSTGRESQL_NAME=bitnami_application
       - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
       - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1#test
-      - DISCOURSE_HOSTNAME=####
-      - DISCOURSE_USERNAME=####
-      - DISCOURSE_PASSWORD=test**test##
-      - DISCOURSE_EMAIL=####
+      - DISCOURSE_HOSTNAME=example.com
+      - DISCOURSE_USERNAME=myuser
+      - DISCOURSE_PASSWORD=test12345678
+      - DISCOURSE_EMAIL=myuser@example.com

   sidekiq:
     image: 'bitnami/discourse:2-debian-10'
@@ -76,4 +76,3 @@

 networks:
   proxy:
-    external: true
```

Is the error consistent? (I.e. if you try to initialize without any existing volumes, the error keeps happening.) - If so, you could try to make this change to the compose:

```yaml
@@ -21,6 +21,7 @@
       - default

   discourse:
+    command: sleep infinity
     image: 'bitnami/discourse:2-debian-10'
     labels:
        - "traefik.enable=true"
```

And then enter the container (`docker-compose exec discourse bash`) and run these commands to initialize discourse, and once it fails, check the contents of discourse.conf and database.yml:

```console
$ /app-entrypoint.sh nami start --foreground discourse
# ...this should fail
$ cat /opt/bitnami/discourse/conf/discourse.conf
$ cat /opt/bitnami/discourse/conf/database.yml
```
