### ISSUE TITLE
Error executing 'postInstallation': File /opt/bitnami/discourse/conf/database.yml did not match any of the provided substitutions

### ISSUE THREAD

**Issue by zeppelinux** [bitnami/bitnami-docker-discourse#91]
Trying to persist the `/opt/bitnami/discourse/conf/discourse.conf` because i want to configure the email server using this: https://crunchify.com/how-to-setup-email-for-discourse-forum-with-google-apps-smtp-relay-right-way/.
I have one persistentVolumeClaim folder with two subfolders (data and conf):

```
volumeMounts:
        - name: data
          mountPath: /bitnami
          subPath: data
        - name: data
          mountPath: /opt/bitnami/discourse/conf
          subPath: conf
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: discourse
```

The mounted /conf was initialized by successfully started discourse pod and copied over to the persistent volume.
Kubernetes mounts it, but discourse fails with:
`Error executing 'postInstallation': File /opt/bitnami/discourse/conf/database.yml did not match any of the provided substitutions`

The end goal is to configure the SMTP server, I'm not sure if i have to use persistent volume to do it actually.
