### ISSUE TITLE
Content Security Policy: The page’s settings blocked the loading of a resource

### ISSUE THREAD

**Issue by tech348712013870132** [bitnami/bitnami-docker-discourse#95]
I am unable to access my discourse deployment that is installed via the kubernetes test.yaml configuration.
The server starts up fine but I only get a empty page result (favicon/site-titel gets loaded) and the remaining scripts that are necessary to load the page are completely being blocked by a "Content Security Policy":

```
Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing postgresql-client
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql:5432
postgre ERROR [canConnect] Connection with 'bn_discourse' user is unsuccessful
postgre INFO  ==> Creating database bitnami_application...
postgre INFO  ==> Granting access to bn_discourse to the database bitnami_application...
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Configuring Discourse database...
discour INFO  Enabling PostgreSQL plugins for Discourse...
discour INFO  Migrating database...
discour INFO  Creating the Discourse admin user...
discour INFO  Configuring your Discourse installation...
discour INFO 
discour INFO  ########################################################################
discour INFO   Installation parameters for discourse:
discour INFO     Username: user
discour INFO     Password: **********
discour INFO   (Passwords are not shown for security reasons)
discour INFO  ########################################################################
discour INFO 
nami    INFO  discourse successfully initialized
Starting discourse...
Migrating to AddTextSizeSeqToUserOption (20190125153345)
Migrating to AddIndexOnUserIdToSingleSignOnRecords (20190130013015)
Creating scope :open. Overwriting existing method Poll.open.
Creating scope :open. Overwriting existing method Poll.open.
[ E 2019-06-25 14:46:25.4247 4054/T1 age/Wat/WatchdogMain.cpp:317 ]: Error adjusting Watchdog's OOM score: error writing to /proc/self/oom_score_adj: Permission denied (errno=13)
[ N 2019-06-25 14:46:25.4339 4054/T1 age/Wat/WatchdogMain.cpp:1366 ]: Starting Passenger watchdog...
[ N 2019-06-25 14:46:25.5211 4057/T1 age/Cor/CoreMain.cpp:1339 ]: Starting Passenger core...
[ N 2019-06-25 14:46:25.5213 4057/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2019-06-25 14:46:25.5501 4057/T1 age/Cor/CoreMain.cpp:1014 ]: Passenger core online, PID 4057
[ N 2019-06-25 14:46:28.0528 4057/T7 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
Creating scope :open. Overwriting existing method Poll.open.
Started HEAD "/" for 127.0.0.1 at 2019-06-25 14:47:02 +0000
Processing by ListController#latest as HTML
Started GET "/" for 10.28.3.1 at 2019-06-25 14:47:03 +0000
Processing by ListController#latest as HTML
  Rendering list/list.erb within layouts/application
  Rendered list/list.erb within layouts/application (97.2ms)
  Rendered layouts/_head.html.erb (194.1ms)
  Rendered common/_discourse_stylesheet.html.erb (26.3ms)
  Rendering list/list.erb within layouts/application
  Rendered list/list.erb within layouts/application (53.7ms)
  Rendered layouts/_head.html.erb (96.6ms)
  Rendered common/_discourse_stylesheet.html.erb (39.8ms)
  Rendered application/_header.html.erb (8.4ms)
  Rendered application/_header.html.erb (6.9ms)
Completed 200 OK in 5175ms (Views: 3032.9ms | ActiveRecord: 143.2ms)
Completed 200 OK in 3970ms (Views: 1748.1ms | ActiveRecord: 237.7ms)
Started GET "/stylesheets/desktop_1b778089333a8789c8c7e566861930f62a4a502e.css?__ws=35.228.xxx.xxx" for 10.28.3.1 at 2019-06-25 14:47:07 +0000
Processing by StylesheetsController#show as CSS
  Parameters: {"__ws"=>"35.228.xxx.xxx", "name"=>"desktop_1b778089333a8789c8c7e566861930f62a4a502e"}
Sent file /opt/bitnami/discourse/tmp/stylesheet-cache/desktop_1b778089333a8789c8c7e566861930f62a4a502e.css (0.5ms)
Completed 200 OK in 19ms (ActiveRecord: 5.5ms)
Started GET "/stylesheets/desktop_1b778089333a8789c8c7e566861930f62a4a502e.css.map" for 10.166.0.11 at 2019-06-25 14:47:12 +0000
Processing by StylesheetsController#show_source_map as */*
  Parameters: {"name"=>"desktop_1b778089333a8789c8c7e566861930f62a4a502e"}
Sent file /opt/bitnami/discourse/tmp/stylesheet-cache/desktop_1b778089333a8789c8c7e566861930f62a4a502e.css.map (0.3ms)
Completed 200 OK in 7ms (ActiveRecord: 0.7ms)
```

The console error from firefox are looking like this:

`Content Security Policy: The page’s settings blocked the loading of a resource at http://35.228.xxx.xxx:3000/assets/preload-application-data-0a59ccab480941aaac91f9e7fa7f77496323ae056aaa4158822dea35de319c01.js (“script-src”).`

Does anyone has an idea on how to address this issue?
The discourse hostname is set to the correct IP and the port is the default one (3000) from the test.yaml.

**Comment by javsalgar** [comment]
Hi,

Could you show the changes you did in test.yaml? It seems to me that, for this specific case, you may also need an ingress rule

**Comment by tech348712013870132** [comment]
Hi @jav

This is my slightly modified config.yaml:

```
## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be use in producction.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: bitnami/postgresql
        name: postgresql
        env:
        #- name: POSTGRES_DB
          #value: bitnami_application
        - name: POSTGRES_USER
          value: postgres
        #- name: POSTGRES_PASSWORD
          #value: bitnami1
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: bitnami/redis
        name: redis
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes" 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: discourse
  name: discourse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discourse
  template:
    metadata:
      labels:
        app: discourse
    spec:
      containers:
      - image: bitnami/discourse
        name: discourse
        env:
        - name: POSTGRESQL_HOST
          value: postgresql
        - name: POSTGRESQL_ROOT_USER
          value: postgres
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
          value: bitnami_application
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
          value: bn_discourse
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
          value: bitnami1
        - name: DISCOURSE_POSTGRESQL_NAME
          value: bitnami_application
        - name: DISCOURSE_POSTGRESQL_USERNAME
          value: bn_discourse
        - name: DISCOURSE_POSTGRESQL_PASSWORD
          value: bitnami1
        - name: DISCOURSE_HOSTNAME
          value: "35.228.xxx.xxx"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT_NUMBER
          value: "6379"
---
apiVersion: v1
kind: Pod
metadata:
  name: sidekiq
  labels:
    app: sidekiq
spec:
  containers:
  - name: sidekiq
    image: bitnami/discourse
    args:
    - nami
    - start
    - --foreground
    - discourse-sidekiq
    env:
    - name: POSTGRESQL_HOST
      value: postgresql
    - name: POSTGRESQL_ROOT_USER
      value: postgres
    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
      value: bitnami_application
    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
      value: bn_discourse
    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
      value: bitnami1
    - name: DISCOURSE_POSTGRESQL_NAME
      value: bitnami_application
    - name: DISCOURSE_POSTGRESQL_USERNAME
      value: bn_discourse
    - name: DISCOURSE_POSTGRESQL_PASSWORD
      value: bitnami1
    - name: DISCOURSE_HOST
      value: discourse
    - name: DISCOURSE_PORT
      value: "3000"
    - name: DISCOURSE_HOSTNAME
      value: "35.228.xxx.xxx"
    - name: REDIS_HOST
      value: redis
    - name: REDIS_PORT_NUMBER
      value: "6379"
```

I've separated the discourse service in a separate yaml:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discourse
  name: discourse
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: custom-1
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: discourse
  sessionAffinity: None
  type: LoadBalancer
```

What do you mean with the ingress rule?
Why and how should the rule be implemented?

Thanks a lot for your support :)
